// Alerts table data. Each entry: { name, description, code }
const alertsTable = [
	{ name: "Noob-Power!", description: "Noob-Power! Dit is de standaard alert, als er geen alert in het donatiebericht staat", code: "<noobpower>" },
	{ name: "Voeg een URL toe", description: "Voeg een URL toe in je donatiebericht. Werkt in principe met elke link (als het laad), maar werkt het beste met Twitch of YouTube-links (YouTube-links met timestamps starten vanaf de ingestelde tijd). De afspeelduur is afhankelijk van het donatiebedrag (3 seconden + 1 seconde voor elke euro)", code: "<url>" },
	{ name: "€2,-", description: "Papa, mag ik alsjeblieft 2 euro voor de arme man die op straat staat te schreeuwen. <a href=\"https://www.youtube.com/watch?v=Fy-SqB2FiSQ\">Bron</a>", code: "<2euro>" },
	{ name: "Zelda CDI: Boring", description: "Gee, it sure is boring around here (van de intro van Link: The Faces of Evil voor de Philips CDI)", code: "<boring>" },
	{ name: "BREIN intro", description: "De inhoud van deze drager is beschermd door wetten van Intellectuele Eigendom waaronder de Auteurswet, de Wet op de Naburige Rechten, de Databankwet en de Beneluxmerkenwet.", code: "<brein>" },
	{ name: "Buurman & Buurman", description: "Speel de intro van Buurman & Buurman. Ajeto!", code: "<buurman>" },
	{ name: "Look at all this damage!", description: "<a href=\"https://www.youtube.com/watch?v=4B-JdfG6efI\">And we're going to repair it using flex shot</a>", code: "<damage>" },
	{ name: "Edd, Ed n Eddy: Deurbel", description: "Iemand belt aan bij de deurbel van Edd...", code: "<edd>" },
	{ name: "Hier, een euro!", description: "<a href=\"https://www.youtube.com/watch?v=HiLKVdNJt_o\">AAAAAAAAAAAAAA!</a>", code: "<euro>" },
	{ name: "Het is feest!", description: "<a href=\"https://www.youtube.com/watch?v=pchWYdcN6zA\">Joepie!</a>", code: "<feest>" },
	{ name: "Speel een geluidseffect!", description: "Speel een willekeurig geluidseffect af van 138 mogelijkheden. Kan van alles zijn", code: "<geluidseffect>" },
	{ name: "GIGACHAD", description: "<a href=\"https://www.youtube.com/watch?v=FuJwXZpqzB8\">GIGACHAD</a>", code: "<gigachad>" },
	{ name: "Habbo Hotel-melding", description: "Je donatiemelding als een Habbo-chatbericht. Wil iemand meubi?", code: "<habbo>" },
	{ name: "Hardheid", description: "Meet je hardheid, van 0% tot 100%!", code: "<hardheid>" },
	{ name: "Will Smith: That's Hot", description: "That's hot. Will Smith komt langs", code: "<hot>" },
	{ name: "Hotel Mario: dinner", description: "Deel 1 van de Hotel Mario intro. Nice of the Princess to invite us over for dinner ey Luigi", code: "<hotelmario>" },
	{ name: "Hugo Duro", description: "Hugo Duro, de Spaanse voetballer die ook wel bekend staat als Harde Hugo. <a href=\"https://nl.wikipedia.org/wiki/Hugo_Duro\">Hugo Duro op Wikipedia</a>", code: "<hugoduro>" },
	{ name: "Hotel Mario: Instructions", description: "Deel 3 van de Hotel Mario intro. If you need instructions on how to get through the hotel, check out the enclosed instruction book", code: "<instructions>" },
	{ name: "Zelda CDI: I won!", description: "Een cutscene van Link: The Faces of Evil waarin Link heeft gewonnen. <a href=\"https://www.youtube.com/watch?v=kahoWJOsjoc\">Bron</a>", code: "<iwon>" },
	{ name: "Like & Subscribe", description: "Een YouTuber-outro. Vergeet niet te liken en te subscriben en te commenten", code: "<likesubscribe>" },
	{ name: "Speel een potje Lingo", description: "Speel een potje Lingo met Lucille en JP! Gebruik !lingo in de chat om een woord te raden. Iedereen kan meedoen met Lingo! Let op: moeilijke woorden kunnen voorkomen.", code: "<lingo>" },
	{ name: "Ed, Edd n Eddy: Many Doors", description: "Many Doors (van Ed, Edd n Eddy). <a href=\"https://www.youtube.com/watch?v=Rq338WwBUpw\">Bron</a>", code: "<manydoors>" },
	{ name: "Windows Media Player", description: "Start Windows Media Player op. De video die afgespeeld wordt is één van 82 mogelijke video's. De subalert op twitch.tv/qastrol", code: "<mediaplayer>" },
	{ name: "Minecraft: graven", description: "Steve van Minecraft komt het scherm in graven", code: "<minecraft>" },
	{ name: "Reitse: Mosterd", description: "<a href=\"https://www.youtube.com/watch?v=V2IOzbM5n-Y\">Mosterd</a>", code: "<mosterd>" },
	{ name: "Michael Rosen: Noice", description: "<a href=\"https://www.youtube.com/watch?v=lg5WKsVnEA4\">Noice!</a>", code: "<noice>" },
	{ name: "Hotel Mario: Pesky Plumbers", description: "Deel 2 van de intro van Hotel Mario. Dear Pesky Plumbers, the koopalings and I have taken over the Mushroom Kingdom", code: "<peskyplumbers>" },
	{ name: "Vang een Pokémon", description: "Vang één Pokémon uit de eerste vijf generaties van Pokémon! (649 mogelijkheden)", code: "<pokemon>" },
	{ name: "Waarom dit paneel er niet professioneel uitziet?", description: "Omdat net als met mijn wachtscherm en pauze schermpjes en offline scherm ik het leuk vind zelf te tekenen omdat het juist grappig is als het zo lelijk is.", code: "<professioneel>" },
	{ name: "Qastrol moment", description: "Voor als Qastrol een ziek gaming moment heeft", code: "<qastrol>" },
	{ name: "Qastrol's microfoon", description: "Zet Qastrol's microfoon aan als die uit staat, of uit als die aan staat", code: "<qastrolmic>" },
	{ name: "Lekker Ite Mei Reitse", description: "Reitse Spanninga, de Fryske sjef. <a href=\"https://www.youtube.com/watch?v=5JUc8oMhm_k\">Bron</a>", code: "<reitse>" },
	{ name: "The Rock", description: "Hij is The Rock en hij is sus. <a href=\"https://www.youtube.com/watch?v=SnM_JxgBsFk\">Bron</a>", code: "<rock>" },
	{ name: "Zelda CDI Shopkeeper: Ropes, Bombs", description: "De shopkeeper van Link: The Faces of Evil. Ropes, Bombs, you want it? It's your's my friend as long as you have enough rubies. <a href=\"https://www.youtube.com/watch?v=J8XxuW-Orww\">Bron</a>", code: "<ropesbombs>" },
	{ name: "Samson is a DJ", description: "Samson is een DJ (1 seconde per euro). <a href=\"https://www.youtube.com/watch?v=gqW9J64kRXY\">Bron</a>", code: "<samsondj>" },
	{ name: "Smurf 6", description: "Het is smurf 6 (1 seconde per euro). <a href=\"https://www.youtube.com/watch?v=HfUYMG4yWpk\">Bron</a>", code: "<smurf6>" },
	{ name: "Zelda CDI Shopkeeper: Sorry Link", description: "De shopkeeper van Link: The Faces of Evil. Come back when you're a little richer! <a href=\"https://www.youtube.com/watch?v=J8XxuW-Orww\">Bron</a>", code: "<sorrylink>" },
	{ name: "Spongebob: Sports Channel", description: "Spongebob kijkt TV. <a href=\"https://www.youtube.com/watch?v=hPpTGwzeKVc\">Bron</a>", code: "<sportschannel>" },
	{ name: "taxonweb.be", description: "Vlaamse belastingaangifte. <a href=\"https://www.youtube.com/watch?v=KM7rDjaDcwg\">Trouwens, waarom doe je het niet direct? Anders vergeet je het nog.</a>", code: "<taxonweb>" },
	{ name: "The Room: I did not hit her!", description: "Tommy Wiseau begroet Mark. <a href=\"https://www.youtube.com/watch?v=6xdKTeqQcpo\">Bron</a>", code: "<theroom>" },
	{ name: "Geef iemand een timeout", description: "Wil je iemand uit de chat timeouten? Dat kan met een donatie! Mention een Twitch gebruiker in de donatie met @ (bijv. \"@Qastrol\"), je aantal euro's is de duur van de timeout die deze persoon krijgt", code: "<timeout>" },
	{ name: "Tongo", description: "De legendarische Tongo. <a href=\"https://www.youtube.com/watch?v=z-R5qrznusY\">Bron</a>", code: "<tongo>" },
	{ name: "Pokémon Trainer battle", description: "Een trainer gevecht in Pokémon!", code: "<trainer>" },
	{ name: "TROS", description: "<a href=\"https://www.youtube.com/watch?v=b8dXD8GOOm4\">De grootste familie van Nederland. </a>", code: "<tros>" },
	{ name: "Ultrahardheid", description: "Meet je ultrahardheid van 0% tot 10000%!", code: "<ultrahardheid>" },
	{ name: "Verder nergens om", description: "Maar we minen diamonds! (WOE!)", code: "<verdernergensom>" },
	{ name: "Maak jezelf VIP", description: "Maak jezelf VIP! Het aantal euro's dat je doneert is het aantal seconden dat je jezelf VIP maakt! Deze alert werkt alleen als je je eigen Twitch-naam gebruikt als donatienaam", code: "<vip>" },
	{ name: "Windows XP-melding", description: "Een Windows XP popup melding", code: "<windowsxp>" },
	{ name: "Eddy Wally: Wow", description: "Eddy Wally zegt \"wow\"", code: "<wow>" },
	{ name: "Zelda CDI: Tapijt", description: "Onderdeel van de intro van Link: The Faces of Evil voor de Philips CDI. Link vliegt op een tapijt", code: "<zeldatapijt>" },
	{ name: "De Slimste Mens: 3-6-9", description: "De eerste ronde van De Slimste Mens!", code: "<369>" },
	{ name: "Altijd blijven vissen!", description: "Wat er ook gebeurt, altijd blijven vissen! De nieuwste zomerhit van DJ Qastrol. (1 seconde per euro)", code: "<altijdblijvenvissen>" },
	{ name: "De dag die je niet vergeten mag", description: "Vergeet deze dag niet!", code: "<dedag>" },
	{ name: "Desert Bus", description: "De beruchte videogame Desert Bus, waarin je 8 uur lang één recht stuk vooruit rijd, verschijnt op beeld. <a href=\"https://en.wikipedia.org/wiki/Penn_%26_Teller%27s_Smoke_and_Mirrors#Desert_Bus\">Desert Bus op Wikipedia</a>", code: "<desertbus>" },
	{ name: "Oh Yeah Donkey Kong", description: "Donkey Kong wordt geplet door een Game Boy D: <a href=\"https://www.youtube.com/watch?v=ckLV8Lo89tY\">Bron</a>", code: "<ohyeahmrkrabs>" },
	{ name: "EK Voetbal 2024", description: "Throwback naar het EK van 2024 in Duitsland. Dit programma wordt mede mogelijk gemaakt door...", code: "<ek>" },
	{ name: "Vertel een mop", description: "Laat een mop vertellen op de stream! Gegarandeerd hillarisch 😂", code: "<mop>" },
	{ name: "Onthul je horoscoop", description: "Laat je horoscoop vertellen op stream! Deze horoscoop is 100% betrouwbaar", code: "<horoscoop>" },
	{ name: "Harde Partijen", description: "Dit programma wordt mede mogelijk gemaakt door harde partijen", code: "<hardepartijen>" },
	{ name: "Another Brick in the Wall", description: "Glefly Brauly zingt Another Brick in the Wall (Part 2) van Pink Floyd! (1 seconde per euro) <a href=\"https://www.youtube.com/watch?v=moShzA7xGTQ\">Bron</a>", code: "<brickinthewall>" },
	{ name: "HHGregg", description: "Christmas in July. <a href=\"https://www.youtube.com/watch?v=QJzt8L_i7_U\">Bron</a>", code: "<hhgregg>" },
	{ name: "200 Vissen: intro", description: "Weet u het nog toen Qastrol 200 vissen vangde? De intro voor de 200 Vissen stream op twitch.tv/qastrol", code: "<visintro>" },
	{ name: "Kapitein Koek", description: "De iconische Kapitein Koek reclame. MMMMMMMMMMMMMMM Lekker (de entrance van KanarieArie). <a href=\"https://www.youtube.com/watch?v=zvq6Mg8XN8A\">Bron</a>", code: "<kapiteinkoek>" },
	{ name: "Karpers, goudvissen", description: "Wat als karpers en goudvissen een YouTube kanaal hadden, en dit ze een intro video hadden?", code: "<karper>" },
	{ name: "Kaulo Boszhard", description: "Kaulo Boszhard (Amsterdam, 26 juni 1969) is een Nederlands televisiepresentator, acteur, zanger, tekstschrijver en imitator.", code: "<kauloboszhard>" },
	{ name: "KRO-NCRV", description: "Maak morgen mee, KRO-NCRV. <a href=\"https://www.youtube.com/watch?v=Roqx-JA_i1Q\">Bron</a>", code: "<kroncrv>" },
	{ name: "Kat", description: "Een kat komt over het beeld (lief) (de entrance animatie van Lieveheersbabe)", code: "<kat>" },
	{ name: "Mark Rutte", description: "Mark Rutte breekt in de WWE Lijsttrekkersdebat?! Live uitgezonden op twitch.tv/qastrol en Nederland 1", code: "<markrutte>" },
	{ name: "Mario Kart is Kaulo Hard", description: "Mario Kart is Kaulo Hard", code: "<mariokartkaulohard>" },
	{ name: "Mario Kart, maar wat doet de rest dan?", description: "🤨🤨", code: "<watdoetderest>" },
	{ name: "Vsauce", description: "Hey Vsauce, Michael here", code: "<vsauce>" },
	{ name: "Jean Mineur Mediavision", description: "POV je kijkt reclame in de bioscoop", code: "<bioscoop>" },
	{ name: "Narwal van der Zee!", description: "Hij zwemt door de zee (de entrance video van NarwalvanderZee)", code: "<narwal>" },
	{ name: "€3,- in het Duits", description: "Hast du bitte 3 euro! <a href=\"https://www.youtube.com/watch?v=Is2jTgxNctI\">Bron</a>", code: "<3euro>" },
	{ name: "WWE intro", description: "Now! Then! Forever! <a href=\"https://www.youtube.com/watch?v=551L0-4QMV0\">Bron</a>", code: "<wwe>" },
	{ name: "Mario Kart: Attention all Mario Kart gamers!", description: "Attention all Mario Kart gamers! Funky Kong needs your help! <a href=\"https://www.youtube.com/watch?v=qGz3KFdmaD0\">Bron</a>", code: "<attentiongamers>" },
	{ name: "Mario Kart: Blooper", description: "Een Blooper van Mario Kart spuit inkt over het scherm...", code: "<blooper>" },
	{ name: "Lego Island: Brick by Brick", description: "Brick by Brick van Lego Island wordt afgespeeld 😳", code: "<brickbybrick>" },
	{ name: "Mario Kart: Communication Error", description: "POV: je raakt gedisconnected in Mario Kart", code: "<communicationerror>" },
	{ name: "Dit is DVD reclame", description: "Dit is de geweldige DVD-technologie! <a href=\"https://www.youtube.com/watch?v=ZtlBCrP9ySo\">Bron</a>", code: "<dvd>" },
	{ name: "Fryslân", description: "Fryslân Boppe (de entrance animatie van DeJelman)", code: "<fryslan>" },
	{ name: "You got Noob-Power!", description: "Je krijgt Noob-Power in F-Zero X", code: "<fzeronoob>" },
	{ name: "GIGAVIS", description: "Het is de GIGACHAD van de vissen :O", code: "<gigavis>" },
	{ name: "Harde Koeksoep", description: "Een HARD die uit een koeksoep komt (de entrance animatie van Harde_Hugo)", code: "<hardekoeksoep>" },
	{ name: "Kruip in de huid van...", description: "Kruip in de huid van een bekend iemand...", code: "<kruipindehuid>" },
	{ name: "Nederland Kiest", description: "De intro van Nederland Kiest: Het WWE Lijsttrekkersdebat", code: "<nederlandkiest>" },
	{ name: "De Noobbewaarder", description: "Ik kan het weten, ik ben er zelf eens door gered", code: "<noobbewaarder>" },
	{ name: "NPO 1: even geduld", description: "Even geduld...", code: "<npo1>" },
	{ name: "Pokémon Sun and Moon dans", description: "Een trainer in Pokémon Sun en Moon die een Z-move dans doet (de entrance animatie van Weslyv8)", code: "<pokemondans>" },
	{ name: "Rainbow Road lied", description: "It's called a road, it's called a Rainbow Road. It's a road that you go", code: "<rainbowroad>" },
	{ name: "Reinhard Mey: Gute Nacht, Freunde", description: "Reinhard Mey wenst iedereen een goedenavond (1 euro per seconde). <a href=\"https://www.youtube.com/watch?v=6YnQc-AdNCI\">Bron</a>", code: "<reinhard>" },
	{ name: "Robbie Rotten", description: "Don't let your kids watch this! <a href=\"https://www.youtube.com/watch?v=MgffSUwTeKw\">Bron</a>", code: "<robbierotten>" },
	{ name: "SIE!", description: "JAAAA 😁😁🗣️NU heb ik hem echt goed 🗣️🗣️SIEEEEEE 🗣️🗣️ huh😮‍💨 Waaaaauuuuw😲 die was echt ziek man😌", code: "<sie>" },
	{ name: "NOS Radio Tourflits", description: "NOS Radio Tourflits, Tourflits, Tourflits. <a href=\"https://www.youtube.com/watch?v=Q2KX-SlzGv4\">Bron</a>", code: "<tourflits>" },
	{ name: "Turf", description: "Vissers uit Visblad TV lachen om turf 😂 <a href=\"https://www.youtube.com/watch?v=0pRjz8opWew\">Bron</a>", code: "<turf>" },
	{ name: "De Nieuwe Uri Geller", description: "<a href=\"https://www.youtube.com/watch?v=EjgLCJGFBfk\">Waarschuwing. De meeste optredens in deze show zijn levensgevaarlijk. Alleen goed getrainde, professionele mentalisten kunnen deze uitvoeren. Doe dit thuis nooit na!</a>", code: "<urigeller>" },
	{ name: "Donkey Kong: Very Hard", description: "Donkey Kong is HARD! <a href=\"https://www.youtube.com/watch?v=rWZ9xwK5gsk\">Bron</a>", code: "<veryhard>" },
	{ name: "Vis Moment", description: "VIS MOMENT", code: "<vismoment>" },
	{ name: "200 Vissen: Professioneel", description: "Waarom deze vis er niet professioneel uitziet? (uit de 200 vissen stream)", code: "<visprofessioneel>" },
	{ name: "Walter White speelt Mario Kart", description: " <a href=\"https://www.youtube.com/watch?v=1XSysnj2Bk0\">Bron</a>", code: "<walterwhite>" },
	{ name: "We vissen vissen", description: "Verder nergens om, maar we vissen vissen", code: "<wevissenvissen>" },
	{ name: "LordWout RuneScape Schaap", description: "Een schaap in RuneScape (de entrance animatie van Lord Wout)", code: "<woutschaap>" },
	{ name: "European Broadcasting Union", description: "De EBU, bekend van het songfestival", code: "<ebu>" },
	{ name: "Biem", description: "Star Fox 64, maar dan biem", code: "<biem>" },
	{ name: "Halo 3 x Zelda CDI", description: "Gee, it sure is boring around here", code: "<haloboring>" },
	{ name: "3D Hard", description: "HARD in 3D!", code: "<hard3d>" },
	{ name: "3D Hard met koeksoep", description: "HARD in 3D! (met een koeksoep)", code: "<hard3dkoeksoep>" },
	{ name: "Hardslide", description: "Hard over je beeldscherm", code: "<hardslide>" },
	{ name: "Kikkertj", description: "De Mother 3 autokikker rijd over het beeldscherm", code: "<kikkertje>" },
	{ name: "Minecraft with Gadget", description: "Ik ben hier met mijn goede vriend Inspector Gadget", code: "<minecraftwithgadget>" },
	{ name: "Mark Rutte WWE hype", description: "Live reactie op Mark Rutte die in het WWE Lijsttrekkersdebat breekt", code: "<ruttehype>" },
	{ name: "Qastrol op de WC", description: "Hij zit te poepen", code: "<wc>" },
	{ name: "De Westereen", description: "Wolkom yn 'e Westereen", code: "<westereen>" },
	{ name: "Zorgwekkend", description: "Een zorgwekkende video van iemand die <a href=\"https://www.youtube.com/watch?v=g3jCAyPai2Y\">Baka Mitai van Yakuza</a> zingt", code: "<zorgwekkend>" },
	{ name: "Donkey Kong: Uh Oh Sticky", description: "Je plakt vast in de honing", code: "<uhohsticky>" },
	{ name: "200 vissen gevangen!", description: "Gefeliciteerd Qastrol, je hebt het gedaan! 200 vissen, zie ze daar nou staan", code: "<200vissen>" },
	{ name: "Buurman & Buurman Kart", description: "De nieuwste racing game voor Nintendo Switch", code: "<buurmankart>" },
	{ name: "DJ Yolotanker", description: "Het is de Samson en Gert mix van DJ Yolotanker (2 seconden per euro). <a href=\"https://www.youtube.com/watch?v=LKlRQGrUAo0\">Bron</a>", code: "<djyolotanker>" },
	{ name: "Hey", description: "Vsauce Michael, maar hij zegt alleen nog \"Hey\" in elke Vsauce aflevering", code: "<hey>" },
	{ name: "Mythbusters intro", description: "💩 <a href=\"https://www.youtube.com/watch?v=2stoFFvfEyg\">Bron</a>", code: "<mythbusters>" },
	{ name: "YouTube 2007 tutorial", description: "Hallo!!!! Vergeet niet om de video 5 sterren te geven!!!!", code: "<tutorial>" },
	{ name: "150 goals gescoord", description: "Gefeliciteerd Qastrol, je hebt het gedaan! 150 doelpunten zie de ballen daar staan!", code: "<150goals>" },
	{ name: "7 GRAND FEEST", description: "GRAND FEEST?! FLEENTSTONES? GRAND FEEST? <a href=\"https://www.youtube.com/watch?v=nF-xdiL7Nr0\">Bron</a>", code: "<7grandfeest>" },
	{ name: "Black Mesa Announcement System", description: "Vervangt de TTS met de Black Mesa Announcement System van Half Life 1. Bekijk de volgende link voor alle ondersteunde woorden en zet deze in het donatiebericht (dit zijn de enige woorden die met deze alert werken): <a href=\"https://tz-dev.github.io/hl_text2speech/index.html\">https://tz-dev.github.io/hl_text2speech/index.html</a>. Let op: bij deze alert werken de reguliere TTS stemmen of sound effects <strong>niet</strong>", code: "<bmas>" },
	{ name: "Google Gemini AI", description: "De ChatGPT-concurrent van Google. Je donatiebericht is je bericht of vraag naar Gemini.", code: "<gemini>" },
	{ name: "Kattenfoto van Qastrol's kat", description: "Krijg een foto te zien van Qastrol's kat. Er zijn 100 mogelijkheden", code: "<kattenfoto>" },
	{ name: "Among Us Ejected", description: "Eject iets of iemand met je donatie. Voeg het gene dat je wil ejecten in je donatiebericht met \"\" (bijvoorbeeld \"koek en brokken\" eject koek en brokken)", code: "<amongus>" },
	{ name: "Wild Pokémon battle", description: "Een Pokémon gevecht in het wild!", code: "<wildpokemon>" },
	{ name: "Gerard Joling - Mexico", description: "Ik ben naar Mexico gekomen! De afspeelduur is afhankelijk van je donatiebedrag (1 euro = 1 seconde)", code: "<mexico>" },
	{ name: "Poker", description: "Speel een soort van poker. Je pakt vijf willekeurige kaarten, die vervolgens een score krijgen. <a href=\"https://balatrogame.fandom.com/wiki/Poker_Hands\">De scoreberekening is hetzelfde als in Balatro: (chips + handwaarde) * mult</a>", code: "<poker>" },
	{ name: "Hot Potato", description: "Start één potje Hot Potato in de chat. De \"Hot Potato\" wordt gepasst naar een willekeurig iemand in de chat, en die heeft 15 seconden om de hot potato te passen aan iemand anders met !pass. Als dit 30 keer lukt, is het spel voorbij en moet Qastrol één euro doneren. <a href=\"https://tawmae.github.io/hot_potato.html\">Kijk hier voor meer informatie over Hot Potato</a>", code: "<hotpotato>" },
	{ name: "How", description: " <a href=\"https://www.youtube.com/watch?v=6M-NkQAo-3E\">van de \"What\" meme</a>", code: "<how>" },
	{ name: "Kruidvat schepsnoep", description: "Welke kruidvat schepsnoep ben jij? Kom er achter met deze alert. 34 mogelijkheden", code: "<kruidvat>" },
	{ name: "QAS GAS IS Z", description: "Wanneer je meedoet aan een <a href = \"https://twitch.tv/muntjesman\">Muntjesman Nintendo 64 Toernooi</a>, maar ineens vergeet hoe je gas geeft in de game <a href = \"https://en.wikipedia.org/wiki/Extreme-G\">Extreme-G</a>", code: "<qasgasisz>" },
	{ name: "Play it Forward: Gameboy intro", description: "Wanneer je je Gameboy opstart (Play it Forward-stijl)", code: "<gameboy>" },
	{ name: "Kingler zegt \"koekie\"", description: "<a href=\"https://www.youtube.com/watch?v=J1Y2CJMWxwA\">Kingler van Pokémon Puzzle League</a> zegt \"koekie\"", code: "<koekie>" },
	{ name: "Unregistered Hypercam 2", description: "Wanneer je een YouTube Tutorial kijkt in 2005 met Unregistered Hypercam 2 en <a href=\"https://www.youtube.com/watch?v=0Xa3lfd0ukk\">Dreamscape van 009 Sound System</a>", code: "<hypercam>" },
	{ name: "Peggle: Extreme Fever", description: "<a href=\"https://www.youtube.com/watch?v=wXB_5A8UbWI\">Je voltooit een Peggle level en Ode to Joy begint te spelen</a>", code: "<peggle>" },
	{ name: "Don eren", description: "!don eer, ik eer Don", code: "<doneren>" },
	{ name: "Zelda CDI: This is illegal you know", description: "<a href=\"https://www.youtube.com/watch?v=kr_Xw3sTgRk\">Eén van de meest illegale cutscenes in de CDI Zelda spellen</a>", code: "<illegal>" },
	{ name: "Zelda CDI: Somebody that Morshu used to know", description: "<a href=\"https://www.youtube.com/watch?v=MNyxXxyavVw\">Morshu zingt \"Somebody I used to know\"</a>", code: "<somebody>" },
	{ name: "Zelda CDI: You Reposted In The Wrong Shop", description: "<a href=\"https://www.youtube.com/watch?v=m20cGdohWic\">You reposted in the wrong neighbourhood</a>", code: "<reposted>" },
	{ name: "Play it Forward Nederland 1", description: "Een Play it Forward-logo in de stijl van het jaren '90 Nederland 1 logo, met een sound effect", code: "<playitforward>" },
	{ name: "1, 2, Koeksoep", description: "Beschrijving voor 12koeksoep", code: "<12koeksoep>" },
	{ name: "Stel je vraag aan AI Qastrol", description: "AI Qastrol beantwoord al je vragen. Let op: dit vervangt de text to speech", code: "<aiqastrol>" },
	{ name: "Nintendo Alarmo - HARDe wekker", description: "Zo wordt je HARD wakker", code: "<alarmo>" },
	{ name: "Banaantje", description: "Hugo zegt 'banaantje'", code: "<banaantje>" },
	{ name: "BBC Sounds archief", description: "Speel een willekeurig geluid van het BBC Sounds archief, een archief met duizenden geluiden van oude BBC hoorspellen. Kan van alles zijn", code: "<bbcsound>" },
	{ name: "Bobba-filter", description: "Gaat Qastrol, Lord Wout of Harde Hugo een heftig woord zeggen? Filter het eruit met het Bobba-filter", code: "<bobba>" },
	{ name: "Kerstknallers - Centstorm", description: "Een KerstKnallers Centstorm, maar dan bij elk bedrag", code: "<centstorm>" },
	{ name: "Clear Chat", description: "Wil je de chat leeg maken? Dat kan met deze alert!", code: "<clearchat>" },
	{ name: "Alert voor dghhps", description: "Beschrijving voor dghhps", code: "<dghhps>" },
	{ name: "Followmode", description: "Ben je klaar met non-followers die chatten? Met deze alert kan je followmode tijdelijk aanzetten. Je donatiebedrag is het aantal seconden dat followmode actief is", code: "<followmode>" },
	{ name: "Gamerwolde", description: "Hier wonen alleen gamers. <a href=\"https://maps.app.goo.gl/qXf4gykkbomkTbASA\">Gamerwolde op Google Maps</a>", code: "<gamerwolde>" },
	{ name: "Alert voor genieter", description: "Beschrijving voor genieter", code: "<genieter>" },
	{ name: "Stuur een GIPHY-gifje", description: "Stuur een gifje van GIPHY. De tekst die je tussen aanhalingstekens doet, is je zoekopdracht naar een gifje (bijv. \"Christmas\" zoekt de eerste .gif op met Christmas). Let op: een gifje kan mogelijk niet beschikbaar zijn", code: "<gif>" },
	{ name: "Alert voor griddy", description: "Beschrijving voor griddy", code: "<griddy>" },
	{ name: "Halo Theme", description: "Speel de Halo-themesong af onder je TTS-bericht", code: "<halotheme>" },
	{ name: "Keep it hardcore", description: "De titelsong van Wrestling Empire van MDickie. Come on do it! Come on do it! <a href=\"https://www.youtube.com/watch?v=U4eCMaf_UpI\">Bron</a>", code: "<hardcore>" },
	{ name: "Alert voor hardehugo", description: "Beschrijving voor hardehugo", code: "<hardehugo>" },
	{ name: "Alert voor hardeintro", description: "Beschrijving voor hardeintro", code: "<hardeintro>" },
	{ name: "Alert voor hardstuff", description: "Beschrijving voor hardstuff", code: "<hardstuff>" },
	{ name: "Harry Piekema was het!", description: "sus", code: "<harrypiekema>" },
	{ name: "Alert voor hugodisconnect", description: "Beschrijving voor hugodisconnect", code: "<hugodisconnect>" },
	{ name: "Alert voor hugojebentstoer", description: "Beschrijving voor hugojebentstoer", code: "<hugojebentstoer>" },
	{ name: "Alert voor hugowwe", description: "Beschrijving voor hugowwe", code: "<hugowwe>" },
	{ name: "I am Steve", description: "Hij is Steve (van A Minecraft Movie). <a href=\"https://www.youtube.com/watch?v=ykEjEcjPXEE\">Bron</a>", code: "<iamsteve>" },
	{ name: "Karbonkel", description: "Karbonkel laat Mik schrikken 😱 (van Ik Mik Loreland)", code: "<karbonkel>" },
	{ name: "Alert voor kersthuid", description: "Beschrijving voor kersthuid", code: "<kersthuid>" },
	{ name: "Alert voor kerstknallers", description: "Beschrijving voor kerstknallers", code: "<kerstknallers>" },
	{ name: "Alert voor kerstonweb", description: "Beschrijving voor kerstonweb", code: "<kerstonweb>" },
	{ name: "Knolpower!", description: "Het is tijd voor wat knolpower!", code: "<knolpower>" },
	{ name: "Alert voor koprol", description: "Beschrijving voor koprol", code: "<koprol>" },
	{ name: "Labor Day song", description: "Het traditionele labor day lied. <a href=\"https://youtu.be/HmeKhjkTOn8?feature=shared&t=1098\">Bron</a>", code: "<laborday>" },
	{ name: "Alert voor lordwout", description: "Beschrijving voor lordwout", code: "<lordwout>" },
	{ name: "Alert voor moviequiz", description: "Beschrijving voor moviequiz", code: "<moviequiz>" },
	{ name: "Geen alert", description: "Wil je helemaal geen alert? Kies dan de <niks> alert", code: "<niks>" },
	{ name: "NPO 1 Tune", description: "Speel de NPO 1 tune onder je donatiebericht", code: "<npo1tune>" },
	{ name: "NPO 2 Tune", description: "Speel de NPO 2 tune onder je donatiebericht", code: "<npo2tune>" },
	{ name: "Ollama AI", description: "Stel je vraag aan Ollama AI", code: "<ollama>" },
	{ name: "Omegahardheid", description: "Meet je omegahardheid! Nog HARDer dan ultrahardheid, met hardheid tot 1000000% hardheid!", code: "<omegahardheid>" },
	{ name: "Quantumhardheid", description: "De allerhardste hardheid ooit, met gevaarlijk hoge waardes tot wel 100000000% hardheid!", code: "<quantumhardheid>" },
	{ name: "¡Qué pasa, NENG!", description: "Een vervloekte Spaanse videogame. <a href=\"https://www.youtube.com/watch?v=sIdKvagWf9I\">Bron</a>", code: "<quepasaneng>" },
	{ name: "Alert voor random", description: "Beschrijving voor random", code: "<random>" },
	{ name: "Samson & Gert intro", description: "Speel het Samson & Gert intronummer onder je TTS-bericht af", code: "<samsonengert>" },
	{ name: "Schnappi Scary Skeleton", description: "Ich bin Schnappi das Krokodil <a href=\"https://www.youtube.com/watch?v=P3ynj6w2tII\">Bron</a>", code: "<skeleton>" },
	{ name: "Alert voor supermarkt", description: "Beschrijving voor supermarkt", code: "<supermarkt>" },
	{ name: "Alert voor thanos", description: "Beschrijving voor thanos", code: "<thanos>" },
	{ name: "Louis van Gaal", description: "Een beruchte Engelse uitspraak van Louis van Gaal wordt afgespeeld. Dit kunnen 22 uitspraken zijn", code: "<vangaal>" },
	{ name: "Alert voor videogamequiz", description: "Beschrijving voor videogamequiz", code: "<videogamequiz>" },
	{ name: "Het is (vissen)feest", description: "Het is feest van Mona, maar dan met een vis!", code: "<visfeest>" },
	{ name: "VIS GET!", description: "Je hebt een vis gevangen (van de 200 vissen livestream)", code: "<visgevangen>" },
	{ name: "Kruip in de vissenhuid van", description: "Wordt een vis! (van de 200 vissen livestream)", code: "<vissenhuid>" },
	{ name: "De vlag gaat eruit", description: "yaaaaaaaay", code: "<vlag>" },
	{ name: "Voetbal Moment", description: "Een soort YouTuber-intro maar dan voor voetbal", code: "<voetbalmoment>" },
	{ name: "VTube: Gollum", description: "Qastrol heeft nu een Vtube-camera van Gollum van The Lord of The Rings", code: "<vtubegollum>" },
	{ name: "VTube: Hond", description: "Qastrol heeft nu een Vtube-camera van een hond", code: "<vtubehond>" },
	{ name: "VTube: Jerma985", description: "Qastrol heeft nu een Vtube-camera van Jerma985", code: "<vtubejerma>" },
	{ name: "VTube: Kat", description: "Qastrol heeft nu een VTube-camera van een kat", code: "<vtubekat>" },
	{ name: "VTube: Pichu", description: "Qastrol krijgt een VTube-camera van Pichu van de Pokémon-serie", code: "<vtubepichu>" },
	{ name: "VTube: Rotom", description: "Qastrol heeft nu een VTube-camera van Rotom van Pokémon", code: "<vtuberotom>" },
	{ name: "Vtube: Soyjack", description: "Qastrol heeft nu een VTube-camera van Soyjack, de meme van de wijzende persoon", code: "<vtubesoyjack>" },
	{ name: "VTube: Uitzetten", description: "Als de VTube camera aanstaat, kan je deze zo weer uit zetten", code: "<vtubeuit>" },
	{ name: "VTube: Vis", description: "Qastrol wordt de eerste vis Vtuber", code: "<vtubevis>" },
	{ name: "VTube: Yee", description: "Qastrol heeft nu een VTube-camera van een dino", code: "<vtubeyee>" },
	{ name: "Verder nergens om maar we scoren goals", description: "WOE", code: "<wescorengoals>" },
	{ name: "Windows 95 melding", description: "Een pop-up melding in Windows 95", code: "<windows95>" },
	{ name: "Alert voor woutdisconnect", description: "Beschrijving voor woutdisconnect", code: "<woutdisconnect>" },
	{ name: "Zelda CDI in het Nederlands", description: "Ooh jongen, ik verveel me te pletter. (de intro van Link: The Face of Evil in het Nederlands) <a href=\"https://www.youtube.com/watch?v=M2tskI83V6g\">Bron</a>", code: "<zeldanl>" },
	{ name: "Zin in maandag", description: "Voor als je uitkijkt naar maandag, de start van een nieuwe werkweek. <a href=\"https://www.youtube.com/watch?v=X728AwdIQT4\">Bron</a>", code: "<zininmaandag>" },
	{ name: "Alert voor 5euro", description: "Beschrijving voor 5euro", code: "<5euro>" },
	{ name: "Alert voor adoringfan", description: "Beschrijving voor adoringfan", code: "<adoringfan>" },
	{ name: "Alert voor attention", description: "Beschrijving voor attention", code: "<attention>" },
	{ name: "Alert voor baksteene", description: "Beschrijving voor baksteene", code: "<baksteene>" },
	{ name: "Alert voor boek", description: "Beschrijving voor boek", code: "<boek>" },
	{ name: "Alert voor boek2", description: "Beschrijving voor boek2", code: "<boek2>" },
	{ name: "Alert voor bos", description: "Beschrijving voor bos", code: "<bos>" },
	{ name: "Alert voor bowserbrief", description: "Beschrijving voor bowserbrief", code: "<bowserbrief>" },
	{ name: "Alert voor browser", description: "Beschrijving voor browser", code: "<browser>" },
	{ name: "Alert voor cj", description: "Beschrijving voor cj", code: "<cj>" },
	{ name: "Alert voor community", description: "Beschrijving voor community", code: "<community>" },
	{ name: "Alert voor dejelman", description: "Beschrijving voor dejelman", code: "<dejelman>" },
	{ name: "Alert voor dominoday", description: "Beschrijving voor dominoday", code: "<dominoday>" },
	{ name: "Alert voor doneer", description: "Beschrijving voor doneer", code: "<doneer>" },
	{ name: "Alert voor eddywally", description: "Beschrijving voor eddywally", code: "<eddywally>" },
	{ name: "Alert voor emergencymeeting", description: "Beschrijving voor emergencymeeting", code: "<emergencymeeting>" },
	{ name: "Alert voor estate", description: "Beschrijving voor estate", code: "<estate>" },
	{ name: "Alert voor fever", description: "Beschrijving voor fever", code: "<fever>" },
	{ name: "Alert voor geenklier", description: "Beschrijving voor geenklier", code: "<geenklier>" },
	{ name: "Alert voor geenneus", description: "Beschrijving voor geenneus", code: "<geenneus>" },
	{ name: "Alert voor hard", description: "Beschrijving voor hard", code: "<hard>" },
	{ name: "Alert voor hardkoeksoep", description: "Beschrijving voor hardkoeksoep", code: "<hardkoeksoep>" },
	{ name: "Alert voor hello", description: "Beschrijving voor hello", code: "<hello>" },
	{ name: "Alert voor hie", description: "Beschrijving voor hie", code: "<hie>" },
	{ name: "Alert voor hiereeneuro", description: "Beschrijving voor hiereeneuro", code: "<hiereeneuro>" },
	{ name: "Alert voor hondbed", description: "Beschrijving voor hondbed", code: "<hondbed>" },
	{ name: "Alert voor hondlopen", description: "Beschrijving voor hondlopen", code: "<hondlopen>" },
	{ name: "Alert voor hondwijs", description: "Beschrijving voor hondwijs", code: "<hondwijs>" },
	{ name: "Alert voor humbertotantoe", description: "Beschrijving voor humbertotantoe", code: "<humbertotantoe>" },
	{ name: "Alert voor instructionbook", description: "Beschrijving voor instructionbook", code: "<instructionbook>" },
	{ name: "Alert voor jeanmineur", description: "Beschrijving voor jeanmineur", code: "<jeanmineur>" },
	{ name: "Alert voor karpergoudvis", description: "Beschrijving voor karpergoudvis", code: "<karpergoudvis>" },
	{ name: "Alert voor katje", description: "Beschrijving voor katje", code: "<katje>" },
	{ name: "Alert voor kauloperron", description: "Beschrijving voor kauloperron", code: "<kauloperron>" },
	{ name: "Alert voor kippenrijder", description: "Beschrijving voor kippenrijder", code: "<kippenrijder>" },
	{ name: "Alert voor labourday", description: "Beschrijving voor labourday", code: "<labourday>" },
	{ name: "Alert voor linkwritten", description: "Beschrijving voor linkwritten", code: "<linkwritten>" },
	{ name: "Alert voor mariokartworld", description: "Beschrijving voor mariokartworld", code: "<mariokartworld>" },
	{ name: "Alert voor missionpassed", description: "Beschrijving voor missionpassed", code: "<missionpassed>" },
	{ name: "Alert voor morshu", description: "Beschrijving voor morshu", code: "<morshu>" },
	{ name: "Alert voor morshushop", description: "Beschrijving voor morshushop", code: "<morshushop>" },
	{ name: "Alert voor netflix", description: "Beschrijving voor netflix", code: "<netflix>" },
	{ name: "Alert voor nintendodirect", description: "Beschrijving voor nintendodirect", code: "<nintendodirect>" },
	{ name: "Alert voor nos", description: "Beschrijving voor nos", code: "<nos>" },
	{ name: "Alert voor pannenkoek", description: "Beschrijving voor pannenkoek", code: "<pannenkoek>" },
	{ name: "Alert voor peggle3", description: "Beschrijving voor peggle3", code: "<peggle3>" },
	{ name: "Alert voor qastroldirect", description: "Beschrijving voor qastroldirect", code: "<qastroldirect>" },
	{ name: "Alert voor reported", description: "Beschrijving voor reported", code: "<reported>" },
	{ name: "Alert voor rutte", description: "Beschrijving voor rutte", code: "<rutte>" },
	{ name: "Alert voor shrekhorror", description: "Beschrijving voor shrekhorror", code: "<shrekhorror>" },
	{ name: "Alert voor sjors", description: "Beschrijving voor sjors", code: "<sjors>" },
	{ name: "Alert voor snipe", description: "Beschrijving voor snipe", code: "<snipe>" },
	{ name: "Alert voor spongebob", description: "Beschrijving voor spongebob", code: "<spongebob>" },
	{ name: "Alert voor stevestarwars", description: "Beschrijving voor stevestarwars", code: "<stevestarwars>" },
	{ name: "Alert voor stop", description: "Beschrijving voor stop", code: "<stop>" },
	{ name: "Alert voor subscribelike", description: "Beschrijving voor subscribelike", code: "<subscribelike>" },
	{ name: "Alert voor tellsell", description: "Beschrijving voor tellsell", code: "<tellsell>" },
	{ name: "Alert voor tremblingfingers", description: "Beschrijving voor tremblingfingers", code: "<tremblingfingers>" },
	{ name: "Alert voor usedtoknow", description: "Beschrijving voor usedtoknow", code: "<usedtoknow>" },
	{ name: "Alert voor vrolijkpalen", description: "Beschrijving voor vrolijkpalen", code: "<vrolijkpalen>" },
	{ name: "Alert voor waarschuwing", description: "Beschrijving voor waarschuwing", code: "<waarschuwing>" },
	{ name: "Alert voor walta", description: "Beschrijving voor walta", code: "<walta>" },
	{ name: "Alert voor warnerbros", description: "Beschrijving voor warnerbros", code: "<warnerbros>" },
	{ name: "Alert voor welkomdatjekijkt", description: "Beschrijving voor welkomdatjekijkt", code: "<welkomdatjekijkt>" },
	{ name: "Alert voor weminendiamonds", description: "Beschrijving voor weminendiamonds", code: "<weminendiamonds>" },
	{ name: "Alert voor weslyv8", description: "Beschrijving voor weslyv8", code: "<weslyv8>" },
	{ name: "Alert voor woutmoment", description: "Beschrijving voor woutmoment", code: "<woutmoment>" },
	{ name: "Alert voor xbox", description: "Beschrijving voor xbox", code: "<xbox>" },
	{ name: "Alert voor youtube", description: "Beschrijving voor youtube", code: "<youtube>" },
	{ name: "Alert voor zwolle", description: "Beschrijving voor zwolle", code: "<zwolle>" },
	{ name: "Alert voor odyssey", description: "Beschrijving voor odyssey", code: "<odyssey>" }

];