
// Alerts table data. Each entry: { name, description, code }
const alertsTable = [
	{ name: "Noob-Power!", description: "Noob-Power! Dit is de standaard alert, als er geen alert in het donatiebericht staat", code: "<noobpower>", year: 2024, category: ["Qastrol"], type: "Audio-alert"},
	{ name: "Voeg een URL toe", description: "Voeg een URL toe in je donatiebericht. Werkt in principe met elke link (als het laad), maar werkt het beste met Twitch of YouTube-links (YouTube-links met timestamps starten vanaf de ingestelde tijd). De afspeelduur is afhankelijk van het donatiebedrag (3 seconden + 1 seconde voor elke euro)", code: "<url>", year: 2024, category: ["Twitch"], type: "Interactieve alert"},
	{ name: "€2,-", description: "Papa, mag ik alsjeblieft 2 euro voor de arme man die op straat staat te schreeuwen. <a href=\"https://www.youtube.com/watch?v=Fy-SqB2FiSQ\">Bron</a>", code: "<2euro>", year: 2024, category: ["TV"], type: "Video-alert"},
	{ name: "Zelda CDI: Boring", description: "Gee, it sure is boring around here (van de intro van Link: The Faces of Evil voor de Philips CDI)", code: "<boring>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "BREIN intro", description: "De inhoud van deze drager is beschermd door wetten van Intellectuele Eigendom waaronder de Auteurswet, de Wet op de Naburige Rechten, de Databankwet en de Beneluxmerkenwet.", code: "<brein>", category: ["Film"], type: "Video-alert", year: 2024},
	{ name: "Buurman & Buurman", description: "Speel de intro van Buurman & Buurman. Ajeto!", code: "<buurman>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Look at all this damage!", description: "<a href=\"https://www.youtube.com/watch?v=4B-JdfG6efI\">And we're going to repair it using flex shot</a>", code: "<damage>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Edd, Ed n Eddy: Deurbel", description: "Iemand belt aan bij de deurbel van Edd...", code: "<edd>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Hier, een euro!", description: "<a href=\"https://www.youtube.com/watch?v=HiLKVdNJt_o\">AAAAAAAAAAAAAA!</a>", code: "<euro>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Het is feest!", description: "<a href=\"https://www.youtube.com/watch?v=pchWYdcN6zA\">Joepie!</a>", code: "<feest>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Speel een geluidseffect!", description: "Speel een willekeurig geluidseffect af van 138 mogelijkheden. Kan van alles zijn", code: "<geluidseffect>", category: ["Internet", "TV", "Radio", "Film", "Gaming"], type: "Audio-alert", year: 2024},
	{ name: "GIGACHAD", description: "<a href=\"https://www.youtube.com/watch?v=FuJwXZpqzB8\">GIGACHAD</a>", code: "<gigachad>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Habbo Hotel-melding", description: "Je donatiemelding als een Habbo-chatbericht. Wil iemand meubi?", code: "<habbo>", category: ["Internet", "Gaming"], type: "Audio-alert", year: 2024},
	{ name: "Hardheid", description: "Meet je hardheid, van 0% tot 100%!", code: "<hardheid>", category: ["Harde Hugo"], type: "Audio-alert", year: 2024},
	{ name: "Will Smith: That's Hot", description: "That's hot. Will Smith komt langs", code: "<hot>", category: ["Meme", "Internet"], type: "Video-alert", year: 2024},
	{ name: "Hotel Mario: dinner", description: "Deel 1 van de Hotel Mario intro. Nice of the Princess to invite us over for dinner ey Luigi", code: "<hotelmario>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Hugo Duro", description: "Hugo Duro, de Spaanse voetballer die ook wel bekend staat als Harde Hugo. <a href=\"https://nl.wikipedia.org/wiki/Hugo_Duro\">Hugo Duro op Wikipedia</a>", code: "<hugoduro>", category: ["Harde Hugo", "Sport"], type: "Video-alert", year: 2024},
	{ name: "Hotel Mario: Instructions", description: "Deel 3 van de Hotel Mario intro. If you need instructions on how to get through the hotel, check out the enclosed instruction book", code: "<instructions>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Zelda CDI: I won!", description: "Een cutscene van Link: The Faces of Evil waarin Link heeft gewonnen. <a href=\"https://www.youtube.com/watch?v=kahoWJOsjoc\">Bron</a>", code: "<iwon>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Like & Subscribe", description: "Een YouTuber-outro. Vergeet niet te liken en te subscriben en te commenten", code: "<likesubscribe>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Speel een potje Lingo", description: "Speel een potje Lingo met Lucille en JP! Gebruik !lingo in de chat om een woord te raden. Iedereen kan meedoen met Lingo! Let op: moeilijke woorden kunnen voorkomen.", code: "<lingo>", category: ["TV"], type: "Interactieve alert", year: 2024},
	{ name: "Ed, Edd n Eddy: Many Doors", description: "Many Doors (van Ed, Edd n Eddy). <a href=\"https://www.youtube.com/watch?v=Rq338WwBUpw\">Bron</a>", code: "<manydoors>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Windows Media Player", description: "Start Windows Media Player op. De video die afgespeeld wordt is één van 82 mogelijke video's. De subalert op twitch.tv/qastrol", code: "<mediaplayer>", category: ["Computer", "Qastrol"], type: "Video-alert", year: 2024},
	{ name: "Minecraft: graven", description: "Steve van Minecraft komt het scherm in graven", code: "<minecraft>", category: ["Gaming", "Qastrol"], type: "Video-alert", year: 2024},
	{ name: "Reitse: Mosterd", description: "<a href=\"https://www.youtube.com/watch?v=V2IOzbM5n-Y\">Mosterd</a>", code: "<mosterd>", category: ["TV", "Fryslân"], type: "Video-alert", year: 2024},
	{ name: "Michael Rosen: Noice", description: "<a href=\"https://www.youtube.com/watch?v=lg5WKsVnEA4\">Noice!</a>", code: "<noice>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Hotel Mario: Pesky Plumbers", description: "Deel 2 van de intro van Hotel Mario. Dear Pesky Plumbers, the koopalings and I have taken over the Mushroom Kingdom", code: "<peskyplumbers>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Vang een Pokémon", description: "Vang één Pokémon uit de eerste vijf generaties van Pokémon! (649 mogelijkheden)", code: "<pokemon>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Waarom dit paneel er niet professioneel uitziet?", description: "Omdat net als met mijn wachtscherm en pauze schermpjes en offline scherm ik het leuk vind zelf te tekenen omdat het juist grappig is als het zo lelijk is.", code: "<professioneel>", category: ["Internet", "Meme"], type: "Video-alert", year: 2024},
	{ name: "Qastrol moment", description: "Voor als Qastrol een ziek gaming moment heeft", code: "<qastrol>", category: ["Intro", "Qastrol"], type: "Video-alert", year: 2024},
	{ name: "Qastrol's microfoon", description: "Zet Qastrol's microfoon aan als die uit staat, of uit als die aan staat", code: "<qastrolmic>", category: ["Qastrol"], type: "Interactieve alert", year: 2024},
	{ name: "Lekker Ite Mei Reitse", description: "Reitse Spanninga, de Fryske sjef. <a href=\"https://www.youtube.com/watch?v=5JUc8oMhm_k\">Bron</a>", code: "<reitse>", category: ["TV", "Fryslân"], type: "Video-alert", year: 2024},
	{ name: "The Rock", description: "Hij is The Rock en hij is sus. <a href=\"https://www.youtube.com/watch?v=SnM_JxgBsFk\">Bron</a>", code: "<rock>", category: ["Meme", "Sport"], type: "Video-alert", year: 2024},
	{ name: "Zelda CDI Shopkeeper: Ropes, Bombs", description: "De shopkeeper van Link: The Faces of Evil. Ropes, Bombs, you want it? It's your's my friend as long as you have enough rubies. <a href=\"https://www.youtube.com/watch?v=J8XxuW-Orww\">Bron</a>", code: "<ropesbombs>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Samson is a DJ", description: "Samson is een DJ (1 seconde per euro). <a href=\"https://www.youtube.com/watch?v=gqW9J64kRXY\">Bron</a>", code: "<samsondj>", category: ["TV", "Muziek"], type: "Video-alert", year: 2024},
	{ name: "Smurf 6", description: "Het is smurf 6 (1 seconde per euro). <a href=\"https://www.youtube.com/watch?v=HfUYMG4yWpk\">Bron</a>", code: "<smurf6>", category: ["Internet", "Meme", "KerstKnallers"], type: "Video-alert", year: 2024},
	{ name: "Zelda CDI Shopkeeper: Sorry Link", description: "De shopkeeper van Link: The Faces of Evil. Come back when you're a little richer! <a href=\"https://www.youtube.com/watch?v=J8XxuW-Orww\">Bron</a>", code: "<sorrylink>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Spongebob: Sports Channel", description: "Spongebob kijkt TV. <a href=\"https://www.youtube.com/watch?v=hPpTGwzeKVc\">Bron</a>", code: "<sportschannel>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "taxonweb.be", description: "Vlaamse belastingaangifte. <a href=\"https://www.youtube.com/watch?v=KM7rDjaDcwg\">Trouwens, waarom doe je het niet direct? Anders vergeet je het nog.</a>", code: "<taxonweb>", category: ["TV", "België"], type: "Video-alert", year: 2024},
	{ name: "The Room: I did not hit her!", description: "Tommy Wiseau begroet Mark. <a href=\"https://www.youtube.com/watch?v=6xdKTeqQcpo\">Bron</a>", code: "<theroom>", category: ["Film", "Meme"], type: "Video-alert", year: 2024},
	{ name: "Geef iemand een timeout", description: "Wil je iemand uit de chat timeouten? Dat kan met een donatie! Mention een Twitch gebruiker in de donatie met @ (bijv. \"@Qastrol\"), je aantal euro's is de duur van de timeout die deze persoon krijgt", code: "<timeout>", category: ["Twitch"], type: "Interactieve alert", year: 2024},
	{ name: "Tongo", description: "De legendarische Tongo. <a href=\"https://www.youtube.com/watch?v=z-R5qrznusY\">Bron</a>", code: "<tongo>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Pokémon Trainer battle", description: "Een trainer gevecht in Pokémon!", code: "<trainer>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "TROS", description: "<a href=\"https://www.youtube.com/watch?v=b8dXD8GOOm4\">De grootste familie van Nederland. </a>", code: "<tros>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Ultrahardheid", description: "Meet je ultrahardheid van 0% tot 10000%!", code: "<ultrahardheid>", category: ["Harde Hugo"], type: "Video-alert", year: 2024},
	{ name: "Verder nergens om", description: "Maar we minen diamonds! (WOE!)", code: "<verdernergensom>", category: ["Gaming", "Qastrol"], type: "Video-alert", year: 2024},
	{ name: "Maak jezelf VIP", description: "Maak jezelf VIP! Het aantal euro's dat je doneert is het aantal seconden dat je jezelf VIP maakt! Deze alert werkt alleen als je je eigen Twitch-naam gebruikt als donatienaam", code: "<vip>", category: ["Twitch"], type: "Interactieve alert", year: 2024},
	{ name: "Windows XP-melding", description: "Een Windows XP popup melding", code: "<windowsxp>", category: ["Computer"], type: "Audio-alert", year: 2024},
	{ name: "Eddy Wally: Wow", description: "Eddy Wally zegt \"wow\"", code: "<wow>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Zelda CDI: Tapijt", description: "Onderdeel van de intro van Link: The Faces of Evil voor de Philips CDI. Link vliegt op een tapijt", code: "<zeldatapijt>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "De Slimste Mens: 3-6-9", description: "De eerste ronde van De Slimste Mens!", code: "<369>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Altijd blijven vissen!", description: "Wat er ook gebeurt, altijd blijven vissen! De nieuwste zomerhit van DJ Qastrol. (1 seconde per euro)", code: "<altijdblijvenvissen>", category: ["Muziek", "Qastrol"], type: "Muziek-alert", year: 2024},
	{ name: "De dag die je niet vergeten mag", description: "Vergeet deze dag niet!", code: "<dedag>", category: ["Radio"], type: "Video-alert", year: 2024},
	{ name: "Desert Bus", description: "De beruchte videogame Desert Bus, waarin je 8 uur lang één recht stuk vooruit rijd, verschijnt op beeld. <a href=\"https://en.wikipedia.org/wiki/Penn_%26_Teller%27s_Smoke_and_Mirrors#Desert_Bus\">Desert Bus op Wikipedia</a>", code: "<desertbus>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Oh Yeah Donkey Kong", description: "Donkey Kong wordt geplet door een Game Boy D: <a href=\"https://www.youtube.com/watch?v=ckLV8Lo89tY\">Bron</a>", code: "<ohyeahmrkrabs>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "EK Voetbal 2024", description: "Throwback naar het EK van 2024 in Duitsland. Dit programma wordt mede mogelijk gemaakt door...", code: "<ek>", category: ["Sport", "Duitsland"], type: "Video-alert", year: 2024},
	{ name: "Vertel een mop", description: "Laat een mop vertellen op de stream! Gegarandeerd hillarisch 😂", code: "<mop>", category: "", type: "Video-alert", year: 2024},
	{ name: "Onthul je horoscoop", description: "Laat je horoscoop vertellen op stream! Deze horoscoop is 100% betrouwbaar", code: "<horoscoop>", category: "", type: "Video-alert", year: 2024},
	{ name: "Harde Partijen", description: "Dit programma wordt mede mogelijk gemaakt door harde partijen", code: "<hardepartijen>", category: ["Twitch", "TV", "Harde Hugo"], type: "Video-alert", year: 2024},
	{ name: "Another Brick in the Wall", description: "Glefly Brauly zingt Another Brick in the Wall (Part 2) van Pink Floyd! (1 seconde per euro) <a href=\"https://www.youtube.com/watch?v=moShzA7xGTQ\">Bron</a>", code: "<brickinthewall>", category: ["Muziek", "Internet"], type: "Video-alert", year: 2024},
	{ name: "HHGregg", description: "Christmas in July. <a href=\"https://www.youtube.com/watch?v=QJzt8L_i7_U\">Bron</a>", code: "<hhgregg>", category: ["Dagelijks leven", "Meme"], type: "Video-alert", year: 2024},
	{ name: "200 Vissen: intro", description: "Weet u het nog toen Qastrol 200 vissen vangde? De intro voor de 200 Vissen stream op twitch.tv/qastrol", code: "<visintro>", category: ["TV", "Intro"], type: "Video-alert", year: 2024},
	{ name: "Kapitein Koek", description: "De iconische Kapitein Koek reclame. MMMMMMMMMMMMMMM Lekker (de entrance van KanarieArie). <a href=\"https://www.youtube.com/watch?v=zvq6Mg8XN8A\">Bron</a>", code: "<kapiteinkoek>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Karpers, goudvissen", description: "Wat als karpers en goudvissen een YouTube kanaal hadden, en dit ze een intro video hadden?", code: "<karper>", category: ["Muziek", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "Kaulo Boszhard", description: "Kaulo Boszhard (Amsterdam, 26 juni 1969) is een Nederlands televisiepresentator, acteur, zanger, tekstschrijver en imitator.", code: "<kauloboszhard>", category: ["Meme", "TV"], type: "Video-alert", year: 2024},
	{ name: "KRO-NCRV", description: "Maak morgen mee, KRO-NCRV. <a href=\"https://www.youtube.com/watch?v=Roqx-JA_i1Q\">Bron</a>", code: "<kroncrv>", category: ["TV", "Qastrol"], type: "Video-alert", year: 2024},
	{ name: "Kat", description: "Een kat komt over het beeld (lief) (de entrance animatie van Lieveheersbabe)", code: "<kat>", category: ["Dieren"], type: "Video-alert", year: 2024},
	{ name: "Mark Rutte", description: "Mark Rutte breekt in de WWE Lijsttrekkersdebat?! Live uitgezonden op twitch.tv/qastrol en Nederland 1", code: "<markrutte>", category: ["TV", "Nederland"], type: "Video-alert", year: 2024},
	{ name: "Mario Kart is Kaulo Hard", description: "Mario Kart is Kaulo Hard", code: "<mariokartkaulohard>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Mario Kart, maar wat doet de rest dan?", description: "🤨🤨", code: "<watdoetderest>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Vsauce", description: "Hey Vsauce, Michael here", code: "<vsauce>", category: "", type: "Video-alert", year: 2024},
	{ name: "Jean Mineur Mediavision", description: "POV je kijkt reclame in de bioscoop", code: "<bioscoop>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Narwal van der Zee!", description: "Hij zwemt door de zee (de entrance video van NarwalvanderZee)", code: "<narwal>", category: "", type: "Video-alert", year: 2024},
	{ name: "€3,- in het Duits", description: "Hast du bitte 3 euro! <a href=\"https://www.youtube.com/watch?v=Is2jTgxNctI\">Bron</a>", code: "<3euro>", category: ["Duitsland"], type: "Video-alert", year: 2024},
	{ name: "WWE intro", description: "Now! Then! Forever! <a href=\"https://www.youtube.com/watch?v=551L0-4QMV0\">Bron</a>", code: "<wwe>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Mario Kart: Attention all Mario Kart gamers!", description: "Attention all Mario Kart gamers! Funky Kong needs your help! <a href=\"https://www.youtube.com/watch?v=qGz3KFdmaD0\">Bron</a>", code: "<attentiongamers>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Mario Kart: Blooper", description: "Een Blooper van Mario Kart spuit inkt over het scherm...", code: "<blooper>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Lego Island: Brick by Brick", description: "Brick by Brick van Lego Island wordt afgespeeld 😳", code: "<brickbybrick>", category: "", type: "Interactieve alert", year: 2024},
	{ name: "Mario Kart: Communication Error", description: "POV: je raakt gedisconnected in Mario Kart", code: "<communicationerror>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Dit is DVD reclame", description: "Dit is de geweldige DVD-technologie! <a href=\"https://www.youtube.com/watch?v=ZtlBCrP9ySo\">Bron</a>", code: "<dvd>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Fryslân", description: "Fryslân Boppe (de entrance animatie van DeJelman)", code: "<fryslan>", category: "", type: "Video-alert", year: 2024},
	{ name: "You got Noob-Power!", description: "Je krijgt Noob-Power in F-Zero X", code: "<fzeronoob>", category: "", type: "Video-alert", year: 2024},
	{ name: "GIGAVIS", description: "Het is de GIGACHAD van de vissen :O", code: "<gigavis>", category: ["Meme", "Dagelijks leven", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "Harde Koeksoep", description: "Een HARD die uit een koeksoep komt (de entrance animatie van Harde_Hugo)", code: "<hardekoeksoep>", category: "", type: "Video-alert", year: 2024},
	{ name: "Kruip in de huid van...", description: "Kruip in de huid van een bekend iemand...", code: "<kruipindehuid>", category: "", type: "Video-alert", year: 2024},
	{ name: "Nederland Kiest", description: "De intro van Nederland Kiest: Het WWE Lijsttrekkersdebat", code: "<nederlandkiest>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "De Noobbewaarder", description: "Ik kan het weten, ik ben er zelf eens door gered", code: "<noobbewaarder>", category: ["Muziek"], type: "Video-alert", year: 2024},
	{ name: "NPO 1: even geduld", description: "Even geduld...", code: "<npo1>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Pokémon Sun and Moon dans", description: "Een trainer in Pokémon Sun en Moon die een Z-move dans doet (de entrance animatie van Weslyv8)", code: "<pokemondans>", category: ["AI"], type: "Video-alert", year: 2024},
	{ name: "Rainbow Road lied", description: "It's called a road, it's called a Rainbow Road. It's a road that you go", code: "<rainbowroad>", category: ["Gaming", "Muziek", "Internet"], type: "Video-alert", year: 2024},
	{ name: "Reinhard Mey: Gute Nacht, Freunde", description: "Reinhard Mey wenst iedereen een goedenavond (1 euro per seconde). <a href=\"https://www.youtube.com/watch?v=6YnQc-AdNCI\">Bron</a>", code: "<reinhard>", category: ["Muziek"], type: "Video-alert", year: 2024},
	{ name: "Robbie Rotten", description: "Don't let your kids watch this! <a href=\"https://www.youtube.com/watch?v=MgffSUwTeKw\">Bron</a>", code: "<robbierotten>", category: ["TV", "Meme"], type: "Video-alert", year: 2024},
	{ name: "SIE!", description: "JAAAA 😁😁🗣️NU heb ik hem echt goed 🗣️🗣️SIEEEEEE 🗣️🗣️ huh😮‍💨 Waaaaauuuuw😲 die was echt ziek man😌", code: "<sie>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "NOS Radio Tourflits", description: "NOS Radio Tourflits, Tourflits, Tourflits. <a href=\"https://www.youtube.com/watch?v=Q2KX-SlzGv4\">Bron</a>", code: "<tourflits>", category: "", type: "Video-alert", year: 2024},
	{ name: "Turf", description: "Vissers uit Visblad TV lachen om turf 😂 <a href=\"https://www.youtube.com/watch?v=0pRjz8opWew\">Bron</a>", code: "<turf>", category: ["Dagelijks leven"], type: "Video-alert", year: 2024},
	{ name: "De Nieuwe Uri Geller", description: "<a href=\"https://www.youtube.com/watch?v=EjgLCJGFBfk\">Waarschuwing. De meeste optredens in deze show zijn levensgevaarlijk. Alleen goed getrainde, professionele mentalisten kunnen deze uitvoeren. Doe dit thuis nooit na!</a>", code: "<urigeller>", category: "", type: "Video-alert", year: 2024},
	{ name: "Donkey Kong: Very Hard", description: "Donkey Kong is HARD! <a href=\"https://www.youtube.com/watch?v=rWZ9xwK5gsk\">Bron</a>", code: "<veryhard>", category: "", type: "Video-alert", year: 2024},
	{ name: "Vis Moment", description: "VIS MOMENT", code: "<vismoment>", category: ["Gaming", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "200 Vissen: Professioneel", description: "Waarom deze vis er niet professioneel uitziet? (uit de 200 vissen stream)", code: "<visprofessioneel>", category: ["Gaming", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "Walter White speelt Mario Kart", description: " <a href=\"https://www.youtube.com/watch?v=1XSysnj2Bk0\">Bron</a>", code: "<walterwhite>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "We vissen vissen", description: "Verder nergens om, maar we vissen vissen", code: "<wevissenvissen>", category: ["Gaming", "Muziek"], type: "Video-alert", year: 2024},
	{ name: "LordWout RuneScape Schaap", description: "Een schaap in RuneScape (de entrance animatie van Lord Wout)", code: "<woutschaap>", category: ["Gaming", "Lord Wout", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "European Broadcasting Union", description: "De EBU, bekend van het songfestival", code: "<ebu>", category: ["Muziek", "TV"], type: "Video-alert", year: 2024},
	{ name: "Biem", description: "Star Fox 64, maar dan biem", code: "<biem>", category: ["Gaming", "Meme"], type: "Video-alert", year: 2024},
	{ name: "Halo 3 x Zelda CDI", description: "Gee, it sure is boring around here", code: "<haloboring>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "3D Hard", description: "HARD in 3D!", code: "<hard3d>", category: "", type: "Video-alert", year: 2024},
	{ name: "3D Hard met koeksoep", description: "HARD in 3D! (met een koeksoep)", code: "<hard3dkoeksoep>", category: "", type: "Video-alert", year: 2024},
	{ name: "Hardslide", description: "Hard over je beeldscherm", code: "<hardslide>", category: ["Twitch", "Harde Hugo"], type: "Video-alert", year: 2024},
	{ name: "Kikkertj", description: "De Mother 3 autokikker rijd over het beeldscherm", code: "<kikkertje>", category: ["Dieren"], type: "Video-alert", year: 2024},
	{ name: "Minecraft with Gadget", description: "Ik ben hier met mijn goede vriend Inspector Gadget", code: "<minecraftwithgadget>", category: ["Gaming", "Internet", "Meme"], type: "Video-alert", year: 2024},
	{ name: "Mark Rutte WWE hype", description: "Live reactie op Mark Rutte die in het WWE Lijsttrekkersdebat breekt", code: "<ruttehype>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Qastrol op de WC", description: "Hij zit te poepen", code: "<wc>", category: ["Qastrol"], type: "Video-alert", year: 2024},
	{ name: "De Westereen", description: "Wolkom yn 'e Westereen", code: "<westereen>", category: ["Internet", "Fryslân"], type: "Video-alert", year: 2024},
	{ name: "Zorgwekkend", description: "Een zorgwekkende video van iemand die <a href=\"https://www.youtube.com/watch?v=g3jCAyPai2Y\">Baka Mitai van Yakuza</a> zingt", code: "<zorgwekkend>", category: ["Muziek", "Gaming"], type: "Video-alert", year: 2024},
	{ name: "Donkey Kong: Uh Oh Sticky", description: "Je plakt vast in de honing", code: "<uhohsticky>", category: ["Gaming"], type: "Audio-alert", year: 2024},
	{ name: "200 vissen gevangen!", description: "Gefeliciteerd Qastrol, je hebt het gedaan! 200 vissen, zie ze daar nou staan", code: "<200vissen>", category: ["AI", "Qastrol"], type: "Muziek-alert", year: 2024},
	{ name: "Buurman & Buurman Kart", description: "De nieuwste racing game voor Nintendo Switch", code: "<buurmankart>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "DJ Yolotanker", description: "Het is de Samson en Gert mix van DJ Yolotanker (2 seconden per euro). <a href=\"https://www.youtube.com/watch?v=LKlRQGrUAo0\">Bron</a>", code: "<djyolotanker>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Hey", description: "Vsauce Michael, maar hij zegt alleen nog \"Hey\" in elke Vsauce aflevering", code: "<hey>", category: ["Meme", "Internet"], type: "Video-alert", year: 2024},
	{ name: "Mythbusters intro", description: "💩 <a href=\"https://www.youtube.com/watch?v=2stoFFvfEyg\">Bron</a>", code: "<mythbusters>", category: ["TV", "Intro"], type: "Video-alert", year: 2024},
	{ name: "YouTube 2007 tutorial", description: "Hallo!!!! Vergeet niet om de video 5 sterren te geven!!!!", code: "<tutorial>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "150 goals gescoord", description: "Gefeliciteerd Qastrol, je hebt het gedaan! 150 doelpunten zie de ballen daar staan!", code: "<150goals>", category: ["AI", "Qastrol"], type: "Muziek-alert", year: 2024},
	{ name: "7 GRAND FEEST", description: "GRAND FEEST?! FLEENTSTONES? GRAND FEEST? <a href=\"https://www.youtube.com/watch?v=nF-xdiL7Nr0\">Bron</a>", code: "<7grandfeest>", category: "", type: "Video-alert", year: 2024},
	{ name: "Black Mesa Announcement System", description: "Vervangt de TTS met de Black Mesa Announcement System van Half Life 1. Bekijk de volgende link voor alle ondersteunde woorden en zet deze in het donatiebericht (dit zijn de enige woorden die met deze alert werken): <a href=\"https://tz-dev.github.io/hl_text2speech/index.html\">https://tz-dev.github.io/hl_text2speech/index.html</a>. Let op: bij deze alert werken de reguliere TTS stemmen of sound effects <strong>niet</strong>", code: "<bmas>", category: ["AI"], type: "Video-alert", year: 2024},
	{ name: "Google Gemini AI", description: "De ChatGPT-concurrent van Google. Je donatiebericht is je bericht of vraag naar Gemini.", code: "<gemini>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Kattenfoto van Qastrol's kat", description: "Krijg een foto te zien van Qastrol's kat. Er zijn 100 mogelijkheden", code: "<kattenfoto>", category: ["Qastrol", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "Among Us Ejected", description: "Eject iets of iemand met je donatie. Voeg het gene dat je wil ejecten in je donatiebericht met \"\" (bijvoorbeeld \"koek en brokken\" eject koek en brokken)", code: "<amongus>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Wild Pokémon battle", description: "Een Pokémon gevecht in het wild!", code: "<wildpokemon>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Gerard Joling - Mexico", description: "Ik ben naar Mexico gekomen! De afspeelduur is afhankelijk van je donatiebedrag (1 euro = 1 seconde)", code: "<mexico>", category: ["Meme", "Muziek"], type: "Video-alert", year: 2024},
	{ name: "Poker", description: "Speel een soort van poker. Je pakt vijf willekeurige kaarten, die vervolgens een score krijgen. <a href=\"https://balatrogame.fandom.com/wiki/Poker_Hands\">De scoreberekening is hetzelfde als in Balatro: (chips + handwaarde) * mult</a>", code: "<poker>", category: ["Twitch"], type: "Interactieve alert", year: 2024},
	{ name: "Hot Potato", description: "Start één potje Hot Potato in de chat. De \"Hot Potato\" wordt gepasst naar een willekeurig iemand in de chat, en die heeft 15 seconden om de hot potato te passen aan iemand anders met !pass. Als dit 30 keer lukt, is het spel voorbij en moet Qastrol één euro doneren. <a href=\"https://tawmae.github.io/hot_potato.html\">Kijk hier voor meer informatie over Hot Potato</a>", code: "<hotpotato>", category: ["Twitch"], type: "Interactieve alert", year: 2024},
	{ name: "How", description: " <a href=\"https://www.youtube.com/watch?v=6M-NkQAo-3E\">van de \"What\" meme</a>", code: "<how>", category: "", type: "Video-alert", year: 2024},
	{ name: "Kruidvat schepsnoep", description: "Welke kruidvat schepsnoep ben jij? Kom er achter met deze alert. 34 mogelijkheden", code: "<kruidvat>", category: "", type: "Video-alert", year: 2024},
	{ name: "QAS GAS IS Z", description: "Wanneer je meedoet aan een <a href = \"https://twitch.tv/muntjesman\">Muntjesman Nintendo 64 Toernooi</a>, maar ineens vergeet hoe je gas geeft in de game <a href = \"https://en.wikipedia.org/wiki/Extreme-G\">Extreme-G</a>", code: "<qasgasisz>", category: ["Qastrol", "Gaming"], type: "Video-alert", year: 2024},
	{ name: "Play it Forward: Gameboy intro", description: "Wanneer je je Gameboy opstart (Play it Forward-stijl)", code: "<gameboy>", category: ["Gaming", "Intro"], type: "Video-alert", year: 2024},
	{ name: "Kingler zegt \"koekie\"", description: "<a href=\"https://www.youtube.com/watch?v=J1Y2CJMWxwA\">Kingler van Pokémon Puzzle League</a> zegt \"koekie\"", code: "<koekie>", category: ["Gaming"], type: "Video-alert"},
	{ name: "Unregistered Hypercam 2", description: "Wanneer je een YouTube Tutorial kijkt in 2005 met Unregistered Hypercam 2 en <a href=\"https://www.youtube.com/watch?v=0Xa3lfd0ukk\">Dreamscape van 009 Sound System</a>", code: "<hypercam>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Peggle: Extreme Fever", description: "<a href=\"https://www.youtube.com/watch?v=wXB_5A8UbWI\">Je voltooit een Peggle level en Ode to Joy begint te spelen</a>", code: "<peggle>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Don eren", description: "!don eer, ik eer Don", code: "<doneren>", category: "", type: "Video-alert", year: 2024},
	{ name: "Zelda CDI: This is illegal you know", description: "<a href=\"https://www.youtube.com/watch?v=kr_Xw3sTgRk\">Eén van de meest illegale cutscenes in de CDI Zelda spellen</a>", code: "<illegal>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Zelda CDI: Somebody that Morshu used to know", description: "<a href=\"https://www.youtube.com/watch?v=MNyxXxyavVw\">Morshu zingt \"Somebody I used to know\"</a>", code: "<somebody>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Zelda CDI: You Reposted In The Wrong Shop", description: "<a href=\"https://www.youtube.com/watch?v=m20cGdohWic\">You reposted in the wrong neighbourhood</a>", code: "<reposted>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Play it Forward Nederland 1", description: "Een Play it Forward-logo in de stijl van het jaren '90 Nederland 1 logo, met een sound effect", code: "<playitforward>", category: ["TV", "Intro", "Nederland"], type: "Video-alert", year: 2024},
	{ name: "1, 2, Koeksoep", description: "Hugo is heel hard", code: "<12koeksoep>", category: ["Harde Hugo", "AI", "Gaming"], type: "Video-alert", year: 2024},
	{ name: "Stel je vraag aan AI Qastrol", description: "AI Qastrol beantwoord al je vragen. Let op: dit vervangt de text to speech", code: "<aiqastrol>", category: ["Qastrol"], type: "Video-alert", year: 2024},
	{ name: "Nintendo Alarmo - HARDe wekker", description: "Zo wordt je HARD wakker", code: "<alarmo>", category: ["Gaming", "Harde Hugo"], type: "Video-alert", year: 2024},
	{ name: "Banaantje", description: "Hugo zegt 'banaantje'", code: "<banaantje>", category: "", type: "Video-alert", year: 2024},
	{ name: "BBC Sounds archief", description: "Speel een willekeurig geluid van het BBC Sounds archief, een archief met duizenden geluiden van oude BBC hoorspellen. Kan van alles zijn", code: "<bbcsound>", category: ["Radio"], type: "Audio-alert", year: 2024},
	{ name: "Bobba-filter", description: "Gaat Qastrol, Lord Wout of Harde Hugo een heftig woord zeggen? Filter het eruit met het Bobba-filter", code: "<bobba>", category: ["Qastrol"], type: "Video-alert", year: 2024},
	{ name: "Kerstknallers - Centstorm", description: "Een KerstKnallers Centstorm, maar dan bij elk bedrag", code: "<centstorm>", category: ["KerstKnallers"], type: "Video-alert", year: 2024},
	{ name: "Clear Chat", description: "Wil je de chat leeg maken? Dat kan met deze alert!", code: "<clearchat>", category: "", type: "Video-alert", year: 2024},
	{ name: "DGHHPS", description: "De DGHHPS stream is binnenkort te zien bij twitch.tv/harde_hugo!", code: "<dghhps>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Followmode", description: "Ben je klaar met non-followers die chatten? Met deze alert kan je followmode tijdelijk aanzetten. Je donatiebedrag is het aantal seconden dat followmode actief is", code: "<followmode>", category: ["Twitch"], type: "Interactieve alert", year: 2024},
	{ name: "Gamerwolde", description: "Hier wonen alleen gamers. <a href=\"https://maps.app.goo.gl/qXf4gykkbomkTbASA\">Gamerwolde op Google Maps</a>", code: "<gamerwolde>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Harde Hugo genieter", description: "Gemiddelde Lekker spelen fan vs Gemiddelde Harde Hugo genieter", code: "<genieter>", category: "", type: "Video-alert", year: 2024},
	{ name: "Stuur een GIPHY-gifje", description: "Stuur een gifje van GIPHY. De tekst die je tussen aanhalingstekens doet, is je zoekopdracht naar een gifje (bijv. \"Christmas\" zoekt de eerste .gif op met Christmas). Let op: een gifje kan mogelijk niet beschikbaar zijn", code: "<gif>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Griddy bij KerstKnallers 2023", description: "De griddy van KerstKnallers 2023 (speelt 1 seconde af per gedoneerde euro)", code: "<griddy>", category: ["Muziek", "KerstKnallers"], type: "Interactieve alert", year: ""},
	{ name: "Halo Theme", description: "Speel de Halo-themesong af onder je TTS-bericht", code: "<halotheme>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Keep it hardcore", description: "De titelsong van Wrestling Empire van MDickie. Come on do it! Come on do it! <a href=\"https://www.youtube.com/watch?v=U4eCMaf_UpI\">Bron</a>", code: "<hardcore>", category: ["Muziek", "Gaming"], type: "Video-alert", year: 2024},
	{ name: "Harde Hugo moment", description: "Voor de harde gaming momenten van Harde Hugo", code: "<hardehugo>", category: ["Harde Hugo", "Intro"], type: "Video-alert", year: 2024},
	{ name: "Halo: Hard stuff", description: "De aankondiger van Halo heeft het over hard stuff", code: "<hardstuff>", category: ["AI", "Gaming"], type: "Audio-alert", year: 2024},
	{ name: "Harry Piekema was het!", description: "sus", code: "<harrypiekema>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Discord: Hugo disconnected", description: "Harde Hugo wordt gedisconnect uit de Discord call", code: "<hugodisconnect>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Hugo je bent stoer", description: "Met elke kill stijgt de hardheid omhoog. Twitch chat roept 'Hugo je bent stoer'", code: "<hugojebentstoer>", category: ["AI", "Harde Hugo"], type: "Interactieve alert", year: 2024},
	{ name: "Harde Hugo: WWE karakter", description: "Harde Hugo is een worstelaar in WWE", code: "<hugowwe>", category: ["Sport", "Harde Hugo"], type: "Video-alert", year: 2024},
	{ name: "I am Steve", description: "Hij is Steve (van A Minecraft Movie). <a href=\"https://www.youtube.com/watch?v=ykEjEcjPXEE\">Bron</a>", code: "<iamsteve>", category: ["Gaming", "Film"], type: "Video-alert", year: 2024},
	{ name: "Karbonkel", description: "Karbonkel laat Mik schrikken 😱 (van Ik Mik Loreland)", code: "<karbonkel>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Kruip in de huid van... KerstKnallers!", description: "Welke KerstKnallers streamer ben jij?", code: "<kersthuid>", category: ["KerstKnallers"], type: "Video-alert", year: 2024},
	{ name: "KerstKnallers: donatie", description: "Een gewone KerstKnallers donatie", code: "<kerstknallers>", category: ["KerstKnallers"], type: "Video-alert", year: 2024},
	{ name: "Kerstonweb.be", description: "Een speciale Kerstknallers versie van een Belgische belastingsaangiftereclame", code: "<kerstonweb>", category: ["België", "KerstKnallers"], type: "Video-alert", year: 2024},
	{ name: "Knolpower!", description: "Het is tijd voor wat knolpower!", code: "<knolpower>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Harde koprol", description: "Harde Hugo doet een koprol", code: "<koprol>", category: ["Harde Hugo"], type: "Video-alert", year: 2024},
	{ name: "Labor Day song", description: "Het traditionele labor day lied. <a href=\"https://youtu.be/HmeKhjkTOn8?feature=shared&t=1098\">Bron</a>", code: "<laborday>", category: ["Muziek"], type: "Video-alert", year: 2024},
	{ name: "Lord Wout Runescape schaap", description: "Een schaap in RuneScape", code: "<lordwout>", category: ["Gaming", "Lord Wout", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "Alert voor moviequiz", description: "Beschrijving voor moviequiz", code: "<moviequiz>", category: ["Film"], type: "Video-alert", year: 2024},
	{ name: "Geen alert", description: "Wil je helemaal geen alert? Kies dan de <niks> alert", code: "<niks>", category: [], type: "Video-alert", year: 2024},
	{ name: "NPO 1 Tune", description: "Speel de NPO 1 tune onder je donatiebericht", code: "<npo1tune>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "NPO 2 Tune", description: "Speel de NPO 2 tune onder je donatiebericht", code: "<npo2tune>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Ollama AI", description: "Stel je vraag aan Ollama AI", code: "<ollama>", category: ["AI"], type: "Interactieve alert", year: 2024},
	{ name: "Omegahardheid", description: "Meet je omegahardheid! Nog HARDer dan ultrahardheid, met hardheid tot 1000000% hardheid!", code: "<omegahardheid>", category: ["Harde Hugo"], type: "Interactieve alert", year: 2024},
	{ name: "Quantumhardheid", description: "De allerhardste hardheid ooit, met gevaarlijk hoge waardes tot wel 100000000% hardheid!", code: "<quantumhardheid>", category: ["Harde Hugo"], type: "Interactieve alert", year: 2024},
	{ name: "¡Qué pasa, NENG!", description: "Een vervloekte Spaanse videogame. <a href=\"https://www.youtube.com/watch?v=sIdKvagWf9I\">Bron</a>", code: "<quepasaneng>", category: ["Gaming", "TV"], type: "Video-alert", year: 2024},
	{ name: "Willekeurige alert", description: "Speel een willekeurige alert af", code: "<random>", category: [], type: "Video-alert", year: 2024},
	{ name: "Samson & Gert intro", description: "Speel het Samson & Gert intronummer onder je TTS-bericht af", code: "<samsonengert>", category: ["TV", "Intro"], type: "Video-alert", year: 2024},
	{ name: "Schnappi Scary Skeleton", description: "Ich bin Schnappi das Krokodil <a href=\"https://www.youtube.com/watch?v=P3ynj6w2tII\">Bron</a>", code: "<skeleton>", category: ["Internet", "Duitsland"], type: "Video-alert", year: 2024},
	{ name: "Harde Hugo is een supermarkt", description: "Harde Hugo is een supermarkt", code: "<supermarkt>", category: ["Harde Hugo", "Dagelijks leven"], type: "Video-alert", year: 2024},
	{ name: "Harde Thanos", description: "Harde Hugo speelt Thanos", code: "<thanos>", category: ["Harde Hugo", "Film"], type: "Video-alert", year: 2024},
	{ name: "Louis van Gaal", description: "Een beruchte Engelse uitspraak van Louis van Gaal wordt afgespeeld. Dit kunnen 22 uitspraken zijn", code: "<vangaal>", category: ["Sport"], type: "Video-alert", year: 2024},
	{ name: "Alert voor videogamequiz", description: "Beschrijving voor videogamequiz", code: "<videogamequiz>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Het is (vissen)feest", description: "Het is feest van Mona, maar dan met een vis!", code: "<visfeest>", category: ["Sport", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "VIS GET!", description: "Je hebt een vis gevangen (van de 200 vissen livestream)", code: "<visgevangen>", category: ["Qastrol", "Sport", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "Kruip in de vissenhuid van", description: "Wordt een vis! (van de 200 vissen livestream)", code: "<vissenhuid>", category: ["AI", "Muziek", "Dieren"], type: "Muziek-alert", year: 2024},
	{ name: "De vlag gaat eruit", description: "yaaaaaaaay", code: "<vlag>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Voetbal Moment", description: "Een soort YouTuber-intro maar dan voor voetbal", code: "<voetbalmoment>", category: ["Sport"], type: "Video-alert", year: 2024},
	{ name: "VTube: Gollum", description: "Qastrol heeft nu een Vtube-camera van Gollum van The Lord of The Rings", code: "<vtubegollum>", category: ["Vtube"], type: "Interactieve alert", year: 2024},
	{ name: "VTube: Hond", description: "Qastrol heeft nu een Vtube-camera van een hond", code: "<vtubehond>", category: ["Vtube", "Dieren"], type: "Interactieve alert", year: 2024},
	{ name: "VTube: Jerma985", description: "Qastrol heeft nu een Vtube-camera van Jerma985", code: "<vtubejerma>", category: ["Vtube"], type: "Interactieve alert", year: 2024},
	{ name: "VTube: Kat", description: "Qastrol heeft nu een VTube-camera van een kat", code: "<vtubekat>", category: ["Vtube", "Dieren"], type: "Interactieve alert", year: 2024},
	{ name: "VTube: Pichu", description: "Qastrol krijgt een VTube-camera van Pichu van de Pokémon-serie", code: "<vtubepichu>", category: ["Vtube"], type: "Interactieve alert", year: 2024},
	{ name: "VTube: Rotom", description: "Qastrol heeft nu een VTube-camera van Rotom van Pokémon", code: "<vtuberotom>", category: ["Vtube"], type: "Interactieve alert", year: 2024},
	{ name: "Vtube: Soyjack", description: "Qastrol heeft nu een VTube-camera van Soyjack, de meme van de wijzende persoon", code: "<vtubesoyjack>", category: ["Vtube"], type: "Interactieve alert", year: 2024},
	{ name: "VTube: Uitzetten", description: "Als de VTube camera aanstaat, kan je deze zo weer uit zetten", code: "<vtubeuit>", category: ["Vtube"], type: "Interactieve alert", year: 2024},
	{ name: "VTube: Vis", description: "Qastrol wordt de eerste vis Vtuber", code: "<vtubevis>", category: ["Vtube", "Dieren"], type: "Interactieve alert", year: 2024},
	{ name: "VTube: Yee", description: "Qastrol heeft nu een VTube-camera van een dino", code: "<vtubeyee>", category: ["Vtube"], type: "Interactieve alert", year: 2024},
	{ name: "Verder nergens om maar we scoren goals", description: "WOE", code: "<wescorengoals>", category: ["Sport", "Muziek"], type: "Muziek-alert", year: 2024},
	{ name: "Windows 95 melding", description: "Een pop-up melding in Windows 95", code: "<windows95>", category: ["Computer"], type: "Audio-alert", year: 2024},
	{ name: "Discord: Wout disconnect", description: "Lord Wout wordt gedisconnect uit de Discord call", code: "<woutdisconnect>", category: ["Lord Wout"], type: "Interactieve alert", year: 2024},
	{ name: "Zelda CDI in het Nederlands", description: "Ooh jongen, ik verveel me te pletter. (de intro van Link: The Face of Evil in het Nederlands) <a href=\"https://www.youtube.com/watch?v=M2tskI83V6g\">Bron</a>", code: "<zeldanl>", category: ["Gaming", "Nederland"], type: "Video-alert", year: 2024},
	{ name: "Zin in maandag", description: "Voor als je uitkijkt naar maandag, de start van een nieuwe werkweek. <a href=\"https://www.youtube.com/watch?v=X728AwdIQT4\">Bron</a>", code: "<zininmaandag>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "5 euro", description: "Op je muil gauw!", code: "<5euro>", category: ["Meme", "TV"], type: "Video-alert", year: 2024},
	{ name: "The Elder Scrolls Oblivion: Adoring Fan", description: "Hij is je grootste fan", code: "<adoringfan>", category: ["Gaming"], type: "Video-alert", year: ""},
	{ name: "Attention, all Mario Kart gamers", description: "Funky Kong needs your help", code: "<attention>", category: ["Gaming", "Meme"], type: "Video-alert", year: 2024},
	{ name: "Baksteene kom nou terug", description: "Ik was fout. Ik ben alleen en heb het koud", code: "<baksteene>", category: ["Twitch"], type: "Video-alert", },
	{ name: "VPRO Boeken", description: "Het boekenprogramma van de VPRO", code: "<boek>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Boek Movie Maker intro", description: "YouTube 2007 stijl", code: "<boek2>", category: ["Computer", "Qastrol"], type: "Video-alert", year: 2024},
	{ name: "BOS!", description: "Wanneer je heel bos bent (boos)", code: "<bos>", category: ["Meme"], type: "Video-alert", year: 2025},
	{ name: "Hotel Mario: Bowser's Brief", description: "Dear Pesky Plumbers", code: "<bowserbrief>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Browser's cassle", description: "Mario wz in a jail seel in browsers cassle and he was looked and couldn't get ouuuuuuuuuuuu!", code: "<browser>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "GTA San Andreas: Here we go again", description: "Ah shit, here we go again", code: "<cj>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Qastrol community", description: "😳", code: "<community>", category: ["Meme", "Qastrol"], type: "Video-alert", year: 2024},
	{ name: "Fryslân compilatie", description: "Doe de Fryslân Bop! (de entrance van DeJelman)", code: "<fryslan>", category: ["Fryslân"], type: "Video-alert", year: 2024},
	{ name: "Domino Day intro", description: "Domino Day, het jaarlijkse evenement met dominostenen", code: "<dominoday>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Don eren", description: "Ik wil graag Don eren", code: "<doneer>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Eddy Wally: Wow", description: "Wow", code: "<eddywally>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Among Us: Emergency Meeting", description: "Wanneer je in Among Us iedereen bij elkaar roept", code: "<emergencymeeting>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "It's free real estate", description: "It's free real estate", code: "<estate>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Peggle: Ultra Extreme Fever", description: "Wanneer je alle pegs hebt geraakt in Peggle", code: "<fever>", category: ["Gaming"], type: "Video-alert", year: ""},
	{ name: "Geenklier Brommergang", description: "De GeenKlier brommergang komt aan in SpongeBob", code: "<geenklier>", category: ["TV", "Twitch"], type: "Video-alert", year: ""},
	{ name: "Heb geen neus", description: "Ik heb helemaal geen neus", code: "<geenneus>", category: ["Internet", "Muziek"], type: "Video-alert", year: ""},
	{ name: "Hard 3D", description: "HAAAAAAAAAAAAAARD!", code: "<hard>", category: ["Twitch", "Harde Hugo"], type: "Video-alert", year: 2024},
	{ name: "Harde koeksoep", description: "HARD! komt uit een koeksoep (de entrance van Harde Hugo)", code: "<hardkoeksoep>", category: ["Twitch", "Harde Hugo"], type: "Video-alert", year: 2024},
	{ name: "Hello!", description: "Een krabje zegt hallo", code: "<hello>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Hie", description: "Een voetballer stelt zich voor", code: "<hie>", category: ["Sport"], type: "Video-alert", year: 2024},
	{ name: "Hier, een euro!", description: "AAAAA!", code: "<hiereeneuro>", category: ["TV", "België"], type: "Video-alert", year: 2024},
	{ name: "Man Bijt Hond: Beter Bed", description: "Eén van de bumpers van Man Bijt Hond, waarbij de hond op een Beter Bed springt", code: "<hondbed>", category: ["TV"], type: "Video-alert", year: ""},
	{ name: "Man Bijt Hond: Lopen", description: "Eén van de bumpers van Man Bijt Hond, waarbij de hond loopt", code: "<hondlopen>", category: ["TV"], type: "Video-alert", year: ""},
	{ name: "Man Bijt Hond: Wijzen", description: "Eén van de bumpers van Man Bijt Hond, waarbij de hond wijst", code: "<hondwijs>", category: ["TV"], type: "Video-alert", year: ""},
	{ name: "Humberto Tantoe", description: "Humberto Tantoe (Paramaribo, 26 oktober 1965) is een Nederlands-Surinaamse radio- en televisiepresentator, sportjournalist en schrijver. ", code: "<humbertotantoe>", category: ["TV", "Meme"], type: "Video-alert", year: ""},
	{ name: "Hotel Mario: Instructions", description: "If you need instructions on how to get through the hotel", code: "<instructionbook>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Jean Mineur intro", description: "Als je reclame kijkt in de bioscoop", code: "<jeanmineur>", category: ["Film"], type: "Video-alert", year: 2024},
	{ name: "Karper Goudvis gaming intro", description: "Wanneer vissen een eigen YouTube kanaal zouden hebben", code: "<karpergoudvis>", category: ["Internet", "Sport", "Dieren"], type: "Video-alert", year: 2024},
	{ name: "Katje", description: "Een katje komt over het scherm heen (de entrance van lieveheersbabe)", code: "<katje>", category: ["Dieren"], type: "Video-alert", year: 2024},
	{ name: "Kaulo Perron", description: "Een NS Station met straattaal", code: "<kauloperron>", category: ["Dagelijks leven", "Meme"], type: "Video-alert", year: 2024},
	{ name: "Minecraft Movie: Kippenrijder", description: "KIPPENRIJDER!", code: "<kippenrijder>", category: ["Gaming", "Film"], type: "Video-alert", year: ""},
	{ name: "Labour Day lied", description: "Labour Day, ooh labour day", code: "<labourday>", category: ["Meme"], type: "Video-alert", year: 2024},
	{ name: "Zelda CDI: It is written", description: "It is written: only Link can defeat Ganon", code: "<linkwritten>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Mario Kart World x Daft Punk", description: "De nieuwste hit van Daft Punk", code: "<mariokartworld>", category: ["Gaming", "Muziek"], type: "Video-alert", year: ""},
	{ name: "GTA San Andreas: Mission Passed", description: "+ RESPECT", code: "<missionpassed>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Zelda CDi: Morshu", description: "Lamp oil? Ropes? Bombs? You want it? It's yours my friend as long as you have enough rubees", code: "<morshu>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Zelda CDi: You reposted in the wrong shop", description: "Een nummer van Morshu", code: "<morshushop>", category: ["Meme", "Gaming"], type: "Video-alert", year: ""},
	{ name: "Netflix Intro", description: "Een Qastrol Netflix intro", code: "<netflix>", category: ["TV", "Qastrol"], type: "Video-alert", year: 2024},
	{ name: "Nintendo Direct", description: "De intro van een Nintendo Direct", code: "<nintendodirect>", category: ["Internet"], type: "Video-alert", year: ""},
	{ name: "NOS Journaal intro", description: "Wanneer je het 8 uur journaal kijkt", code: "<nos>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Reitse: Ja, pannenkoek!", description: "Reitse Spanninga wordt boos", code: "<pannenkoek>", category: ["TV", "Fryslân"], type: "Video-alert", year: ""},
	{ name: "Peggle 3", description: "Peggle 3 wordt aangekondigd bij E3", code: "<peggle3>", category: ["Gaming"], type: "Video-alert", year: ""},
	{ name: "Qastrol Direct", description: "De Qastrol Direct, de live uitzending met aankondigingen", code: "<qastroldirect>", category: ["Internet", "Qastrol"], type: "Video-alert", year: ""},
	{ name: "Among Us: Reported", description: "Wanneer je in Among Us iets rapporteert", code: "<reported>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Mark Rutte hype", description: "Live reactie op Mark Rutte die inbreekt in het WWE Lijsttrekkersdebat", code: "<rutte>", category: ["Sport"], type: "Video-alert", year: 2024},
	{ name: "Shrek Horror", description: "Een extreem enge mobiele game, met Shrek die danst op het titelscherm", code: "<shrekhorror>", category: ["Gaming", "Film"], type: "Video-alert", year: ""},
	{ name: "Rapper Sjors", description: "videoboodschappen.nl", code: "<sjors>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Qastrol sniper intro", description: "Epische gamer intro", code: "<snipe>", category: ["Qastrol", "Intro"], type: "Video-alert", year: 2024},
	{ name: "UP NEXT: SpongeBob Squarepants", description: "Hierna is SpongeBob Squarepants te zien", code: "<spongebob>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Minecraft Movie x Star Wars", description: "I am Steve, maar dan Star Wars", code: "<stevestarwars>", category: ["Gaming", "Film"], type: "Video-alert", year: ""},
	{ name: "The Elder Scrolls IV Oblivion: STOP!", description: "STOP! You violated the law. Pay the court a fine or serve your sentence. Your stolen goods are now forfeit.", code: "<stop>", category: ["Gaming"], type: "Video-alert", year: ""},
	{ name: "Subscribe & Like", description: "& Comment", code: "<subscribelike>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "Tellsell: HARD!", description: "Deze livestream wordt mede mogelijk gemaakt door HARD!", code: "<tellsell>", category: ["Harde Hugo"], type: "Video-alert", year: 2024},
	{ name: "Hard Time: Trembling Fingers", description: "De Trembling Fingers dans van Hard Time 3", code: "<tremblingfingers>", category: ["Gaming"], type: "Video-alert", year: ""},
	{ name: "Zelda CDi: Somebody that I used to know", description: "Morshu van Zelda CDi zingt Somebody that I used to know", code: "<usedtoknow>", category: ["Meme", "Gaming"], type: "Video-alert", year: ""},
	{ name: "Vrolijk Palen", description: "Gordon wenst iedereen een vrolijk palen", code: "<vrolijkpalen>", category: ["AI", "Meme"], type: "Video-alert", year: ""},
	{ name: "De Nieuwe Uri Geller: Waarschuwing", description: "Waarschuwing. De meeste optredens uit deze show zijn levensgevaarlijk. Alleen goed getrainde, professionele mentalisten kunnen deze uitvoeren. Doe dit thuis nooit na!", code: "<waarschuwing>", category: ["TV"], type: "Video-alert", year: 2024},
	{ name: "Super Mario Bros 3: WALTA!", description: "WALTA! WALTA! WALTA!", code: "<walta>", category: ["Gaming", "Twitch"], type: "Video-alert", year: ""},
	{ name: "Warner Bros intro", description: "Afkomstig uit de Minecraft Movie", code: "<warnerbros>", category: ["Film"], type: "Video-alert", year: 2024},
	{ name: "Welkom dat je kijkt", description: "Welkom welkom welkom dat je kijkt", code: "<welkomdatjekijkt>", category: ["Internet"], type: "Video-alert", year: ""},
	{ name: "Verder nergens om, maar we minen diamonds", description: "WOE!", code: "<weminendiamonds>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Pokémon Sun/Moon dans", description: "Het karakter van Pokémon Sun en Moon doet een Z-move dans", code: "<weslyv8>", category: ["Gaming"], type: "Video-alert", year: 2024},
	{ name: "Lord Wout moment", description: "Voor de gaming momenten van Lord Wout", code: "<woutmoment>", category: ["Gaming", "Lord Wout"], type: "Video-alert", year: 2024},
	{ name: "Happy Easter Xbox", description: "Beschrijving voor xbox", code: "<xbox>", category: ["Gaming", "Internet"], type: "Video-alert", year: ""},
	{ name: "YouTube 2007 Tutorial", description: "Welkom bij mijn tutorial!", code: "<youtube>", category: ["Internet"], type: "Video-alert", year: 2024},
	{ name: "De provincie Zwolle", description: "De 🗺️ provincie 🏘️ Zwolle 🇳🇱 staat 🧍 nummer 🔢 één 🥇 met 🤝 technologie ⚙️ van 🧪 teleportatie 🧙‍♂️ Zo 😱 hun 👥 zijn 🫶 wel 👍 gek 🤪 man 👨 Ja 🙂 ik 🙋 wist 🧠 dat 🧐 niet ❌ man 👨 nee 🙅 dat 🗣️ we 👯‍♂️ zo 🫣 dichtbij 🤏 zijn 😮 dat 🗣️ provincie 🏘️ Zwolle 🇳🇱 zo 💫 toereikend 👐 is ✅ en ☝️ dat 🗣️ ze 👩‍🔬 zo 💫 ver 📏 al ⏩ geavanceerd 📈 zijn 🤖 met ⚙️ de 🧭 technologie ⚙️ broer 👨 is 💪 andere 🔀 level 🎚️ ja ✅ is 💪 andere 🔀 level 🎚️", code: "<zwolle>", category: ["Internet"], type: "", year: ""},
	{ name: "Mario Odyssey: Moon Get!", description: "Donatietekst zoals wanneer je in Mario Odyssey een maan krijgt", code: "<odyssey>", category: ["Gaming"], type: "Video-alert", year: ""}

];