// Alerts table data. Each entry: { name, description, code }
const alertsTable = [
	{ name: "Noob-Power!", description: "Noob-Power! Dit is de standaard alert, als er geen alert in het donatiebericht staat", code: "<noobpower>" },
	{ name: "Voeg een URL toe", description: "Voeg een URL toe in je donatiebericht. Werkt in principe met elke link (als het laad), maar werkt het beste met Twitch of YouTube-links (YouTube-links met timestamps starten vanaf de ingestelde tijd). De afspeelduur is afhankelijk van het donatiebedrag (3 seconden + 1 seconde voor elke euro)", code: "<url>" },
	{ name: "€2,-", description: "Papa, mag ik alsjeblieft 2 euro voor de arme man die op straat staat te schreeuwen. <a href=\"https://www.youtube.com/watch?v=Fy-SqB2FiSQ\">Bron</a>", code: "<2euro>" },
	{ name: "Zelda CDI: Boring", description: "Gee, it sure is boring around here (van de intro van Link: The Faces of Evil voor de Philips CDI)", code: "<boring>" },
	{ name: "BREIN intro", description: "De inhoud van deze drager is beschermd door wetten van Intellectuele Eigendom waaronder de Auteurswet, de Wet op de Naburige Rechten, de Databankwet en de Beneluxmerkenwet.", code: "<brein>" },
	{ name: "Buurman & Buurman", description: "Speel de intro van Buurman & Buurman. Ajeto!", code: "<buurman>" },
	{ name: "Look at all this damage!", description: "<a href=\"https://www.youtube.com/watch?v=4B-JdfG6efI\">And we're going to repair it using flex shot</a>", code: "<damage>" },
	{ name: "Edd, Ed n Eddy: Deurbel", description: "Iemand belt aan bij de deurbel van Edd...", code: "<edd>" },
	{ name: "Hier, een euro!", description: "<a href=\"https://www.youtube.com/watch?v=HiLKVdNJt_o\">AAAAAAAAAAAAAA!</a>", code: "<euro>" },
	{ name: "Het is feest!", description: "<a href=\"https://www.youtube.com/watch?v=pchWYdcN6zA\">Joepie!</a>", code: "<feest>" },
	{ name: "Speel een geluidseffect!", description: "Speel een willekeurig geluidseffect af van 138 mogelijkheden. Kan van alles zijn", code: "<geluidseffect>" },
	{ name: "GIGACHAD", description: "<a href=\"https://www.youtube.com/watch?v=FuJwXZpqzB8\">GIGACHAD</a>", code: "<gigachad>" },
	{ name: "Habbo Hotel-melding", description: "Je donatiemelding als een Habbo-chatbericht. Wil iemand meubi?", code: "<habbo>" },
	{ name: "Hardheid", description: "Meet je hardheid, van 0% tot 100%!", code: "<hardheid>" },
	{ name: "Will Smith: That's Hot", description: "That's hot. Will Smith komt langs", code: "<hot>" },
	{ name: "Hotel Mario: dinner", description: "Deel 1 van de Hotel Mario intro. Nice of the Princess to invite us over for dinner ey Luigi", code: "<hotelmario>" },
	{ name: "Hugo Duro", description: "Hugo Duro, de Spaanse voetballer die ook wel bekend staat als Harde Hugo. <a href=\"https://nl.wikipedia.org/wiki/Hugo_Duro\">Hugo Duro op Wikipedia</a>", code: "<hugoduro>" },
	{ name: "Hotel Mario: Instructions", description: "Deel 3 van de Hotel Mario intro. If you need instructions on how to get through the hotel, check out the enclosed instruction book", code: "<instructions>" },
	{ name: "Zelda CDI: I won!", description: "Een cutscene van Link: The Faces of Evil waarin Link heeft gewonnen. <a href=\"https://www.youtube.com/watch?v=kahoWJOsjoc\">Bron</a>", code: "<iwon>" },
	{ name: "Like & Subscribe", description: "Een YouTuber-outro. Vergeet niet te liken en te subscriben en te commenten", code: "<likesubscribe>" },
	{ name: "Speel een potje Lingo", description: "Speel een potje Lingo met Lucille en JP! Gebruik !lingo in de chat om een woord te raden. Iedereen kan meedoen met Lingo! Let op: moeilijke woorden kunnen voorkomen.", code: "<lingo>" },
	{ name: "Ed, Edd n Eddy: Many Doors", description: "Many Doors (van Ed, Edd n Eddy). <a href=\"https://www.youtube.com/watch?v=Rq338WwBUpw\">Bron</a>", code: "<manydoors>" },
	{ name: "Windows Media Player", description: "Start Windows Media Player op. De video die afgespeeld wordt is één van 82 mogelijke video's. De subalert op twitch.tv/qastrol", code: "<mediaplayer>" },
	{ name: "Minecraft: graven", description: "Steve van Minecraft komt het scherm in graven", code: "<minecraft>" },
	{ name: "Reitse: Mosterd", description: "<a href=\"https://www.youtube.com/watch?v=V2IOzbM5n-Y\">Mosterd</a>", code: "<mosterd>" },
	{ name: "Michael Rosen: Noice", description: "<a href=\"https://www.youtube.com/watch?v=lg5WKsVnEA4\">Noice!</a>", code: "<noice>" },
	{ name: "Hotel Mario: Pesky Plumbers", description: "Deel 2 van de intro van Hotel Mario. Dear Pesky Plumbers, the koopalings and I have taken over the Mushroom Kingdom", code: "<peskyplumbers>" },
	{ name: "Vang een Pokémon", description: "Vang één Pokémon uit de eerste vijf generaties van Pokémon! (649 mogelijkheden)", code: "<pokemon>" },
	{ name: "Waarom dit paneel er niet professioneel uitziet?", description: "Omdat net als met mijn wachtscherm en pauze schermpjes en offline scherm ik het leuk vind zelf te tekenen omdat het juist grappig is als het zo lelijk is.", code: "<professioneel>" },
	{ name: "Qastrol moment", description: "Voor als Qastrol een ziek gaming moment heeft", code: "<qastrol>" },
	{ name: "Qastrol's microfoon", description: "Zet Qastrol's microfoon aan als die uit staat, of uit als die aan staat", code: "<qastrolmic>" },
	{ name: "Lekker Ite Mei Reitse", description: "Reitse Spanninga, de Fryske sjef. <a href=\"https://www.youtube.com/watch?v=5JUc8oMhm_k\">Bron</a>", code: "<reitse>" },
	{ name: "The Rock", description: "Hij is The Rock en hij is sus. <a href=\"https://www.youtube.com/watch?v=SnM_JxgBsFk\">Bron</a>", code: "<rock>" },
	{ name: "Zelda CDI Shopkeeper: Ropes, Bombs", description: "De shopkeeper van Link: The Faces of Evil. Ropes, Bombs, you want it? It's your's my friend as long as you have enough rubies. <a href=\"https://www.youtube.com/watch?v=J8XxuW-Orww\">Bron</a>", code: "<ropesbombs>" },
	{ name: "Samson is a DJ", description: "Samson is een DJ (1 seconde per euro). <a href=\"https://www.youtube.com/watch?v=gqW9J64kRXY\">Bron</a>", code: "<samsondj>" },
	{ name: "Smurf 6", description: "Het is smurf 6 (1 seconde per euro). <a href=\"https://www.youtube.com/watch?v=HfUYMG4yWpk\">Bron</a>", code: "<smurf6>" },
	{ name: "Zelda CDI Shopkeeper: Sorry Link", description: "De shopkeeper van Link: The Faces of Evil. Come back when you're a little richer! <a href=\"https://www.youtube.com/watch?v=J8XxuW-Orww\">Bron</a>", code: "<sorrylink>" },
	{ name: "Spongebob: Sports Channel", description: "Spongebob kijkt TV. <a href=\"https://www.youtube.com/watch?v=hPpTGwzeKVc\">Bron</a>", code: "<sportschannel>" },
	{ name: "taxonweb.be", description: "Vlaamse belastingaangifte. <a href=\"https://www.youtube.com/watch?v=KM7rDjaDcwg\">Trouwens, waarom doe je het niet direct? Anders vergeet je het nog.</a>", code: "<taxonweb>" },
	{ name: "The Room: I did not hit her!", description: "Tommy Wiseau begroet Mark. <a href=\"https://www.youtube.com/watch?v=6xdKTeqQcpo\">Bron</a>", code: "<theroom>" },
	{ name: "Geef iemand een timeout", description: "Wil je iemand uit de chat timeouten? Dat kan met een donatie! Mention een Twitch gebruiker in de donatie met @ (bijv. \"@Qastrol\"), je aantal euro's is de duur van de timeout die deze persoon krijgt", code: "<timeout>" },
	{ name: "Tongo", description: "De legendarische Tongo. <a href=\"https://www.youtube.com/watch?v=z-R5qrznusY\">Bron</a>", code: "<tongo>" },
	{ name: "Pokémon Trainer battle", description: "Een trainer gevecht in Pokémon!", code: "<trainer>" },
	{ name: "TROS", description: "<a href=\"https://www.youtube.com/watch?v=b8dXD8GOOm4\">De grootste familie van Nederland. </a>", code: "<tros>" },
	{ name: "Ultrahardheid", description: "Meet je ultrahardheid van 0% tot 10000%!", code: "<ultrahardheid>" },
	{ name: "Verder nergens om", description: "Maar we minen diamonds! (WOE!)", code: "<verdernergensom>" },
	{ name: "Maak jezelf VIP", description: "Maak jezelf VIP! Het aantal euro's dat je doneert is het aantal seconden dat je jezelf VIP maakt! Deze alert werkt alleen als je je eigen Twitch-naam gebruikt als donatienaam", code: "<vip>" },
	{ name: "Windows XP-melding", description: "Een Windows XP popup melding", code: "<windowsxp>" },
	{ name: "Eddy Wally: Wow", description: "Eddy Wally zegt \"wow\"", code: "<wow>" },
	{ name: "Zelda CDI: Tapijt", description: "Onderdeel van de intro van Link: The Faces of Evil voor de Philips CDI. Link vliegt op een tapijt", code: "<zeldatapijt>" },
	{ name: "De Slimste Mens: 3-6-9", description: "De eerste ronde van De Slimste Mens!", code: "<369>" },
	{ name: "Altijd blijven vissen!", description: "Wat er ook gebeurt, altijd blijven vissen! De nieuwste zomerhit van DJ Qastrol. (1 seconde per euro)", code: "<altijdblijvenvissen>" },
	{ name: "De dag die je niet vergeten mag", description: "Vergeet deze dag niet!", code: "<dedag>" },
	{ name: "Desert Bus", description: "De beruchte videogame Desert Bus, waarin je 8 uur lang één recht stuk vooruit rijd, verschijnt op beeld. <a href=\"https://en.wikipedia.org/wiki/Penn_%26_Teller%27s_Smoke_and_Mirrors#Desert_Bus\">Desert Bus op Wikipedia</a>", code: "<desertbus>" },
	{ name: "Oh Yeah Donkey Kong", description: "Donkey Kong wordt geplet door een Game Boy D: <a href=\"https://www.youtube.com/watch?v=ckLV8Lo89tY\">Bron</a>", code: "<ohyeahmrkrabs>" },
	{ name: "EK Voetbal 2024", description: "Throwback naar het EK van 2024 in Duitsland. Dit programma wordt mede mogelijk gemaakt door...", code: "<ek>" },
	{ name: "Vertel een mop", description: "Laat een mop vertellen op de stream! Gegarandeerd hillarisch 😂", code: "<mop>" },
	{ name: "Onthul je horoscoop", description: "Laat je horoscoop vertellen op stream! Deze horoscoop is 100% betrouwbaar", code: "<horoscoop>" },
	{ name: "Harde Partijen", description: "Dit programma wordt mede mogelijk gemaakt door harde partijen", code: "<hardepartijen>" },
	{ name: "Another Brick in the Wall", description: "Glefly Brauly zingt Another Brick in the Wall (Part 2) van Pink Floyd! (1 seconde per euro) <a href=\"https://www.youtube.com/watch?v=moShzA7xGTQ\">Bron</a>", code: "<brickinthewall>" },
	{ name: "HHGregg", description: "Christmas in July. <a href=\"https://www.youtube.com/watch?v=QJzt8L_i7_U\">Bron</a>", code: "<hhgregg>" },
	{ name: "200 Vissen: intro", description: "Weet u het nog toen Qastrol 200 vissen vangde? De intro voor de 200 Vissen stream op twitch.tv/qastrol", code: "<visintro>" },
	{ name: "Kapitein Koek", description: "De iconische Kapitein Koek reclame. MMMMMMMMMMMMMMM Lekker (de entrance van KanarieArie). <a href=\"https://www.youtube.com/watch?v=zvq6Mg8XN8A\">Bron</a>", code: "<kapiteinkoek>" },
	{ name: "Karpers, goudvissen", description: "Wat als karpers en goudvissen een YouTube kanaal hadden, en dit ze een intro video hadden?", code: "<karper>" },
	{ name: "Kaulo Boszhard", description: "Kaulo Boszhard (Amsterdam, 26 juni 1969) is een Nederlands televisiepresentator, acteur, zanger, tekstschrijver en imitator.", code: "<kauloboszhard>" },
	{ name: "KRO-NCRV", description: "Maak morgen mee, KRO-NCRV. <a href=\"https://www.youtube.com/watch?v=Roqx-JA_i1Q\">Bron</a>", code: "<kroncrv>" },
	{ name: "Kat", description: "Een kat komt over het beeld (lief) (de entrance animatie van Lieveheersbabe)", code: "<kat>" },
	{ name: "Mark Rutte", description: "Mark Rutte breekt in de WWE Lijsttrekkersdebat?! Live uitgezonden op twitch.tv/qastrol en Nederland 1", code: "<markrutte>" },
	{ name: "Mario Kart is Kaulo Hard", description: "Mario Kart is Kaulo Hard", code: "<mariokartkaulohard>" },
	{ name: "Mario Kart, maar wat doet de rest dan?", description: "🤨🤨", code: "<watdoetderest>" },
	{ name: "Vsauce", description: "Hey Vsauce, Michael here", code: "<vsauce>" },
	{ name: "Jean Mineur Mediavision", description: "POV je kijkt reclame in de bioscoop", code: "<bioscoop>" },
	{ name: "Narwal van der Zee!", description: "Hij zwemt door de zee (de entrance video van NarwalvanderZee)", code: "<narwal>" },
	{ name: "€3,- in het Duits", description: "Hast du bitte 3 euro! <a href=\"https://www.youtube.com/watch?v=Is2jTgxNctI\">Bron</a>", code: "<3euro>" },
	{ name: "WWE intro", description: "Now! Then! Forever! <a href=\"https://www.youtube.com/watch?v=551L0-4QMV0\">Bron</a>", code: "<wwe>" },
	{ name: "Mario Kart: Attention all Mario Kart gamers!", description: "Attention all Mario Kart gamers! Funky Kong needs your help! <a href=\"https://www.youtube.com/watch?v=qGz3KFdmaD0\">Bron</a>", code: "<attentiongamers>" },
	{ name: "Mario Kart: Blooper", description: "Een Blooper van Mario Kart spuit inkt over het scherm...", code: "<blooper>" },
	{ name: "Lego Island: Brick by Brick", description: "Brick by Brick van Lego Island wordt afgespeeld 😳", code: "<brickbybrick>" },
	{ name: "Mario Kart: Communication Error", description: "POV: je raakt gedisconnected in Mario Kart", code: "<communicationerror>" },
	{ name: "Dit is DVD reclame", description: "Dit is de geweldige DVD-technologie! <a href=\"https://www.youtube.com/watch?v=ZtlBCrP9ySo\">Bron</a>", code: "<dvd>" },
	{ name: "Fryslân", description: "Fryslân Boppe (de entrance animatie van DeJelman)", code: "<fryslan>" },
	{ name: "You got Noob-Power!", description: "Je krijgt Noob-Power in F-Zero X", code: "<fzeronoob>" },
	{ name: "GIGAVIS", description: "Het is de GIGACHAD van de vissen :O", code: "<gigavis>" },
	{ name: "Harde Koeksoep", description: "Een HARD die uit een koeksoep komt (de entrance animatie van Harde_Hugo)", code: "<hardekoeksoep>" },
	{ name: "Kruip in de huid van...", description: "Kruip in de huid van een bekend iemand...", code: "<kruipindehuid>" },
	{ name: "Nederland Kiest", description: "De intro van Nederland Kiest: Het WWE Lijsttrekkersdebat", code: "<nederlandkiest>" },
	{ name: "De Noobbewaarder", description: "Ik kan het weten, ik ben er zelf eens door gered", code: "<noobbewaarder>" },
	{ name: "NPO 1: even geduld", description: "Even geduld...", code: "<npo1>" },
	{ name: "Pokémon Sun and Moon dans", description: "Een trainer in Pokémon Sun en Moon die een Z-move dans doet (de entrance animatie van Weslyv8)", code: "<pokemondans>" },
	{ name: "Rainbow Road lied", description: "It's called a road, it's called a Rainbow Road. It's a road that you go", code: "<rainbowroad>" },
	{ name: "Reinhard Mey: Gute Nacht, Freunde", description: "Reinhard Mey wenst iedereen een goedenavond (1 euro per seconde). <a href=\"https://www.youtube.com/watch?v=6YnQc-AdNCI\">Bron</a>", code: "<reinhard>" },
	{ name: "Robbie Rotten", description: "Don't let your kids watch this! <a href=\"https://www.youtube.com/watch?v=MgffSUwTeKw\">Bron</a>", code: "<robbierotten>" },
	{ name: "SIE!", description: "JAAAA 😁😁🗣️NU heb ik hem echt goed 🗣️🗣️SIEEEEEE 🗣️🗣️ huh😮‍💨 Waaaaauuuuw😲 die was echt ziek man😌", code: "<sie>" },
	{ name: "NOS Radio Tourflits", description: "NOS Radio Tourflits, Tourflits, Tourflits. <a href=\"https://www.youtube.com/watch?v=Q2KX-SlzGv4\">Bron</a>", code: "<tourflits>" },
	{ name: "Turf", description: "Vissers uit Visblad TV lachen om turf 😂 <a href=\"https://www.youtube.com/watch?v=0pRjz8opWew\">Bron</a>", code: "<turf>" },
	{ name: "De Nieuwe Uri Geller", description: "<a href=\"https://www.youtube.com/watch?v=EjgLCJGFBfk\">Waarschuwing. De meeste optredens in deze show zijn levensgevaarlijk. Alleen goed getrainde, professionele mentalisten kunnen deze uitvoeren. Doe dit thuis nooit na!</a>", code: "<urigeller>" },
	{ name: "Donkey Kong: Very Hard", description: "Donkey Kong is HARD! <a href=\"https://www.youtube.com/watch?v=rWZ9xwK5gsk\">Bron</a>", code: "<veryhard>" },
	{ name: "Vis Moment", description: "VIS MOMENT", code: "<vismoment>" },
	{ name: "200 Vissen: Professioneel", description: "Waarom deze vis er niet professioneel uitziet? (uit de 200 vissen stream)", code: "<visprofessioneel>" },
	{ name: "Walter White speelt Mario Kart", description: " <a href=\"https://www.youtube.com/watch?v=1XSysnj2Bk0\">Bron</a>", code: "<walterwhite>" },
	{ name: "We vissen vissen", description: "Verder nergens om, maar we vissen vissen", code: "<wevissenvissen>" },
	{ name: "LordWout RuneScape Schaap", description: "Een schaap in RuneScape (de entrance animatie van Lord Wout)", code: "<woutschaap>" },
	{ name: "European Broadcasting Union", description: "De EBU, bekend van het songfestival", code: "<ebu>" },
	{ name: "Biem", description: "Star Fox 64, maar dan biem", code: "<biem>" },
	{ name: "Halo 3 x Zelda CDI", description: "Gee, it sure is boring around here", code: "<haloboring>" },
	{ name: "3D Hard", description: "HARD in 3D!", code: "<hard3d>" },
	{ name: "3D Hard met koeksoep", description: "HARD in 3D! (met een koeksoep)", code: "<hard3dkoeksoep>" },
	{ name: "Hardslide", description: "Hard over je beeldscherm", code: "<hardslide>" },
	{ name: "Kikkertj", description: "De Mother 3 autokikker rijd over het beeldscherm", code: "<kikkertje>" },
	{ name: "Minecraft with Gadget", description: "Ik ben hier met mijn goede vriend Inspector Gadget", code: "<minecraftwithgadget>" },
	{ name: "Mark Rutte WWE hype", description: "Live reactie op Mark Rutte die in het WWE Lijsttrekkersdebat breekt", code: "<ruttehype>" },
	{ name: "Qastrol op de WC", description: "Hij zit te poepen", code: "<wc>" },
	{ name: "De Westereen", description: "Wolkom yn 'e Westereen", code: "<westereen>" },
	{ name: "Zorgwekkend", description: "Een zorgwekkende video van iemand die <a href=\"https://www.youtube.com/watch?v=g3jCAyPai2Y\">Baka Mitai van Yakuza</a> zingt", code: "<zorgwekkend>" },
	{ name: "Donkey Kong: Uh Oh Sticky", description: "Je plakt vast in de honing", code: "<uhohsticky>" },
	{ name: "200 vissen gevangen!", description: "Gefeliciteerd Qastrol, je hebt het gedaan! 200 vissen, zie ze daar nou staan", code: "<200vissen>" },
	{ name: "Buurman & Buurman Kart", description: "De nieuwste racing game voor Nintendo Switch", code: "<buurmankart>" },
	{ name: "DJ Yolotanker", description: "Het is de Samson en Gert mix van DJ Yolotanker (2 seconden per euro). <a href=\"https://www.youtube.com/watch?v=LKlRQGrUAo0\">Bron</a>", code: "<djyolotanker>" },
	{ name: "Hey", description: "Vsauce Michael, maar hij zegt alleen nog \"Hey\" in elke Vsauce aflevering", code: "<hey>" },
	{ name: "Mythbusters intro", description: "💩 <a href=\"https://www.youtube.com/watch?v=2stoFFvfEyg\">Bron</a>", code: "<mythbusters>" },
	{ name: "YouTube 2007 tutorial", description: "Hallo!!!! Vergeet niet om de video 5 sterren te geven!!!!", code: "<tutorial>" },
	{ name: "150 goals gescoord", description: "Gefeliciteerd Qastrol, je hebt het gedaan! 150 doelpunten zie de ballen daar staan!", code: "<150goals>" },
	{ name: "7 GRAND FEEST", description: "GRAND FEEST?! FLEENTSTONES? GRAND FEEST? <a href=\"https://www.youtube.com/watch?v=nF-xdiL7Nr0\">Bron</a>", code: "<7grandfeest>" },
	{ name: "Black Mesa Announcement System", description: "Vervangt de TTS met de Black Mesa Announcement System van Half Life 1. Bekijk de volgende link voor alle ondersteunde woorden en zet deze in het donatiebericht (dit zijn de enige woorden die met deze alert werken): <a href=\"https://tz-dev.github.io/hl_text2speech/index.html\">https://tz-dev.github.io/hl_text2speech/index.html</a>. Let op: bij deze alert werken de reguliere TTS stemmen of sound effects <strong>niet</strong>", code: "<bmas>" },
	{ name: "Google Gemini AI", description: "De ChatGPT-concurrent van Google. Je donatiebericht is je bericht of vraag naar Gemini.", code: "<gemini>" },
	{ name: "Kattenfoto van Qastrol's kat", description: "Krijg een foto te zien van Qastrol's kat. Er zijn 100 mogelijkheden", code: "<kattenfoto>" },
	{ name: "Among Us Ejected", description: "Eject iets of iemand met je donatie. Voeg het gene dat je wil ejecten in je donatiebericht met \"\" (bijvoorbeeld \"koek en brokken\" eject koek en brokken)", code: "<amongus>" },
	{ name: "Wild Pokémon battle", description: "Een Pokémon gevecht in het wild!", code: "<wildpokemon>" },
	{ name: "Gerard Joling - Mexico", description: "Ik ben naar Mexico gekomen! De afspeelduur is afhankelijk van je donatiebedrag (1 euro = 1 seconde)", code: "<mexico>" },
	{ name: "Poker", description: "Speel een soort van poker. Je pakt vijf willekeurige kaarten, die vervolgens een score krijgen. <a href=\"https://balatrogame.fandom.com/wiki/Poker_Hands\">De scoreberekening is hetzelfde als in Balatro: (chips + handwaarde) * mult</a>", code: "<poker>" },
	{ name: "Hot Potato", description: "Start één potje Hot Potato in de chat. De \"Hot Potato\" wordt gepasst naar een willekeurig iemand in de chat, en die heeft 15 seconden om de hot potato te passen aan iemand anders met !pass. Als dit 30 keer lukt, is het spel voorbij en moet Qastrol één euro doneren. <a href=\"https://tawmae.github.io/hot_potato.html\">Kijk hier voor meer informatie over Hot Potato</a>", code: "<hotpotato>" },
	{ name: "How", description: " <a href=\"https://www.youtube.com/watch?v=6M-NkQAo-3E\">van de \"What\" meme</a>", code: "<how>" },
	{ name: "Kruidvat schepsnoep", description: "Welke kruidvat schepsnoep ben jij? Kom er achter met deze alert. 34 mogelijkheden", code: "<kruidvat>" },
	{ name: "QAS GAS IS Z", description: "Wanneer je meedoet aan een <a href = \"https://twitch.tv/muntjesman\">Muntjesman Nintendo 64 Toernooi</a>, maar ineens vergeet hoe je gas geeft in de game <a href = \"https://en.wikipedia.org/wiki/Extreme-G\">Extreme-G</a>", code: "<qasgasisz>" },
	{ name: "Play it Forward: Gameboy intro", description: "Wanneer je je Gameboy opstart (Play it Forward-stijl)", code: "<gameboy>" },
	{ name: "Kingler zegt \"koekie\"", description: "<a href=\"https://www.youtube.com/watch?v=J1Y2CJMWxwA\">Kingler van Pokémon Puzzle League</a> zegt \"koekie\"", code: "<koekie>" },
	{ name: "Unregistered Hypercam 2", description: "Wanneer je een YouTube Tutorial kijkt in 2005 met Unregistered Hypercam 2 en <a href=\"https://www.youtube.com/watch?v=0Xa3lfd0ukk\">Dreamscape van 009 Sound System</a>", code: "<hypercam>" },
	{ name: "Peggle: Extreme Fever", description: "<a href=\"https://www.youtube.com/watch?v=wXB_5A8UbWI\">Je voltooit een Peggle level en Ode to Joy begint te spelen</a>", code: "<peggle>" },
	{ name: "Don eren", description: "!don eer, ik eer Don", code: "<doneren>" },
	{ name: "Zelda CDI: This is illegal you know", description: "<a href=\"https://www.youtube.com/watch?v=kr_Xw3sTgRk\">Eén van de meest illegale cutscenes in de CDI Zelda spellen</a>", code: "<illegal>" },
	{ name: "Zelda CDI: Somebody that Morshu used to know", description: "<a href=\"https://www.youtube.com/watch?v=MNyxXxyavVw\">Morshu zingt \"Somebody I used to know\"</a>", code: "<somebody>" },
	{ name: "Zelda CDI: You Reposted In The Wrong Shop", description: "<a href=\"https://www.youtube.com/watch?v=m20cGdohWic\">You reposted in the wrong neighbourhood</a>", code: "<reposted>" },
	{ name: "Play it Forward Nederland 1", description: "Een Play it Forward-logo in de stijl van het jaren '90 Nederland 1 logo, met een sound effect", code: "<playitforward>" },
	{ name: "Alert voor 12koeksoep", description: "Beschrijving voor 12koeksoep", code: "<12koeksoep>" },
	{ name: "Alert voor aiqastrol", description: "Beschrijving voor aiqastrol", code: "<aiqastrol>" },
	{ name: "Alert voor alarmo", description: "Beschrijving voor alarmo", code: "<alarmo>" },
	{ name: "Alert voor banaantje", description: "Beschrijving voor banaantje", code: "<banaantje>" },
	{ name: "Alert voor bbcsound", description: "Beschrijving voor bbcsound", code: "<bbcsound>" },
	{ name: "Alert voor bobba", description: "Beschrijving voor bobba", code: "<bobba>" },
	{ name: "Alert voor centstorm", description: "Beschrijving voor centstorm", code: "<centstorm>" },
	{ name: "Alert voor clearchat", description: "Beschrijving voor clearchat", code: "<clearchat>" },
	{ name: "Alert voor dghhps", description: "Beschrijving voor dghhps", code: "<dghhps>" },
	{ name: "Alert voor followmode", description: "Beschrijving voor followmode", code: "<followmode>" },
	{ name: "Alert voor gamerwolde", description: "Beschrijving voor gamerwolde", code: "<gamerwolde>" },
	{ name: "Alert voor genieter", description: "Beschrijving voor genieter", code: "<genieter>" },
	{ name: "Alert voor gif", description: "Beschrijving voor gif", code: "<gif>" },
	{ name: "Alert voor griddy", description: "Beschrijving voor griddy", code: "<griddy>" },
	{ name: "Alert voor halotheme", description: "Beschrijving voor halotheme", code: "<halotheme>" },
	{ name: "Alert voor hardcore", description: "Beschrijving voor hardcore", code: "<hardcore>" },
	{ name: "Alert voor hardehugo", description: "Beschrijving voor hardehugo", code: "<hardehugo>" },
	{ name: "Alert voor hardeintro", description: "Beschrijving voor hardeintro", code: "<hardeintro>" },
	{ name: "Alert voor hardstuff", description: "Beschrijving voor hardstuff", code: "<hardstuff>" },
	{ name: "Alert voor harrypiekema", description: "Beschrijving voor harrypiekema", code: "<harrypiekema>" },
	{ name: "Alert voor hugodisconnect", description: "Beschrijving voor hugodisconnect", code: "<hugodisconnect>" },
	{ name: "Alert voor hugojebentstoer", description: "Beschrijving voor hugojebentstoer", code: "<hugojebentstoer>" },
	{ name: "Alert voor hugowwe", description: "Beschrijving voor hugowwe", code: "<hugowwe>" },
	{ name: "Alert voor iamsteve", description: "Beschrijving voor iamsteve", code: "<iamsteve>" },
	{ name: "Alert voor karbonkel", description: "Beschrijving voor karbonkel", code: "<karbonkel>" },
	{ name: "Alert voor kersthuid", description: "Beschrijving voor kersthuid", code: "<kersthuid>" },
	{ name: "Alert voor kerstknallers", description: "Beschrijving voor kerstknallers", code: "<kerstknallers>" },
	{ name: "Alert voor kerstonweb", description: "Beschrijving voor kerstonweb", code: "<kerstonweb>" },
	{ name: "Alert voor knolpower", description: "Beschrijving voor knolpower", code: "<knolpower>" },
	{ name: "Alert voor koprol", description: "Beschrijving voor koprol", code: "<koprol>" },
	{ name: "Alert voor laborday", description: "Beschrijving voor laborday", code: "<laborday>" },
	{ name: "Alert voor lordwout", description: "Beschrijving voor lordwout", code: "<lordwout>" },
	{ name: "Alert voor moviequiz", description: "Beschrijving voor moviequiz", code: "<moviequiz>" },
	{ name: "Alert voor niks", description: "Beschrijving voor niks", code: "<niks>" },
	{ name: "Alert voor npo1tune", description: "Beschrijving voor npo1tune", code: "<npo1tune>" },
	{ name: "Alert voor npo2tune", description: "Beschrijving voor npo2tune", code: "<npo2tune>" },
	{ name: "Alert voor ollama", description: "Beschrijving voor ollama", code: "<ollama>" },
	{ name: "Alert voor omegahardheid", description: "Beschrijving voor omegahardheid", code: "<omegahardheid>" },
	{ name: "Alert voor quantumhardheid", description: "Beschrijving voor quantumhardheid", code: "<quantumhardheid>" },
	{ name: "Alert voor quepasaneng", description: "Beschrijving voor quepasaneng", code: "<quepasaneng>" },
	{ name: "Alert voor random", description: "Beschrijving voor random", code: "<random>" },
	{ name: "Alert voor samsonengert", description: "Beschrijving voor samsonengert", code: "<samsonengert>" },
	{ name: "Alert voor skeleton", description: "Beschrijving voor skeleton", code: "<skeleton>" },
	{ name: "Alert voor supermarkt", description: "Beschrijving voor supermarkt", code: "<supermarkt>" },
	{ name: "Alert voor thanos", description: "Beschrijving voor thanos", code: "<thanos>" },
	{ name: "Alert voor vangaal", description: "Beschrijving voor vangaal", code: "<vangaal>" },
	{ name: "Alert voor videogamequiz", description: "Beschrijving voor videogamequiz", code: "<videogamequiz>" },
	{ name: "Alert voor visfeest", description: "Beschrijving voor visfeest", code: "<visfeest>" },
	{ name: "Alert voor visgevangen", description: "Beschrijving voor visgevangen", code: "<visgevangen>" },
	{ name: "Alert voor vissenhuid", description: "Beschrijving voor vissenhuid", code: "<vissenhuid>" },
	{ name: "Alert voor vlag", description: "Beschrijving voor vlag", code: "<vlag>" },
	{ name: "Alert voor voetbalmoment", description: "Beschrijving voor voetbalmoment", code: "<voetbalmoment>" },
	{ name: "Alert voor vtubegollum", description: "Beschrijving voor vtubegollum", code: "<vtubegollum>" },
	{ name: "Alert voor vtubehond", description: "Beschrijving voor vtubehond", code: "<vtubehond>" },
	{ name: "Alert voor vtubejerma", description: "Beschrijving voor vtubejerma", code: "<vtubejerma>" },
	{ name: "Alert voor vtubekat", description: "Beschrijving voor vtubekat", code: "<vtubekat>" },
	{ name: "Alert voor vtubepichu", description: "Beschrijving voor vtubepichu", code: "<vtubepichu>" },
	{ name: "Alert voor vtuberotom", description: "Beschrijving voor vtuberotom", code: "<vtuberotom>" },
	{ name: "Alert voor vtubesoyjack", description: "Beschrijving voor vtubesoyjack", code: "<vtubesoyjack>" },
	{ name: "Alert voor vtubeuit", description: "Beschrijving voor vtubeuit", code: "<vtubeuit>" },
	{ name: "Alert voor vtubevis", description: "Beschrijving voor vtubevis", code: "<vtubevis>" },
	{ name: "Alert voor vtubeyee", description: "Beschrijving voor vtubeyee", code: "<vtubeyee>" },
	{ name: "Alert voor wescorengoals", description: "Beschrijving voor wescorengoals", code: "<wescorengoals>" },
	{ name: "Alert voor windows95", description: "Beschrijving voor windows95", code: "<windows95>" },
	{ name: "Alert voor woutdisconnect", description: "Beschrijving voor woutdisconnect", code: "<woutdisconnect>" },
	{ name: "Alert voor zeldanl", description: "Beschrijving voor zeldanl", code: "<zeldanl>" },
	{ name: "Alert voor zininmaandag", description: "Beschrijving voor zininmaandag", code: "<zininmaandag>" }];

// Note: the page expects a global `alertsTable` variable. Keep the name global to match existing script usage.