/* Auto-generated by tools/generate_alerts_links.py */
const alertsLinks = {
  "2euro": [
    "alerts/2euro.mp4"
  ],
  "3euro": [
    "alerts/3euro.mp4"
  ],
  "5euro": [
    "alerts/5euro.mp4"
  ],
  "adoringfan": [
    "alerts/adoringfan.webm"
  ],
  "attention": [
    "alerts/attention.webm"
  ],
  "baksteene": [
    "alerts/baksteene.webm"
  ],
  "biem": [
    "alerts/biem.mp4"
  ],
  "boek": [
    "alerts/boek.mp4"
  ],
  "boek2": [
    "alerts/boek2.mp4"
  ],
  "boring": [
    "alerts/boring.mp4",
    "alerts/boring.webm"
  ],
  "bowserbrief": [
    "alerts/bowserbrief.webm"
  ],
  "brein": [
    "alerts/brein.mp4"
  ],
  "brickinthewall": [
    "alerts/brickinthewall.mp4"
  ],
  "browser": [
    "alerts/browser.mp4"
  ],
  "buurman": [
    "alerts/buurman.webm"
  ],
  "buurmankart": [
    "alerts/buurmankart.mp4"
  ],
  "cj": [
    "alerts/cj.webm"
  ],
  "community": [
    "alerts/community.webm"
  ],
  "dominoday": [
    "alerts/dominoday.mp4"
  ],
  "doneer": [
    "alerts/doneer.mp4"
  ],
  "dvd": [
    "alerts/dvd.mp4"
  ],
  "eddywally": [
    "alerts/eddywally.webm"
  ],
  "emergencymeeting": [
    "alerts/emergencymeeting.webm"
  ],
  "estate": [
    "alerts/estate.mp4"
  ],
  "fever": [
    "alerts/fever.webm"
  ],
  "gamerwolde": [
    "alerts/gamerwolde.webm"
  ],
  "geenneus": [
    "alerts/geenneus.webm"
  ],
  "gigachad": [
    "alerts/gigachad.webm"
  ],
  "gigavis": [
    "alerts/gigavis.webm"
  ],
  "hard": [
    "alerts/hard.webm"
  ],
  "hardehugocommunity2": [
    "alerts/Harde Hugo Community 2.mp4"
  ],
  "hardehugomoment": [
    "alerts/hardehugomoment.mp4"
  ],
  "hardepartijen": [
    "alerts/hardepartijen.mp4"
  ],
  "hardslide": [
    "alerts/hardslide.webm"
  ],
  "hello": [
    "alerts/hello.mp4"
  ],
  "hey": [
    "alerts/hey.mp4"
  ],
  "hie": [
    "alerts/hie.mp4"
  ],
  "hiereeneuro": [
    "alerts/hiereeneuro.mp4"
  ],
  "hondbeterbed": [
    "alerts/hondbeterbed.mp4"
  ],
  "hondlopen": [
    "alerts/hondlopen.mp4"
  ],
  "hotelmario": [
    "alerts/hotelmario.webm"
  ],
  "hugoduro": [
    "alerts/hugoduro.mp4"
  ],
  "humbertotantoe": [
    "alerts/humbertotantoe.webm"
  ],
  "humbertotantoeleeg": [
    "alerts/HumbertotantoeLeeg.webm"
  ],
  "iamsteve": [
    "alerts/iamsteve.mp4"
  ],
  "illegal": [
    "alerts/illegal.webm"
  ],
  "instructionbook": [
    "alerts/instructionbook.webm"
  ],
  "iwon": [
    "alerts/iwon.webm"
  ],
  "jeanmineur": [
    "alerts/jeanmineur.mp4"
  ],
  "karbonkel": [
    "alerts/karbonkel.mp4"
  ],
  "karpergoudvis": [
    "alerts/karpergoudvis.webm"
  ],
  "kauloboszhard": [
    "alerts/kauloboszhard.webm"
  ],
  "kauloperron": [
    "alerts/kauloperron.mp4"
  ],
  "kippenrijder": [
    "alerts/kippenrijder.webm"
  ],
  "koekie": [
    "alerts/koekie.mp4"
  ],
  "kroncrv": [
    "alerts/kroncrv.mp4"
  ],
  "labourday": [
    "alerts/labourday.mp4"
  ],
  "linkwritten": [
    "alerts/linkwritten.webm"
  ],
  "manbijthond": [
    "alerts/manbijthond.mp4"
  ],
  "mariokartkaulohard": [
    "alerts/mariokartkaulohard.webm"
  ],
  "mariokartworld": [
    "alerts/mariokartworld.mp4"
  ],
  "mexico": [
    "alerts/mexico.mp4"
  ],
  "minecraft": [
    "alerts/minecraft.webm"
  ],
  "minecraftwithgadget": [
    "alerts/minecraftwithgadget.mp4"
  ],
  "missionpassed": [
    "alerts/missionpassed.webm"
  ],
  "morshu": [
    "alerts/morshu.webm"
  ],
  "morshushop": [
    "alerts/morshushop.mp4"
  ],
  "mosterd": [
    "alerts/mosterd.mp4"
  ],
  "mythbusters": [
    "alerts/mythbusters.mp4"
  ],
  "netflix": [
    "alerts/netflix.webm"
  ],
  "nintendodirect": [
    "alerts/nintendodirect.webm"
  ],
  "noice": [
    "alerts/noice.webm"
  ],
  "noobbewaarder": [
    "alerts/noobbewaarder.mp4"
  ],
  "nos": [
    "alerts/nos.mp4"
  ],
  "pannenkoek": [
    "alerts/pannenkoek.mp4"
  ],
  "professioneel": [
    "alerts/professioneel.mp4"
  ],
  "qasgasisz": [
    "alerts/qasgasisz.mp4"
  ],
  "qastroldirect": [
    "alerts/qastroldirect.webm"
  ],
  "qastrolmoment": [
    "alerts/qastrolmoment.webm"
  ],
  "quepasaneng": [
    "alerts/quepasaneng.mp4"
  ],
  "rainbowroad": [
    "alerts/rainbowroad.mp4"
  ],
  "reported": [
    "alerts/reported.webm"
  ],
  "rock": [
    "alerts/rock.webm"
  ],
  "rutte": [
    "alerts/rutte.mp4"
  ],
  "sie": [
    "alerts/sie.mp4"
  ],
  "sjors": [
    "alerts/sjors.mp4"
  ],
  "skeleton": [
    "alerts/skeleton.mp4"
  ],
  "snipe": [
    "alerts/snipe.webm"
  ],
  "sorrylink": [
    "alerts/sorrylink.webm"
  ],
  "spongebob": [
    "alerts/spongebob.webm"
  ],
  "steve": [
    "alerts/steve.mp4"
  ],
  "stevestarwars": [
    "alerts/stevestarwars.mp4"
  ],
  "stop": [
    "alerts/stop.webm"
  ],
  "subscribelike": [
    "alerts/subscribelike.webm"
  ],
  "taxonweb": [
    "alerts/taxonweb.mp4"
  ],
  "tellsell": [
    "alerts/tellsell.mp4"
  ],
  "tongo": [
    "alerts/tongo.webm"
  ],
  "tros": [
    "alerts/tros.mp4"
  ],
  "turf": [
    "alerts/turf.mp4"
  ],
  "usedtoknow": [
    "alerts/usedtoknow.mp4"
  ],
  "vismoment": [
    "alerts/vismoment.webm"
  ],
  "visprofessioneel": [
    "alerts/visprofessioneel.mp4"
  ],
  "vlag": [
    "alerts/vlag.mp4"
  ],
  "voetbalmoment": [
    "alerts/voetbalmoment.webm"
  ],
  "vrolijkpalen": [
    "alerts/vrolijkpalen.mp4"
  ],
  "waarschuwing": [
    "alerts/waarschuwing.mp4"
  ],
  "warnerbros": [
    "alerts/warnerbros.mp4"
  ],
  "wc": [
    "alerts/wc.mp4"
  ],
  "welkomdatjekijkt": [
    "alerts/welkomdatjekijkt.mp4"
  ],
  "weminendiamonds": [
    "alerts/weminendiamonds.mp4"
  ],
  "westereen": [
    "alerts/westereen.mp4"
  ],
  "woutmoment": [
    "alerts/woutmoment.mp4"
  ],
  "wwe": [
    "alerts/wwe.mp4"
  ],
  "xbox": [
    "alerts/xbox.webm"
  ],
  "youtube": [
    "alerts/youtube.mp4"
  ],
  "zeldanl": [
    "alerts/zeldanl.mp4"
  ],
  "zorgwekkend": [
    "alerts/zorgwekkend.mp4"
  ],
  "200vissen": [
    "alerts/200vissen.mp3"
  ],
  "150goals": [
    "alerts/150goals.mp3"
  ],
  "chatleeg": [
    "alerts/chatleeg.webm"
  ],
  "dislike": [
    "alerts/dislike.mp4"
  ],
  "manydoors": [
    "alerts/manydoors.mp4"
  ]
};
window.alertsLinks = alertsLinks;
