/* Auto-generated by tools/generate_alerts_links.py */
const alertsLinks = {
  "150goals": [
    "alerts/150goals.mp3"
  ],
  "200vissen": [
    "alerts/200vissen.mp3"
  ],
  "2euro": [
    "alerts/2euro.mp4"
  ],
  "3euro": [
    "alerts/3euro.mp4"
  ],
  "5euro": [
    "alerts/5euro.mp4"
  ],
  "7grandfeest": [
    "alerts/7grandfeest.webm"
  ],
  "adoringfan": [
    "alerts/adoringfan.webm"
  ],
  "adultswim": [
    "alerts/adultswim.webm"
  ],
  "attention": [
    "alerts/attention.webm"
  ],
  "author": [
    "alerts/author.webm"
  ],
  "baksteene": [
    "alerts/baksteene.webm"
  ],
  "banaantje": [
    "alerts/banaantje.mp4"
  ],
  "bathroom": [
    "alerts/bathroom.webm"
  ],
  "biem": [
    "alerts/biem.mp4"
  ],
  "bijnamaandag": [
    "alerts/bijnamaandag.mp4"
  ],
  "bijnaweekend": [
    "alerts/bijnaweekend.mp4"
  ],
  "boek": [
    "alerts/boek.mp4"
  ],
  "boek2": [
    "alerts/boek2.mp4"
  ],
  "boring": [
    "alerts/boring.mp4",
    "alerts/boring.webm"
  ],
  "bos": [
    "alerts/bos.webm"
  ],
  "bowserbrief": [
    "alerts/bowserbrief.webm"
  ],
  "brein": [
    "alerts/brein.mp4"
  ],
  "brickinthewall": [
    "alerts/brickinthewall.mp4"
  ],
  "browser": [
    "alerts/browser.mp4"
  ],
  "busintro": [
    "alerts/busintro.mp4"
  ],
  "busoutro": [
    "alerts/busoutro.mp4"
  ],
  "buurman": [
    "alerts/buurman.webm"
  ],
  "buurmankart": [
    "alerts/buurmankart.mp4"
  ],
  "cd": [
    "alerts/cd.mp4"
  ],
  "chatleeg": [
    "alerts/chatleeg.webm"
  ],
  "cj": [
    "alerts/cj.webm"
  ],
  "clownwc": [
    "alerts/clownwc.webm"
  ],
  "community": [
    "alerts/community.webm"
  ],
  "dghhps": [
    "alerts/dghhps.mp4"
  ],
  "dislike": [
    "alerts/dislike.mp4"
  ],
  "djkibbeling": [
    "alerts/djkibbeling.mp4"
  ],
  "dominoday": [
    "alerts/dominoday.mp4"
  ],
  "doneer": [
    "alerts/doneer.mp4"
  ],
  "dubbo": [
    "alerts/dubbo.mp3"
  ],
  "dvd": [
    "alerts/dvd.mp4"
  ],
  "eddywally": [
    "alerts/eddywally.webm"
  ],
  "emergencymeeting": [
    "alerts/emergencymeeting.webm"
  ],
  "estate": [
    "alerts/estate.mp4"
  ],
  "euro": [
    "alerts/euro.mp4"
  ],
  "feest": [
    "alerts/feest.webm"
  ],
  "fever": [
    "alerts/fever.webm"
  ],
  "fryslan": [
    "alerts/fryslan.mp4"
  ],
  "gameboy": [
    "alerts/gameboy.mp4"
  ],
  "gamefreak": [
    "alerts/gamefreak.mp4"
  ],
  "gamerwolde": [
    "alerts/gamerwolde.webm"
  ],
  "geenklier": [
    "alerts/geenklier.mp4"
  ],
  "geenneus": [
    "alerts/geenneus.webm"
  ],
  "gigachad": [
    "alerts/gigachad.webm"
  ],
  "gigavis": [
    "alerts/gigavis.webm"
  ],
  "gigawout": [
    "alerts/gigawout.webm"
  ],
  "griddy": [
    "alerts/griddy.webm"
  ],
  "hard": [
    "alerts/hard.webm"
  ],
  "hardehugo": [
    "alerts/hardehugo.mp4"
  ],
  "hardehugomoment": [
    "alerts/hardehugomoment.mp4"
  ],
  "hardepartijen": [
    "alerts/hardepartijen.mp4"
  ],
  "hardkoeksoep": [
    "alerts/hardkoeksoep.webm"
  ],
  "hardslide": [
    "alerts/hardslide.webm"
  ],
  "hello": [
    "alerts/hello.mp4"
  ],
  "hey": [
    "alerts/hey.mp4"
  ],
  "hie": [
    "alerts/hie.mp4"
  ],
  "hiereeneuro": [
    "alerts/hiereeneuro.mp4"
  ],
  "hondbed": [
    "alerts/hondbed.mp4"
  ],
  "hondlopen": [
    "alerts/hondlopen.mp4"
  ],
  "hondwijs": [
    "alerts/hondwijs.mp4"
  ],
  "hotelmario": [
    "alerts/hotelmario.webm"
  ],
  "hugoduro": [
    "alerts/hugoduro.mp4"
  ],
  "hugogenieter": [
    "alerts/hugogenieter.mp4"
  ],
  "humbertotantoe": [
    "alerts/humbertotantoe.webm"
  ],
  "humbertotantoeleeg": [
    "alerts/HumbertotantoeLeeg.webm"
  ],
  "iamsteve": [
    "alerts/iamsteve.mp4"
  ],
  "illegal": [
    "alerts/illegal.webm"
  ],
  "indetuin": [
    "alerts/indetuin.webm"
  ],
  "instructionbook": [
    "alerts/instructionbook.webm"
  ],
  "iwon": [
    "alerts/iwon.webm"
  ],
  "jeanmineur": [
    "alerts/jeanmineur.mp4"
  ],
  "kapiteinkoek": [
    "alerts/kapiteinkoek.mp4"
  ],
  "karbonkel": [
    "alerts/karbonkel.mp4"
  ],
  "karper": [
    "alerts/karper.webm"
  ],
  "karpergoudvis": [
    "alerts/karpergoudvis.webm"
  ],
  "kat": [
    "alerts/kat.webm"
  ],
  "kauloboszhard": [
    "alerts/kauloboszhard.webm"
  ],
  "kauloperron": [
    "alerts/kauloperron.mp4"
  ],
  "kippenrijder": [
    "alerts/kippenrijder.webm"
  ],
  "koekie": [
    "alerts/koekie.mp4"
  ],
  "kroncrv": [
    "alerts/kroncrv.mp4"
  ],
  "kunnen": [
    "alerts/kunnen.webm"
  ],
  "laborday": [
    "alerts/laborday.mp4"
  ],
  "labourday": [
    "alerts/labourday.mp4"
  ],
  "linkwritten": [
    "alerts/linkwritten.webm"
  ],
  "lordwout": [
    "alerts/lordwout.mp4"
  ],
  "manbijthond": [
    "alerts/manbijthond.mp4"
  ],
  "manydoors": [
    "alerts/manydoors.mp4"
  ],
  "mariokartkaulohard": [
    "alerts/mariokartkaulohard.webm"
  ],
  "mariokartworld": [
    "alerts/mariokartworld.mp4"
  ],
  "mes": [
    "alerts/mes.webm"
  ],
  "mexico": [
    "alerts/mexico.mp4"
  ],
  "minecraft": [
    "alerts/minecraft.webm"
  ],
  "minecraftwithgadget": [
    "alerts/minecraftwithgadget.mp4"
  ],
  "missionpassed": [
    "alerts/missionpassed.webm"
  ],
  "morshu": [
    "alerts/morshu.webm"
  ],
  "morshushop": [
    "alerts/morshushop.mp4"
  ],
  "mosterd": [
    "alerts/mosterd.mp4"
  ],
  "mythbusters": [
    "alerts/mythbusters.mp4"
  ],
  "narwal": [
    "alerts/narwal.webm"
  ],
  "netflix": [
    "alerts/netflix.webm"
  ],
  "nintendodirect": [
    "alerts/nintendodirect.webm"
  ],
  "noice": [
    "alerts/noice.webm"
  ],
  "noobbewaarder": [
    "alerts/noobbewaarder.mp4"
  ],
  "nos": [
    "alerts/nos.mp4"
  ],
  "pacman": [
    "alerts/pacman.mp4"
  ],
  "pannenkoek": [
    "alerts/pannenkoek.mp4"
  ],
  "peggle3": [
    "alerts/peggle3.mp4"
  ],
  "pif": [
    "alerts/pif.webm"
  ],
  "professioneel": [
    "alerts/professioneel.mp4"
  ],
  "puzzleleague": [
    "alerts/puzzleleague.mp4"
  ],
  "qasgasisz": [
    "alerts/qasgasisz.mp4"
  ],
  "qastrol": [
    "alerts/qastrol.webm"
  ],
  "qastroldirect": [
    "alerts/qastroldirect.webm"
  ],
  "qastrolmoment": [
    "alerts/qastrolmoment.webm"
  ],
  "quepasaneng": [
    "alerts/quepasaneng.mp4"
  ],
  "quepasanengmp4tmp": [
    "alerts/quepasaneng.mp4.tmp.mp4"
  ],
  "rainbowroad": [
    "alerts/rainbowroad.mp4"
  ],
  "reitse": [
    "alerts/reitse.webm"
  ],
  "reported": [
    "alerts/reported.webm"
  ],
  "reposted": [
    "alerts/reposted.mp4"
  ],
  "rock": [
    "alerts/rock.webm"
  ],
  "rtl4": [
    "alerts/rtl4.mp4"
  ],
  "rutte": [
    "alerts/rutte.mp4"
  ],
  "shrek": [
    "alerts/shrek.webm"
  ],
  "sie": [
    "alerts/sie.mp4"
  ],
  "sirenhead": [
    "alerts/sirenhead.webm"
  ],
  "sjors": [
    "alerts/sjors.mp4"
  ],
  "skeleton": [
    "alerts/skeleton.mp4"
  ],
  "snipe": [
    "alerts/snipe.webm"
  ],
  "sorrylink": [
    "alerts/sorrylink.webm"
  ],
  "spongebob": [
    "alerts/spongebob.webm"
  ],
  "steve": [
    "alerts/steve.mp4"
  ],
  "stevestarwars": [
    "alerts/stevestarwars.mp4"
  ],
  "stop": [
    "alerts/stop.webm"
  ],
  "subscribelike": [
    "alerts/subscribelike.webm"
  ],
  "taxonweb": [
    "alerts/taxonweb.mp4"
  ],
  "tellsell": [
    "alerts/tellsell.mp4"
  ],
  "theroom": [
    "alerts/theroom.webm"
  ],
  "toetjes": [
    "alerts/toetjes.webm"
  ],
  "tongo": [
    "alerts/tongo.webm"
  ],
  "tremblingfingers": [
    "alerts/tremblingfingers.webm"
  ],
  "tros": [
    "alerts/tros.mp4"
  ],
  "turf": [
    "alerts/turf.mp4"
  ],
  "urigeller": [
    "alerts/urigeller.mp4"
  ],
  "usedtoknow": [
    "alerts/usedtoknow.mp4"
  ],
  "visintro": [
    "alerts/visintro.webm"
  ],
  "vismoment": [
    "alerts/vismoment.webm"
  ],
  "visprofessioneel": [
    "alerts/visprofessioneel.mp4"
  ],
  "vlag": [
    "alerts/vlag.mp4"
  ],
  "voetbalmoment": [
    "alerts/voetbalmoment.webm"
  ],
  "vrolijkpalen": [
    "alerts/vrolijkpalen.mp4"
  ],
  "waarschuwing": [
    "alerts/waarschuwing.mp4"
  ],
  "walta": [
    "alerts/walta.mp4"
  ],
  "warnerbros": [
    "alerts/warnerbros.mp4"
  ],
  "wc": [
    "alerts/wc.mp4"
  ],
  "welkomdatjekijkt": [
    "alerts/welkomdatjekijkt.mp4"
  ],
  "weminendiamonds": [
    "alerts/weminendiamonds.mp4"
  ],
  "wes": [
    "alerts/wes.mp4"
  ],
  "westereen": [
    "alerts/westereen.mp4"
  ],
  "woutgenieter": [
    "alerts/woutgenieter.webm"
  ],
  "woutmoment": [
    "alerts/woutmoment.mp4"
  ],
  "woutschaap": [
    "alerts/woutschaap.mp4"
  ],
  "wow": [
    "alerts/wow.webm"
  ],
  "wwe": [
    "alerts/wwe.mp4"
  ],
  "xbox": [
    "alerts/xbox.webm"
  ],
  "youtube": [
    "alerts/youtube.mp4"
  ],
  "zeldanl": [
    "alerts/zeldanl.mp4"
  ],
  "zorgwekkend": [
    "alerts/zorgwekkend.mp4"
  ],
  "zwolle": [
    "alerts/zwolle.webm"
  ]
};
window.alertsLinks = alertsLinks;
