const noobPointsTable = [
	{ name: "150 goals!", code: "150goals", description: "Gefeliciteerd Qastrol, je hebt het gedaan! Qastrol heeft 150 goals gescoord", cost: 1000, type: "Muziek-alert", category: ["AI", "Qastrol"] },
	{ name: "Clear Chat", code: "chatleeg", description: "Maak de chat leeg met deze redeem (en krijg een geinig Gamecube intro filmpje)", cost: 2000, type: "Video-alert", category: ["Gaming", "Interactieve alert"] },
	{ name: "Look at all this damage", code: "damage", description: "En we gaan het repareren met flex shot", cost: 500, type: "Video-alert", category: ["Meme"] },
	{ name: "200 vissen", code: "200vissen", description: "Gefeliciteerd Qastrol, je hebt het gedaan! 200 vissen zijn gevangen", cost: 1000, type: "Muziek-alert", category: ["AI", "Qastrol"] },
	{ name: "Dislike, unsub, report", code: "dislike", description: "Dislike 👎 Unsub 👎 Unsub 👎", cost: 500, type: "Video-alert", category: ["Internet"] },
	{ name: "Halo: Hard Stuff", code: "hardstuff", description: "Hard stuff", cost: 500, type: "Audio-alert", category: ["AI"] },
	{ name: "Karper en Goudvis", code: "karpergoudvis", description: "Wanneer Karpers en goudvissen een YouTube kanaal zouden hebben", cost: 1000, type: "Video-alert", category: ["Internet", "Sport"] },
	{ name: "Louis van Gaal uitspraak", code: "vangaal", description: "Een beruchte Engelse uitspraak van Louis van Gaal wordt afgespeeld. Dit kunnen 22 uitspraken zijn", cost: 1000, type: "Video-alert", category: ["Sport"] },
	{ name: "Ed Edd n Eddy: Many Doors", code: "manydoors", description: "Many Doors (van Ed, Edd n Eddy)", cost: 1000, type: "Video-alert", category: ["TV"] },
	{ name: "Minecraft Steve", code: "minecraftsteve", description: "Hij mijnt in de stream", cost: 2000, type: "Video-alert", category: ["Gaming"] },
	{ name: "Noob-Power!", code: "noobpower", description: "Noob-Power!", cost: 500, type: "Audio-alert", category: ["Qastrol"] },
	{ name: "Vsauce: Or is it?", code: "orisit", description: "🤨", cost: 500, type: "Video-alert", category: ["Internet"] },
	{ name: "Pokémon: A Wild Pokémon", code: "wildpokemon", description: "Een wilde Pokémon", cost: 1000, type: "Video-alert", category: ["Gaming"] },
	{ name: "Robbie Rotten", code: "robbierotten", description: "Robbie Rotten komt langs..", cost: 3000, type: "Video-alert", category: ["TV", "Meme"] },
	{ name: "The Room: Oh hi Mark", code: "theroom", description: "Tommy Wiseau begroet Mark", cost: 3000, type: "Video-alert", category: ["Film", "Meme"] },
	{ name: "Timeout", code: "timeout", description: "Geef \"iemand\" een timeout", cost: 1000, type: "Video-alert", category: ["Interactieve alert", "Intro", "Twitch"] },
	{ name: "Uh Oh Sticky", code: "uhohsticky", description: "Diddy Kong plakt in de honing", cost: 500, type: "Audio-alert", category: ["Gaming"] },
	{ name: "Verder nergens om, maar we scoren goals", code: "wescorengoals", description: "WOE", cost: 1000, type: "Video-alert", category: ["Sport", "Muziek-alert"] },
	{ name: "Vis 200", code: "vis200", description: "De Vis 200, het ultieme visvang evenement aan het eind van het jaar (Top 2000)", cost: 5000, type: "Audio-alert", category: ["Hobby's", "Radio"] },
	{ name: "Vis Get", code: "visget", description: "Joepie, een vis gevangen", cost: 1000, type: "Audio-alert", category: ["Hobby's", "Gaming", "AI"] },
	{ name: "Verder nergens om, maar we vissen vissen", code: "wevissenvissen", description: "WOE", cost: 1000, type: "Video-alert", category: ["Gaming", "Muziek-alert"] },
	{ name: "F-Zero: You Got Noob-Power!", code: "fzero", description: "Je hebt Noob-Power", cost: 1000, type: "Audio-alert", category: ["Gaming"] },
	{ name: "Zelda CDi: Tapijt", code: "tapijt", description: "Link zweeft op een tapijt", cost: 1000, type: "Video-alert", category: ["Gaming"] },
	{ name: "Will Smith: That's hot", code: "thatshot", description: "Dat is heet", cost: 2000, type: "Video-alert", category: ["Meme", "Internet"] },
	{ name: "2 euro", code: "2euro", description: "Papa, mag ik alsjeblieft 2 euro voor de arme man die op straat staat te schreeuwen? <a href=\"https://www.youtube.com/watch?v=Fy-SqB2FiSQ\">Bron</a>", cost: 2390, type: "Video-alert", category: ["TV"] },
	{ name: "3 euro (in het Duits)", code: "3euro", description: "Hast du bitte 3 euro! <a href=\"https://www.youtube.com/watch?v=Is2jTgxNctI\">Bron</a>", cost: 1330, type: "Video-alert", category: ["Duitsland"] },
	{ name: "5 euro?", code: "5euro", description: "Op je muil gauw", cost: 960, type: "Video-alert", category: ["Meme"] },
	{ name: "Attention: all Mario Kart gamers", code: "attention", description: "Funky Kong needs your help", cost: 5850, type: "Video-alert", category: ["Gaming", "Meme"] },
	{ name: "Star Fox: BIEM!", code: "biem", description: "BIEM!", cost: 1950, type: "Video-alert", category: ["Gaming", "Meme"] },
	{ name: "VPRO Boeken", code: "boek", description: "Boek", cost: 4020, type: "Video-alert", category: ["TV"] },
	{ name: "Windows Movie Maker Boek intro", code: "boek2", description: "Boek", cost: 2010, type: "Video-alert", category: ["Computer", "Qastrol"] },
	{ name: "Halo: Boring", code: "boring", description: "Gee, it sure is boring around here", cost: 500, type: "Video-alert", category: ["Gaming"] },
	{ name: "Zelda CDI: Boring", code: "boring", description: "Gee, it sure is boring around here", cost: 860, type: "Video-alert", category: ["Gaming"] },
	{ name: "Hotel Mario: Bowser", code: "bowserbrief", description: "Dear pesky plumbers, the koopalings and I have taken over the Mushroom Kingdom", cost: 4000, type: "Video-alert", category: ["Gaming"] },
	{ name: "BREIN intro", code: "brein", description: "De inhoud van deze drager is beschermd door wetten van Intellectuele Eigendom waaronder de Auteurswet, de Wet op de Naburige Rechten, de Databankwet en de Beneluxmerkenwet.", cost: 5360, type: "Video-alert", category: ["Film"] },
	{ name: "Another Brick in the Wall", code: "brickinthewall", description: "Glefly Brauly zingt Another Brick in the Wall (Part 2) van Pink Floyd! <a href=\"https://www.youtube.com/watch?v=moShzA7xGTQ\">Bron</a>", cost: 15700, type: "Video-alert", category: ["Muziek-alert"] },
	{ name: "Buurman en Buurman intro", code: "buurman", description: "Buurman! Hé Buurman!", cost: 3160, type: "Video-alert", category: ["TV"] },
	{ name: "Buurman Kart", code: "buurmankart", description: "De nieuwste racing game voor Nintendo Switch", cost: 6150, type: "Video-alert", category: ["Gaming"] },
	{ name: "GTA San Andreas: Ah shit, here we go again", code: "cj", description: "Ah shit, here we go again", cost: 780, type: "Video-alert", category: ["Gaming"] },
	{ name: "Qastrol Community", code: "community", description: "Hard", cost: 750, type: "Video-alert", category: ["Meme", "Qastrol"] },
	{ name: "Don eren", code: "doneer", description: "Ik wil graag don eren", cost: 1510, type: "Video-alert", category: ["Meme"] },
	{ name: "DVD-reclame", code: "dvd", description: "De ongelofelijke DVD-technologie", cost: 2210, type: "Video-alert", category: ["TV"] },
	{ name: "Eddy Wally: Wow", code: "eddywally", description: "Wauw", cost: 1790, type: "Video-alert", category: ["Meme"] },
	{ name: "Among Us: Emergency Meeting", code: "emergencymeeting", description: "🚨", cost: 440, type: "Video-alert", category: ["Gaming"] },
	{ name: "It's free real estate", code: "estate", description: "It's free real estate", cost: 640, type: "Video-alert", category: ["Meme"] },
	{ name: "GIGACHAD", code: "gigachad", description: "GIGACHAD", cost: 5530, type: "Video-alert", category: ["Meme"] },
	{ name: "GIGAVIS", code: "gigavis", description: "De GIGACHAD van de vissen", cost: 5540, type: "Video-alert", category: ["Meme", "Dagelijks leven"] },
	{ name: "Hard!", code: "hard", description: "HAAAAAAAAAAAAAAAAAAAAAARD!!!!!!", cost: 600, type: "Video-alert", category: ["Twitch", "Harde Hugo"] },
	{ name: "Harde Hugo moment", code: "hardehugomoment", description: "Hard", cost: 2000, type: "Video-alert", category: ["Twitch", "Harde Hugo"] },
	{ name: "Harde partijen", code: "hardepartijen", description: "Dit programma wordt mede mogelijk gemaakt door harde partijen", cost: 990, type: "Video-alert", category: ["Twitch", "TV", "Harde Hugo"] },
	{ name: "Hardslide", code: "hardslide", description: "Hard over je beeldscherm", cost: 1900, type: "Video-alert", category: ["Twitch", "Harde Hugo"] },
	{ name: "Hello", code: "hello", description: "👋", cost: 1640, type: "Video-alert", category: ["Meme"] },
	{ name: "Vsauce: Hey", code: "hey", description: "Vsauce Michael zegt \"Hey\"", cost: 2440, type: "Video-alert", category: ["Meme", "Internet"] },
	{ name: "Hie", code: "hie", description: "Hie, I'm Qastrol", cost: 340, type: "Video-alert", category: ["Sport"] },
	{ name: "Hier, een euro!", code: "hiereeneuro", description: "AAAAAAAAAAAAAAAA", cost: 1580, type: "Video-alert", category: ["TV"] },
	{ name: "Hotel Mario intro", code: "hotelmario", description: "Nice of the princess to invite us over for dinner, 'ey Luigi", cost: 3170, type: "Video-alert", category: ["Gaming"] },
	{ name: "Hugo Duro", code: "hugoduro", description: "Hugo Duro, de Spaanse voetballer die ook wel bekend staat als Harde Hugo.", cost: 2470, type: "Video-alert", category: ["Harde Hugo", "Sport"] },
	{ name: "Minecraft Movie: I am Steve", code: "iamsteve", description: "Ik... ben Steve", cost: 1860, type: "Video-alert", category: ["Gaming", "Film"] },
	{ name: "Zelda CDI: This is illegal you know", code: "illegal", description: "Eén van de meest illegale cutscenes van Zelda CDI", cost: 2590, type: "Video-alert", category: ["Gaming"] },
	{ name: "Hotel Mario: Instructions", code: "instructionbook", description: "If you need instructions on how to get through the hotel, check the enclosed instruction book", cost: 3960, type: "Video-alert", category: ["Gaming"] },
	{ name: "Jean Mineur", code: "jeanmineur", description: "De reclame is voorbij", cost: 5190, type: "Video-alert", category: ["Film"] },
	{ name: "Karbonkel jumpscare", code: "karbonkel", description: "Karbonkel laat Mik hard schrikken", cost: 3750, type: "Video-alert", category: ["TV"] },
	{ name: "Kaulo perron", code: "kauloperron", description: "Een NS-aankondiging met straattaal", cost: 4270, type: "Video-alert", category: ["Dagelijks leven", "Meme"] },
	{ name: "Kingler zegt Koekie", code: "koekie", description: "Koekie (Pokémon Stadium)", cost: 1090, type: "Video-alert", category: ["Gaming"] },
	{ name: "KRO-NCRV Qastrol intro", code: "kroncrv", description: "Maak morgen mee", cost: 990, type: "Video-alert", category: ["TV", "Qastrol"] },
	{ name: "Labour Day song", code: "labourday", description: "Het traditionele Labour Day lied", cost: 2300, type: "Video-alert", category: ["Meme"] },
	{ name: "Zelda CDI: It is written", code: "linkwritten", description: "Only Link can destroy Ganon", cost: 900, type: "Video-alert", category: ["Gaming"] },
	{ name: "Mario Kart is kaulo hard", code: "mariokartkaulohard", description: "Mario Kart is kaulo hard", cost: 2500, type: "Video-alert", category: ["Gaming"] },
	{ name: "Gerard Joling: Mexico", code: "mexico", description: "Mexicoooooooooooooo", cost: 4930, type: "Video-alert", category: ["Meme", "Muziek-alert"] },
	{ name: "Minecraft Qastrol intro", code: "minecraft", description: "Leuk", cost: 3500, type: "Video-alert", category: ["Gaming", "Qastrol"] },
	{ name: "Minecraft with Gadget", code: "minecraftwithgadget", description: "Inspector Gadget doet een recensie van Minecraft", cost: 1630, type: "Video-alert", category: ["Gaming", "Internet", "Meme"] },
	{ name: "Morshu: You reposted in the wrong shop", code: "morshushop", description: "You reposted in the wrong neighbourhood", cost: 5770, type: "Video-alert", category: ["Meme", "Gaming"] },
	{ name: "Lekker ite mei Reitse: Mosterd", code: "mosterd", description: "Mosterd", cost: 3770, type: "Video-alert", category: ["TV", "Fryslân"] },
	{ name: "Mythbusters", code: "mythbusters", description: "💩", cost: 2480, type: "Video-alert", category: ["TV"] },
	{ name: "Netflix Qastrol intro", code: "netflix", description: "Je gaat een serie kijken en ziet dit", cost: 1250, type: "Video-alert", category: ["TV", "Qastrol"] },
	{ name: "Nintendo Direct: overgang", code: "nintendodirect", description: "And now for the first time in ten years", cost: 1260, type: "Video-alert", category: ["Internet"] },
	{ name: "De Noob Bewaarder", code: "noobbewaarder", description: "Ik weet nu, dat er een Noob Bewaarder bestaat", cost: 1810, type: "Video-alert", category: ["Muziek-alert"] },
	{ name: "NOS intro", code: "nos", description: "Het is 8 uur", cost: 2780, type: "Video-alert", category: ["TV"] },
	{ name: "Lekker ite mei Reitse: Pannenkoek", code: "pannenkoek", description: "Reitse wordt boos", cost: 780, type: "Video-alert", category: ["TV", "Fryslân"] },
	{ name: "Waarom dit paneel er niet professioneel uitziet?", code: "professioneel", description: "Omdat net als met mijn wachtscherm en pauze schermpjes en offline scherm ik het leuk vind zelf te tekenen omdat het juist grappig is als het zo lelijk is.", cost: 3340, type: "Video-alert", category: ["Internet", "Meme"] },
	{ name: "Qastrol Direct intro", code: "qastroldirect", description: "Een nieuwe presentatie", cost: 2810, type: "Video-alert", category: ["Internet", "Qastrol"] },
	{ name: "Qastrol moment", code: "qastrolmoment", description: "Wanneer Qastrol een episch gaming moment heeft", cost: 2250, type: "Video-alert", category: ["Gaming", "Qastrol"] },
	{ name: "¡Qué pasa, NENG!", code: "quepasaneng", description: "Een vervloekte Spaanse videogame.", cost: 3210, type: "Video-alert", category: ["Gaming"] },
	{ name: "Among Us: Body Reported", code: "reported", description: "Oei", cost: 670, type: "Video-alert", category: ["Gaming"] },
	{ name: "The Rock", code: "rock", description: "🤨", cost: 1140, type: "Video-alert", category: ["Meme", "Sport"] },
	{ name: "Mark Rutte breekt in de WWE ring (live reactie)", code: "rutte", description: "Het publiek gaat los", cost: 3920, type: "Video-alert", category: ["Sport"] },
	{ name: "SIE!", code: "sie", description: "JAAAA 😁😁🗣️NU heb ik hem echt goed 🗣️🗣️SIEEEEEE 🗣️🗣️ huh😮‍💨 Waaaaauuuuw😲 die was echt ziek man😌", cost: 2820, type: "Video-alert", category: ["Meme"] },
	{ name: "Qastrol sniper intro", code: "snipe", description: "Epische gamer intro", cost: 2500, type: "Video-alert", category: ["Qastrol"] },
	{ name: "Up Next: Spongebob", code: "spongebob", description: "De Nickelodeon programmering vervolgt zich met Spongebob", cost: 2740, type: "Video-alert", category: ["TV"] },
	{ name: "Minecraft Movie: I am Steve", code: "steve", description: "I.... am Steve", cost: 3370, type: "Video-alert", category: ["Gaming", "Film"] },
	{ name: "Minecraft Movie x Star Wars", code: "stevestarwars", description: "Steve komt Star Wars karakters tegen", cost: 5050, type: "Video-alert", category: ["Gaming", "Film"] },
	{ name: "Subscribe, like, comment", code: "subscribelike", description: "En vergeet het belletje niet", cost: 2500, type: "Video-alert", category: ["Internet"] },
	{ name: "Taxonweb.be", code: "taxonweb", description: "Vlaamse belastingaangifte", cost: 7590, type: "Video-alert", category: ["TV", "België"] },
	{ name: "Deze livestream wordt mede mogelijk gemaakt door Hard", code: "tellsell", description: "Hard", cost: 1240, type: "Video-alert", category: ["Harde Hugo"] },
	{ name: "Tongo", code: "tongo", description: "De legendarische Tongo.", cost: 5430, type: "Video-alert", category: ["Internet"] },
	{ name: "TROS intro", code: "tros", description: "De grootste familie van Nederland", cost: 1400, type: "Video-alert", category: ["TV"] },
	{ name: "Turf", code: "turf", description: "Vissers lachen om turf 😂", cost: 3770, type: "Video-alert", category: ["Dagelijks leven"] },
	{ name: "Somebody that Morshu used to know", code: "usedtoknow", description: "Morshu zingt", cost: 3670, type: "Video-alert", category: ["Meme", "Gaming"] },
	{ name: "Vis moment", code: "vismoment", description: "Wanneer vissen een episch gaming moment hebben", cost: 2250, type: "Video-alert", category: ["Gaming"] },
	{ name: "Waarom deze vis er niet professioneel uit ziet?", code: "visprofessioneel", description: "🐟", cost: 3200, type: "Video-alert", category: ["Gaming"] },
	{ name: "De vlag gaat eruit", code: "vlag", description: "yaaay", cost: 1470, type: "Video-alert", category: ["Meme"] },
	{ name: "Voetbal moment", code: "voetbalmoment", description: "Wanneer er een episch voetbal moment is", cost: 2000, type: "Video-alert", category: ["Sport"] },
	{ name: "Uri Geller: Waarschuwing", code: "waarschuwing", description: "Waarschuwing. De meeste optredens in deze show zijn levensgevaarlijk. Alleen goed getrainde, professionele mentalisten kunnen deze uitvoeren. Doe dit thuis nooit na!", cost: 3660, type: "Video-alert", category: ["TV"] },
	{ name: "Warner Bros intro", code: "warnerbros", description: "Warner Bros", cost: 3700, type: "Video-alert", category: ["TV"] },
	{ name: "Qastrol op de WC", code: "wc", description: "💩", cost: 880, type: "Video-alert", category: ["Qastrol"] },
	{ name: "Verder nergens om, maar we minen diamonds", code: "weminendiamonds", description: "WOE", cost: 2270, type: "Video-alert", category: ["Gaming"] },
	{ name: "De Westereen", code: "westereen", description: "Wolkom yn 'e Westereen", cost: 8920, type: "Video-alert", category: ["Internet", "Fryslân"] },
	{ name: "Lord Wout moment", code: "woutmoment", description: "Wanneer Wout een episch gaming moment heeft", cost: 4070, type: "Video-alert", category: ["Gaming", "Lord Wout"] },
	{ name: "WWE intro", code: "wwe", description: "De klassieke intro voor een WWE match", cost: 5760, type: "Video-alert", category: ["TV"] },
	{ name: "Zelda CDI: Nederlandse intro", code: "zeldanl", description: "Ik verveel me te pletter!", cost: 2520, type: "Video-alert", category: ["Gaming", "Nederland"] },
	{ name: "Zorgwekkend", code: "zorgwekkend", description: "Een zorgwekkende video van iemand die Baka Mitai van Yakuza zingt", cost: 6970, type: "Video-alert", category: ["Muziek-alert", "Gaming"] },
	{ name: "Rapper Sjors", code: "sjors", description: "Videoboodschappenbestellen.nl", cost: 1740, type: "Video-alert", category: ["Internet"] },
	{ name: "YouTube 2007 intro", code: "youtube", description: "Welkom bij mijn tutorial!", cost: 3230, type: "Video-alert", category: ["Internet"] },
	{ name: "GTA San Andreas: Mission Passed", code: "missionpassed", description: "+ RESPECT", cost: 2010, type: "Video-alert", category: ["Gaming"] },
	{ name: "Zelda CDI: I won", code: "iwon", description: "Link heeft gewonnen!", cost: 630, type: "Video-alert", category: ["Gaming"] },
	{ name: "Zelda CDI: Morshu", code: "morshu", description: "Ropes, bombs, lamp oil", cost: 2230, type: "Video-alert", category: ["Gaming"] },
	{ name: "Zelda CDI: Sorry Link", code: "sorrylink", description: "Come back when you're a little, mmmm, richer", cost: 1730, type: "Video-alert", category: ["Gaming"] },
	{ name: "Man Bijt Hond: Beter Bed", code: "hondbeterbed", description: "De hond van Man Bijt Hond springt op een Beter Bed-bed", cost: 890, type: "Video-alert", category: ["TV"] },
	{ name: "Man Bijt Hond: Lopen", code: "hondlopen", description: "De hond van Man Bijt hond is aan het lopen", cost: 880, type: "Video-alert", category: ["TV"] },
	{ name: "Man Bijt Hond: Wijzen", code: "manbijthond", description: "De hond van Man Bijt Hond is aan het wijzen", cost: 950, type: "Video-alert", category: ["TV"] },
	{ name: "QAS Gas is Z", code: "qasgasisz", description: "Wanneer Qastrol vergeet hoe hij gas moet geven", cost: 1770, type: "Video-alert", category: ["Qastrol", "Gaming"] },
	{ name: "Rainbow Road", code: "rainbowroad", description: "It's called a road, it's called a rainbow road", cost: 8480, type: "Video-alert", category: ["Gaming", "Muziek-alert", "Internet"] },
	{ name: "Schnappi Scary Skeletons", code: "skeleton", description: "Ich bin Schnappi das Krokodil", cost: 4270, type: "Video-alert", category: ["Muziek-alert", "Internet", "Duitsland"] },
	{ name: "smashbrostransition", code: "smashbrostransition", description: "Beschrijving voor smashbrostransition", cost: 740, type: "Video-alert", category: ["Gaming"] },
	{ name: "Michael Rosen: Noice", code: "noice", description: "Noice!", cost: 820, type: "Video-alert", category: ["Internet"] },
	{ name: "Browsers cassle", code: "browser", description: "Mario wz in a jail seel in browsers cassle and he was looked and couldn't get ouuuuuuuuuuuu!", cost: 1750, type: "Video-alert", category: ["Gaming"] },
	{ name: "Domino Day", code: "dominoday", description: "Live vanuit het WTC-Expo in Leeuwarden, is dit, Domino Day", cost: 1750, type: "Video-alert", category: ["TV"] },
	{ name: "Minecraft Movie: Kippenrijder", code: "kippenrijder", description: "Steve zegt \"kippenrijder\"", cost: 470, type: "Video-alert", category: ["Gaming", "Film"] },
	{ name: "Ik heb helemaal geen neus", code: "geenneus", description: "Heb geen neus, ik heb helemaal geen neus", cost: 1510, type: "Video-alert", category: ["Internet"] },
	{ name: "Baksteene kom nou terug", code: "baksteene", description: "Baksteene 🧱 kom nou terug... ☹️ ik was fout ❌ Ik ben alleen 😭 en heb het koud... 🥶", cost: 2090, type: "Video-alert", category: ["Gaming"] },
	{ name: "Gamerwolde", code: "gamerwolde", description: "Hier wonen alleen gamers", cost: 1250, type: "Video-alert", category: ["Gaming"] },
	{ name: "Welkom dat je kijkt", code: "welkomdatjekijkt", description: "Welkom, welkom, welkom dat je kijkt", cost: 950, type: "Video-alert", category: ["Internet"] },
	{ name: "adoringfan", code: "adoringfan", description: "Beschrijving voor adoringfan", cost: 2440, type: "Video-alert", category: ["Gaming"] },
	{ name: "humbertotantoe", code: "humbertotantoe", description: "Beschrijving voor humbertotantoe", cost: 2070, type: "Video-alert", category: ["TV", "Meme"] },
	{ name: "HumbertotantoeLeeg", code: "HumbertotantoeLeeg", description: "Beschrijving voor HumbertotantoeLeeg", cost: 2060, type: "Video-alert", category: ["TV", "Meme"] },
	{ name: "kauloboszhard", code: "kauloboszhard", description: "Beschrijving voor kauloboszhard", cost: 5740, type: "Video-alert", category: ["Meme", "TV"] },
	{ name: "stop", code: "stop", description: "Beschrijving voor stop", cost: 1910, type: "Video-alert", category: ["Gaming"] },
	{ name: "vrolijkpalen", code: "vrolijkpalen", description: "Beschrijving voor vrolijkpalen", cost: 1190, type: "Video-alert", category: ["AI"] },
	{ name: "xbox", code: "xbox", description: "Beschrijving voor xbox", cost: 1070, type: "Video-alert", category: ["Gaming", "Internet"] },
	{ name: "fever", code: "fever", description: "Beschrijving voor fever", cost: 6800, type: "Video-alert", category: ["Gaming"] },
	{ name: "mariokartworld", code: "mariokartworld", description: "Beschrijving voor mariokartworld", cost: 3970, type: "Video-alert", category: ["Gaming"] },
	{ name: "1, 2, Koeksoep", code: "12koeksoep", description: "Hugo is heel hard", cost: 5790, type: "Video-alert", category: ["Harde Hugo", "AI", "Gaming"] },
	{ name: "De Slimste Mens: 3-6-9", code: "369", description: "De eerste ronde van De Slimste Mens!", cost: 1920, type: "Video-alert", category: ["TV"] },
	{ name: "67", code: "67", description: "â¶ð¤·â·", cost: 1180, type: "Video-alert", category: ["Meme", "Internet"] },
	{ name: "7 GRAND FEEST", code: "7grandfeest", description: "GRAND FEEST?! FLEENTSTONES? GRAND FEEST? <a href=\\", cost: 2530, type: "Video-alert", category: ["Gaming"] },
	{ name: "Adult Swim bump", code: "adultswim", description: "Streamer is aan het laden..", cost: 3300, type: "Video-alert", category: ["TV"] },
	{ name: "Nintendo Alarmo - HARDe wekker", code: "alarmo", description: "Zo wordt je HARD wakker", cost: 4340, type: "Video-alert", category: ["Gaming", "Harde Hugo"] },
	{ name: "Douwe: Ardio, amore, ardio", code: "ardio", description: "Jij moet niet huilen", cost: 7940, type: "Muziek-alert", category: ["Muziek"] },
	{ name: "Trackmania: Author", code: "author", description: "Unbelievable!!!!! You just beat Nadeo's High Score", cost: 1760, type: "Audio-alert", category: ["Gaming"] },
	{ name: "Banaantje", code: "banaantje", description: "Hugo zegt 'banaantje'", cost: 750, type: "Video-alert", category: ["Harde Hugo"] },
	{ name: "I thought this was the bathroom", code: "bathroom", description: "Oh god", cost: 1760, type: "Video-alert", category: ["Meme", "TV"] },
	{ name: "Man Bijt Hond: Bijna maandag", code: "bijnamaandag", description: "Het is alweer bijna maandag", cost: 960, type: "Video-alert", category: ["TV"] },
	{ name: "Man Bijt Hond: Bijna weekend", code: "bijnaweekend", description: "Het is alweer bijna weekend", cost: 980, type: "Video-alert", category: ["TV"] },
	{ name: "Super Mario 64: BLJ", code: "blj", description: "Mario doet een BLJ", cost: 1700, type: "Video-alert", category: ["Gaming"] },
	{ name: "Mario Kart: Blooper", code: "blooper", description: "Een Blooper van Mario Kart spuit inkt over het scherm...", cost: 2580, type: "Video-alert", category: ["Gaming"] },
	{ name: "BOS!", code: "bos", description: "Wanneer je heel bos bent (boos)", cost: 1380, type: "Video-alert", category: ["Meme"] },
	{ name: "Postbus 51 KerstKnallers intro", code: "busintro", description: "Een KerstKnallers intro in de stijl van Postbus 51", cost: 760, type: "Video-alert", category: ["KerstKnallers", "TV"] },
	{ name: "Postbus 51 KerstKnallers outro", code: "busoutro", description: "Een KerstKnallers outro in de stijl van Postbus 51", cost: 1010, type: "Video-alert", category: ["KerstKnallers", "TV"] },
	{ name: "Lego Island: oops", code: "cd", description: "You have to put the cd in your computer", cost: 1330, type: "Video-alert", category: ["Gaming", "Meme"] },
	{ name: "Clown WC", code: "clownwc", description: "De angstaanjagende Clown WC, bekend van Johano1rct's Planet Coaster streams bij KerstKnallers", cost: 4440, type: "Video-alert", category: ["Gaming", "Twitch"] },
	{ name: "Curb Your Enthusiasm credits", code: "curb", description: "De meme van een rollende aftiteling met Curb Your Enthusiasm", cost: 3780, type: "Video-alert", category: ["Meme", "TV"] },
	{ name: "Fortnite Default Dance", code: "default", description: "De iconische default dance uit Fortnite", cost: 1960, type: "Video-alert", category: ["Gaming"] },
	{ name: "Desert Bus", code: "desertbus", description: "De beruchte videogame Desert Bus, waarin je 8 uur lang één recht stuk vooruit rijd, verschijnt op beeld. <a href=\\", cost: 2370, type: "Video-alert", category: ["Gaming"] },
	{ name: "DGHHPS", code: "dghhps", description: "De DGHHPS stream is binnenkort te zien bij twitch.tv/harde_hugo!", cost: 5240, type: "Video-alert", category: ["TV"] },
	{ name: "DJ Kibbeling", code: "djkibbeling", description: "Jalalalala, DJ Kibbeling", cost: 4820, type: "Video-alert", category: ["Muziek", "KerstKnallers"] },
	{ name: "Hier, een euro!", code: "euro", description: "<a href=\\", cost: 1580, type: "Video-alert", category: ["TV"] },
	{ name: "Het is feest!", code: "feest", description: "<a href=\\", cost: 2100, type: "Video-alert", category: ["TV"] },
	{ name: "Play it Forward Retro Dag: Gameboy intro", code: "gameboy", description: "Een retro-intro voor een Retro Dag", cost: 1480, type: "Video-alert", category: ["Gaming", "Intro", "Twitch"] },
	{ name: "KerstKnallers Gamefreak intro", code: "gamefreak", description: "In de stijl van PokÃ©mon FireRed/LeafGreen", cost: 2110, type: "Video-alert", category: ["KerstKnallers", "Gaming", "Intro"] },
	{ name: "GIGAWOUT", code: "gigawout", description: "Een soort GigaChad, maar dan Lord Wout", cost: 5540, type: "Video-alert", category: ["Lord Wout", "Meme"] },
	{ name: "Griddy bij KerstKnallers 2023", code: "griddy", description: "De griddy van KerstKnallers 2023", cost: 3520, type: "Video-alert", category: ["Muziek", "KerstKnallers"] },
	{ name: "Halo 3 x Zelda CDI", code: "haloboring", description: "Gee, it sure is boring around here", cost: 1440, type: "Video-alert", category: ["Gaming"] },
	{ name: "3D Hard met koeksoep", code: "hard3dkoeksoep", description: "HARD in 3D! (met een koeksoep)", cost: 600, type: "Video-alert", category: ["Twitch"] },
	{ name: "Harde Hugo moment", code: "hardehugo", description: "Voor de harde gaming momenten van Harde Hugo", cost: 2000, type: "Video-alert", category: ["Harde Hugo", "Intro", "Gaming"] },
	{ name: "Spoken van HARD", code: "hardspoken", description: "Spoken van HARD", cost: 3680, type: "Video-alert", category: ["Internet", "Nederland"] },
	{ name: "HHGregg", code: "hhgregg", description: "Christmas in July. <a href=\\", cost: 4780, type: "Video-alert", category: ["Dagelijks leven", "Meme"] },
	{ name: "Man Bijt Hond: Beter Bed", code: "hondbed", description: "EÃ©n van de bumpers van Man Bijt Hond, waarbij de hond op een Beter Bed springt", cost: 890, type: "Video-alert", category: ["TV"] },
	{ name: "Man Bijt Hond: Wijzen", code: "hondwijs", description: "EÃ©n van de bumpers van Man Bijt Hond, waarbij de hond wijst", cost: 950, type: "Video-alert", category: ["TV"] },
	{ name: "How", code: "how", description: " <a href=\\", cost: 2510, type: "Video-alert", category: ["Gaming", "Meme"] },
	{ name: "Harde Hugo genieter", code: "hugogenieter", description: "Gemiddelde Lekker spelen fan vs Gemiddelde Harde Hugo genieter", cost: 3950, type: "Video-alert", category: ["Harde Hugo"] },
	{ name: "Onze Poes en Buurmans Kater - Evening Stars", code: "indetuin", description: "Kattenliedje. Ze zijn toch niet te houden laat die beesten maar miauwen! In de tuin, bij ons in de tuin!", cost: 5220, type: "Video-alert", category: ["Muziek", "Dieren"] },
	{ name: "Hotel Mario: Instructions", code: "instructions", description: "Deel 3 van de Hotel Mario intro. If you need instructions on how to get through the hotel, check out the enclosed instruction book", cost: 3960, type: "Video-alert", category: ["Gaming"] },
	{ name: "Jerma's Thanksgiving wens", code: "jerma", description: "Happy Thanksgiving van Jerma", cost: 7900, type: "Video-alert", category: ["Twitch"] },
	{ name: "Kapitein Koek", code: "kapiteinkoek", description: "De iconische Kapitein Koek reclame. MMMMMMMMMMMMMMM Lekker (de entrance van KanarieArie). <a href=\\", cost: 6530, type: "Video-alert", category: ["TV"] },
	{ name: "Karpers, goudvissen", code: "karper", description: "Wat als karpers en goudvissen een YouTube kanaal hadden, en dit ze een intro video hadden?", cost: 2500, type: "Video-alert", category: ["Muziek", "Dieren"] },
	{ name: "Kerstonweb.be", code: "kerstonweb", description: "Een speciale Kerstknallers versie van een Belgische belastingsaangiftereclame", cost: 7490, type: "Video-alert", category: ["BelgiÃ«", "KerstKnallers"] },
	{ name: "Harde koprol", code: "koprol", description: "Harde Hugo doet een koprol", cost: 1220, type: "Video-alert", category: ["Harde Hugo"] },
	{ name: "SpongeBob intro kapitein", code: "kunnen", description: "Kunnen we kinderen? Aye aye kapitein!", cost: 2260, type: "Video-alert", category: ["TV", "Intro"] },
	{ name: "Labor Day song", code: "laborday", description: "Het traditionele labor day lied. <a href=\\", cost: 2300, type: "Video-alert", category: ["Muziek"] },
	{ name: "Hallo lieve mensen", code: "lievemensen", description: "Hallo lieve mensen, hallo met Wout", cost: 1560, type: "Video-alert", category: ["Lord Wout", "Meme"] },
	{ name: "Like & Subscribe", code: "likesubscribe", description: "Een YouTuber-outro. Vergeet niet te liken en te subscriben en te commenten", cost: 2500, type: "Video-alert", category: ["Internet"] },
	{ name: "Lord Wout moment", code: "lordwout", description: "Voor de gaming momenten van Lord Wout", cost: 4070, type: "Video-alert", category: ["Gaming", "Lord Wout"] },
	{ name: "Find Luigi", code: "luigi", description: "De iconische minigame van New Super Mario Bros en Super Mario 64 DS", cost: 4020, type: "Video-alert", category: ["Gaming"] },
	{ name: "Mes in het schilderij!", code: "mes", description: "Er wordt een mes in een schilderij gestoken, zoals bij de donatiereward bij de KerstKnallers schilderstreams van xDinomite", cost: 3120, type: "Video-alert", category: ["KerstKnallers"] },
	{ name: "De Mus", code: "mus", description: "Tsjielp tsjielp tsjielp", cost: 4460, type: "Video-alert", category: ["Dieren"] },
	{ name: "Narwal van der Zee!", code: "narwal", description: "Hij zwemt door de zee (de entrance video van NarwalvanderZee)", cost: 4100, type: "Video-alert", category: ["Dieren"] },
	{ name: "Nederland 1 bumper", code: "nederland1", description: "De reclame start", cost: 1830, type: "Video-alert", category: ["TV"] },
	{ name: "Here comes Pac-Man", code: "pacman", description: "Yoyoyoyoyoyoyo", cost: 4440, type: "Video-alert", category: ["Gaming", "Meme"] },
	{ name: "Hotel Mario: Pesky Plumbers", code: "peskyplumbers", description: "Deel 2 van de intro van Hotel Mario. Dear Pesky Plumbers, the koopalings and I have taken over the Mushroom Kingdom", cost: 4930, type: "Video-alert", category: ["Gaming"] },
	{ name: "Play it Forward: Nederland 1", code: "pif", description: "Een Play it Forward logo in de stijl van Nederland 1 in de jaren '90", cost: 5020, type: "Video-alert", category: [] },
	{ name: "Prikkelalarm", code: "prikkelalarm", description: "Als er te veel prikkels zijn, kan je het prikkelalarm inzetten", cost: 2820, type: "Video-alert", category: ["KerstKnallers"] },
	{ name: "PokÃ©mon Puzzle League toernooi", code: "puzzleleague", description: "Qastrol krijgt een uitnodiging voor het <a href=\\", cost: 3380, type: "Video-alert", category: [] },
	{ name: "Qastrol moment", code: "qastrol", description: "Voor als Qastrol een ziek gaming moment heeft", cost: 2260, type: "Video-alert", category: ["Intro", "Qastrol", "Gaming"] },
	{ name: "Lekker Ite Mei Reitse", code: "reitse", description: "Reitse Spanninga, de Fryske sjef. <a href=\\", cost: 4760, type: "Video-alert", category: ["TV", "FryslÃ¢n"] },
	{ name: "Zelda CDI: You Reposted In The Wrong Shop", code: "reposted", description: "<a href=\\", cost: 5770, type: "Video-alert", category: ["Gaming"] },
	{ name: "Rickroll", code: "rick", description: "Never gonna give you up", cost: 2260, type: "Video-alert", category: ["Meme"] },
	{ name: "Racen over de Groninger ringweg", code: "ringweg", description: "Racen met wilde muziek in Stad", cost: 6030, type: "Video-alert", category: ["Nederland", "Sport"] },
	{ name: "RTL4 KerstKnallers-bumper", code: "rtl4", description: "Een KerstKnallers bumper in de stijl van RTL4", cost: 790, type: "Video-alert", category: ["KerstKnallers", "TV"] },
	{ name: "SEGA", code: "sega", description: "De iconische SEGA jingle van de SEGA Genesis", cost: 1060, type: "Video-alert", category: ["Gaming"] },
	{ name: "Shaun het Schaap: Lord Wout", code: "shaun", description: "De Shaun het Schaap intro, maar dan met Lord Wout", cost: 10010, type: "Video-alert", category: ["Lord Wout", "Intro"] },
	{ name: "Shrek Horror", code: "shrek", description: "Een extreem enge mobiele game, met Shrek die danst op het titelscherm", cost: 1930, type: "Video-alert", category: ["Gaming", "Film"] },
	{ name: "Shrek ASMR", code: "shrekasmr", description: "Een zeer vervloekte ASMR-uitvoering van de film Shrek. <a href=\\", cost: 4620, type: "Video-alert", category: ["Internet", "Film"] },
	{ name: "Siren Head", code: "sirenhead", description: "Siren Head over je beeldscherm", cost: 2400, type: "Video-alert", category: ["Meme"] },
	{ name: "Skyrim intro", code: "skyrim", description: "Hey you. Finally awake?", cost: 4690, type: "Video-alert", category: ["Gaming", "Intro"] },
	{ name: "SpongeBob fluit", code: "spongefluit", description: "De fluit van SpongeBob uit de intro", cost: 670, type: "Video-alert", category: ["TV"] },
	{ name: "Spongebob: Sports Channel", code: "sportschannel", description: "Spongebob kijkt TV. <a href=\\", cost: 3510, type: "Video-alert", category: ["TV"] },
	{ name: "Teletekst", code: "teletekst", description: "Teletekst nieuwsberichten ð´", cost: 5000, type: "Video-alert", category: ["TV"] },
	{ name: "Tito Dick \\", code: "tito", description: "Tito Dick \\", cost: 1810, type: "Video-alert", category: ["TV"] },
	{ name: "Toetjes, Koekjes, Pannenkoekenmeel", code: "toetjes", description: "Van de stream van IntensBroodje van KerstKnallers 2024", cost: 4010, type: "Muziek-alert", category: ["KerstKnallers", "Muziek"] },
	{ name: "Hard Time: Trembling Fingers", code: "tremblingfingers", description: "De Trembling Fingers dans van Hard Time 3", cost: 2680, type: "Video-alert", category: ["Gaming"] },
	{ name: "De Nieuwe Uri Geller", code: "urigeller", description: "<a href=\\", cost: 3660, type: "Video-alert", category: ["TV"] },
	{ name: "200 Vissen: intro", code: "visintro", description: "Weet u het nog toen Qastrol 200 vissen vangde? De intro voor de 200 Vissen stream op twitch.tv/qastrol", cost: 3760, type: "Video-alert", category: ["Dieren", "Intro", "Qastrol"] },
	{ name: "Super Mario Bros 3: WALTA!", code: "walta", description: "WALTA! WALTA! WALTA!", cost: 7720, type: "Video-alert", category: ["Gaming", "Twitch"] },
	{ name: "Mario Kart, maar wat doet de rest dan?", code: "watdoetderest", description: "ð¤¨ð¤¨", cost: 2740, type: "Video-alert", category: ["Gaming"] },
	{ name: "KerstKnallers WIDM intro", code: "widm", description: "Een KerstKnallers-intro in de stijl van Wie is de Mol?", cost: 1230, type: "Video-alert", category: ["KerstKnallers", "TV", "Intro"] },
	{ name: "Lord Wout genieter", code: "woutgenieter", description: "Gemiddelde Lekker spelen fan vs gemiddelde Lord Wout genieter", cost: 3960, type: "Video-alert", category: ["Lord Wout", "Meme"] },
	{ name: "Eddy Wally: Wow", code: "wow", description: "Eddy Wally zegt \\", cost: 1790, type: "Video-alert", category: ["Meme"] },
	{ name: "Zo gaat het in Minecraft", code: "zogaat", description: "Een iconische Nederlandse Minecraft parodie. Besef.", cost: 4000, type: "Video-alert", category: ["Internet", "Gaming"] },
	{ name: "De provincie Zwolle", code: "zwolle", description: "De ðºï¸ provincie ðï¸ Zwolle ð³ð± staat ð§ nummer ð¢ Ã©Ã©n ð¥ met ð¤ technologie âï¸ van ð§ª teleportatie ð§ââï¸ Zo ð± hun ð¥ zijn ð«¶ wel ð gek ð¤ª man ð¨ ", cost: 3830, type: "Video-alert", category: ["Internet"] }
];