const noobPointsTable = [
	{ name: "150 goals!", code: "150goals", description: "Gefeliciteerd Qastrol, je hebt het gedaan! Qastrol heeft 150 goals gescoord", cost: 1000 },
	{ name: "Clear Chat", code: "chatleeg", description: "Maak de chat leeg met deze redeem (en krijg een geinig Gamecube intro filmpje)", cost: 2000 },
	{ name: "Look at all this damage", code: "damage", description: "En we gaan het repareren met flex shot", cost: 500 },
	{ name: "200 vissen", code: "200vissen", description: "Gefeliciteerd Qastrol, je hebt het gedaan! 200 vissen zijn gevangen", cost: 1000 },
	{ name: "Dislike, unsub, report", code: "dislike", description: "Een trainergevecht gaat van start", cost: 500 },
	{ name: "Halo: Hard Stuff", code: "hardstuff", description: "Hard stuff", cost: 500 },
	{ name: "Karper en Goudvis", code: "karpergoudvis", description: "Wanneer Karpers en goudvissen een YouTube kanaal zouden hebben", cost: 1000 },
	{ name: "Louis van Gaal uitspraak", code: "vangaal", description: "Een beruchte Engelse uitspraak van Louis van Gaal wordt afgespeeld. Dit kunnen 22 uitspraken zijn", cost: 1000 },
	{ name: "Ed Edd n Eddy: Many Doors", code: "manydoors", description: "Many Doors (van Ed, Edd n Eddy)", cost: 1000 },
	{ name: "Minecraft Steve", code: "minecraftsteve", description: "Hij mijnt in de stream", cost: 2000 },
	{ name: "Noob-Power!", code: "noobpower", description: "Noob-Power!", cost: 500 },
	{ name: "Vsauce: Or is it?", code: "orisit", description: "🤨", cost: 500 },
	{ name: "Pokémon: A Wild Pokémon", code: "wildpokemon", description: "Een wilde Pokémon", cost: 1000 },
	{ name: "Robbie Rotten", code: "robbierotten", description: "Robbie Rotten komt langs..", cost: 3000 },
	{ name: "The Room: Oh hi Mark", code: "theroom", description: "Tommy Wiseau begroet Mark", cost: 3000 },
	{ name: "Timeout", code: "timeout", description: "Geef \"iemand\" een timeout", cost: 1000 },
	{ name: "Uh Oh Sticky", code: "uhohsticky", description: "Diddy Kong plakt in de honing", cost: 500 },
	{ name: "Verder nergens om, maar we scoren goals", code: "wescorengoals", description: "WOE", cost: 1000 },
	{ name: "Vis 200", code: "vis200", description: "De Vis 200, het ultieme visvang evenement aan het eind van het jaar (Top 2000)", cost: 5000 },
	{ name: "Vis Get", code: "visget", description: "Joepie, een vis gevangen", cost: 1000 },
	{ name: "Verder nergens om, maar we vissen vissen", code: "wevissenvissen", description: "WOE", cost: 1000 },
	{ name: "F-Zero: You Got Noob-Power!", code: "fzero", description: "Je hebt Noob-Power", cost: 1000 },
	{ name: "Zelda CDi: Tapijt", code: "tapijt", description: "Link zweeft op een tapijt", cost: 1000 },
	{ name: "Will Smith: That's hot", code: "thatshot", description: "Dat is heet", cost: 2000 },
	{ name: "2 euro", code: "2euro", description: "Papa, mag ik alsjeblieft 2 euro voor de arme man die op straat staat te schreeuwen? <a href=\"https://www.youtube.com/watch?v=Fy-SqB2FiSQ\">Bron</a>", cost: 2390 },
	{ name: "3 euro (in het Duits)", code: "3euro", description: "Hast du bitte 3 euro! <a href=\"https://www.youtube.com/watch?v=Is2jTgxNctI\">Bron</a>", cost: 1330 },
	{ name: "5 euro?", code: "5euro", description: "Op je muil gauw", cost: 960 },
	{ name: "Attention: all Mario Kart gamers", code: "attention", description: "Funky Kong needs your help", cost: 5850 },
	{ name: "Star Fox: BIEM!", code: "biem", description: "BIEM!", cost: 1950 },
	{ name: "VPRO Boeken", code: "boek", description: "Boek", cost: 4020 },
	{ name: "Windows Movie Maker Boek intro", code: "boek2", description: "Boek", cost: 2010 },
	{ name: "Halo: Boring", code: "boring", description: "Gee, it sure is boring around here", cost: 500 },
	{ name: "Zelda CDI: Boring", code: "boring", description: "Gee, it sure is boring around here", cost: 860 },
	{ name: "Hotel Mario: Bowser", code: "bowserbrief", description: "Dear pesky plumbers, the koopalings and I have taken over the Mushroom Kingdom", cost: 4000 },
	{ name: "BREIN intro", code: "brein", description: "De inhoud van deze drager is beschermd door wetten van Intellectuele Eigendom waaronder de Auteurswet, de Wet op de Naburige Rechten, de Databankwet en de Beneluxmerkenwet.", cost: 5360 },
	{ name: "Another Brick in the Wall", code: "brickinthewall", description: "Glefly Brauly zingt Another Brick in the Wall (Part 2) van Pink Floyd! <a href=\"https://www.youtube.com/watch?v=moShzA7xGTQ\">Bron</a>", cost: 15700 },
	{ name: "Buurman en Buurman intro", code: "buurman", description: "Buurman! Hé Buurman!", cost: 3160 },
	{ name: "Buurman Kart", code: "buurmankart", description: "De nieuwste racing game voor Nintendo Switch", cost: 6150 },
	{ name: "GTA San Andreas: Ah shit, here we go again", code: "cj", description: "Ah shit, here we go again", cost: 780 },
	{ name: "Qastrol Community", code: "community", description: "Hard", cost: 750 },
	{ name: "Don eren", code: "doneer", description: "Ik wil graag don eren", cost: 1510 },
	{ name: "DVD-reclame", code: "dvd", description: "De ongelofelijke DVD-technologie", cost: 2210 },
	{ name: "Eddy Wally: Wow", code: "eddywally", description: "Wauw", cost: 1790 },
	{ name: "Among Us: Emergency Meeting", code: "emergencymeeting", description: "🚨", cost: 440 },
	{ name: "It's free real estate", code: "estate", description: "It's free real estate", cost: 640 },
	{ name: "GIGACHAD", code: "gigachad", description: "GIGACHAD", cost: 5530 },
	{ name: "GIGAVIS", code: "gigavis", description: "De GIGACHAD van de vissen", cost: 5540 },
	{ name: "Hard!", code: "hard", description: "HAAAAAAAAAAAAAAAAAAAAAARD!!!!!!", cost: 600 },
	{ name: "Harde Hugo moment", code: "hardehugomoment", description: "Hard", cost: 2000 },
	{ name: "Harde partijen", code: "hardepartijen", description: "Dit programma wordt mede mogelijk gemaakt door harde partijen", cost: 990 },
	{ name: "Hardslide", code: "hardslide", description: "Hard over je beeldscherm", cost: 1900 },
	{ name: "Hello", code: "hello", description: "👋", cost: 1640 },
	{ name: "Vsauce: Hey", code: "hey", description: "Vsauce Michael zegt \"Hey\"", cost: 2440 },
	{ name: "Hie", code: "hie", description: "Hie, I'm Qastrol", cost: 340 },
	{ name: "Hier, een euro!", code: "hiereeneuro", description: "AAAAAAAAAAAAAAAA", cost: 1580 },
	{ name: "Hotel Mario intro", code: "hotelmario", description: "Nice of the princess to invite us over for dinner, 'ey Luigi", cost: 3170 },
	{ name: "Hugo Duro", code: "hugoduro", description: "Hugo Duro, de Spaanse voetballer die ook wel bekend staat als Harde Hugo.", cost: 2470 },
	{ name: "Minecraft Movie: I am Steve", code: "iamsteve", description: "Ik... ben Steve", cost: 1860 },
	{ name: "Zelda CDI: This is illegal you know", code: "illegal", description: "Eén van de meest illegale cutscenes van Zelda CDI", cost: 2590 },
	{ name: "Hotel Mario: Instructions", code: "instructionbook", description: "If you need instructions on how to get through the hotel, check the enclosed instruction book", cost: 3960 },
	{ name: "Jean Mineur", code: "jeanmineur", description: "De reclame is voorbij", cost: 5190 },
	{ name: "Karbonkel jumpscare", code: "karbonkel", description: "Karbonkel laat Mik hard schrikken", cost: 3750 },
	{ name: "Kaulo perron", code: "kauloperron", description: "Een NS-aankondiging met straattaal", cost: 4270 },
	{ name: "Kingler zegt Koekie", code: "koekie", description: "Koekie (Pokémon Stadium)", cost: 1090 },
	{ name: "KRO-NCRV Qastrol intro", code: "kroncrv", description: "Maak morgen mee", cost: 990 },
	{ name: "Labour Day song", code: "labourday", description: "Het traditionele Labour Day lied", cost: 2300 },
	{ name: "Zelda CDI: It is written", code: "linkwritten", description: "Only Link can destroy Ganon", cost: 900 },
	{ name: "Mario Kart is kaulo hard", code: "mariokartkaulohard", description: "Mario Kart is kaulo hard", cost: 2500 },
	{ name: "Gerard Joling: Mexico", code: "mexico", description: "Mexicoooooooooooooo", cost: 4930 },
	{ name: "Minecraft Qastrol intro", code: "minecraft", description: "Leuk", cost: 3500 },
	{ name: "Minecraft with Gadget", code: "minecraftwithgadget", description: "Inspector Gadget doet een recensie van Minecraft", cost: 1630 },
	{ name: "Morshu: You reposted in the wrong shop", code: "morshushop", description: "You reposted in the wrong neighbourhood", cost: 5770 },
	{ name: "Lekker ite mei Reitse: Mosterd", code: "mosterd", description: "Mosterd", cost: 3770 },
	{ name: "Mythbusters", code: "mythbusters", description: "💩", cost: 2480 },
	{ name: "Netflix Qastrol intro", code: "netflix", description: "Je gaat een serie kijken en ziet dit", cost: 1250 },
	{ name: "Nintendo Direct: overgang", code: "nintendodirect", description: "And now for the first time in ten years", cost: 1260 },
	{ name: "De Noob Bewaarder", code: "noobbewaarder", description: "Ik weet nu, dat er een Noob Bewaarder bestaat", cost: 1810 },
	{ name: "NOS intro", code: "nos", description: "Het is 8 uur", cost: 2780 },
	{ name: "Lekker ite mei Reitse: Pannenkoek", code: "pannenkoek", description: "Reitse wordt boos", cost: 780 },
	{ name: "Waarom dit paneel er niet professioneel uitziet?", code: "professioneel", description: "Omdat net als met mijn wachtscherm en pauze schermpjes en offline scherm ik het leuk vind zelf te tekenen omdat het juist grappig is als het zo lelijk is.", cost: 3340 },
	{ name: "Qastrol Direct intro", code: "qastroldirect", description: "Een nieuwe presentatie", cost: 2810 },
	{ name: "Qastrol moment", code: "qastrolmoment", description: "Wanneer Qastrol een episch gaming moment heeft", cost: 2250 },
	{ name: "¡Qué pasa, NENG!", code: "quepasaneng", description: "Een vervloekte Spaanse videogame.", cost: 3210 },
	{ name: "Among Us: Body Reported", code: "reported", description: "Oei", cost: 670 },
	{ name: "The Rock", code: "rock", description: "🤨", cost: 1140 },
	{ name: "Mark Rutte breekt in de WWE ring (live reactie)", code: "rutte", description: "Het publiek gaat los", cost: 3920 },
	{ name: "SIE!", code: "sie", description: "JAAAA 😁😁🗣️NU heb ik hem echt goed 🗣️🗣️SIEEEEEE 🗣️🗣️ huh😮‍💨 Waaaaauuuuw😲 die was echt ziek man😌", cost: 2820 },
	{ name: "Qastrol sniper intro", code: "snipe", description: "Epische gamer intro", cost: 2500 },
	{ name: "Up Next: Spongebob", code: "spongebob", description: "De Nickelodeon programmering vervolgt zich met Spongebob", cost: 2740 },
	{ name: "Minecraft Movie: I am Steve", code: "steve", description: "I.... am Steve", cost: 3370 },
	{ name: "Minecraft Movie x Star Wars", code: "stevestarwars", description: "Steve komt Star Wars karakters tegen", cost: 5050 },
	{ name: "Subscribe, like, comment", code: "subscribelike", description: "En vergeet het belletje niet", cost: 2500 },
	{ name: "Taxonweb.be", code: "taxonweb", description: "Vlaamse belastingaangifte", cost: 7590 },
	{ name: "Deze livestream wordt mede mogelijk gemaakt door Hard", code: "tellsell", description: "Hard", cost: 1240 },
	{ name: "Tongo", code: "tongo", description: "De legendarische Tongo.", cost: 5430 },
	{ name: "TROS intro", code: "tros", description: "De grootste familie van Nederland", cost: 1400 },
	{ name: "Turf", code: "turf", description: "Vissers lachen om turf 😂", cost: 3770 },
	{ name: "Somebody that Morshu used to know", code: "usedtoknow", description: "Morshu zingt", cost: 3670 },
	{ name: "Vis moment", code: "vismoment", description: "Wanneer vissen een episch gaming moment hebben", cost: 2250 },
	{ name: "Waarom deze vis er niet professioneel uit ziet?", code: "visprofessioneel", description: "🐟", cost: 3200 },
	{ name: "De vlag gaat eruit", code: "vlag", description: "yaaay", cost: 1470 },
	{ name: "Voetbal moment", code: "voetbalmoment", description: "Wanneer er een episch voetbal moment is", cost: 2000 },
	{ name: "Uri Geller: Waarschuwing", code: "waarschuwing", description: "Waarschuwing. De meeste optredens in deze show zijn levensgevaarlijk. Alleen goed getrainde, professionele mentalisten kunnen deze uitvoeren. Doe dit thuis nooit na!", cost: 3660 },
	{ name: "Warner Bros intro", code: "warnerbros", description: "Warner Bros", cost: 3700 },
	{ name: "Qastrol op de WC", code: "wc", description: "💩", cost: 880 },
	{ name: "Verder nergens om, maar we minen diamonds", code: "weminendiamonds", description: "WOE", cost: 2270 },
	{ name: "De Westereen", code: "westereen", description: "Wolkom yn 'e Westereen", cost: 8920 },
	{ name: "Lord Wout moment", code: "woutmoment", description: "Wanneer Wout een episch gaming moment heeft", cost: 4070 },
	{ name: "WWE intro", code: "wwe", description: "De klassieke intro voor een WWE match", cost: 5760 },
	{ name: "Zelda CDI: Nederlandse intro", code: "zeldanl", description: "Ik verveel me te pletter!", cost: 2520 },
	{ name: "Zorgwekkend", code: "zorgwekkend", description: "Een zorgwekkende video van iemand die Baka Mitai van Yakuza zingt", cost: 6970 },
	{ name: "Rapper Sjors", code: "sjors", description: "Videoboodschappenbestellen.nl", cost: 1740 },
	{ name: "YouTube 2007 intro", code: "youtube", description: "Welkom bij mijn tutorial!", cost: 3230 },
	{ name: "GTA San Andreas: Mission Passed", code: "missionpassed", description: "+ RESPECT", cost: 2010 },
	{ name: "Zelda CDI: I won", code: "iwon", description: "Link heeft gewonnen!", cost: 630 },
	{ name: "Zelda CDI: Morshu", code: "morshu", description: "Ropes, bombs, lamp oil", cost: 2230 },
	{ name: "Zelda CDI: Sorry Link", code: "sorrylink", description: "Come back when you're a little, mmmm, richer", cost: 1730 },
	{ name: "Man Bijt Hond: Beter Bed", code: "hondbeterbed", description: "De hond van Man Bijt Hond springt op een Beter Bed-bed", cost: 890 },
	{ name: "Man Bijt Hond: Lopen", code: "hondlopen", description: "De hond van Man Bijt hond is aan het lopen", cost: 880 },
	{ name: "Man Bijt Hond: Wijzen", code: "manbijthond", description: "De hond van Man Bijt Hond is aan het wijzen", cost: 950 },
	{ name: "QAS Gas is Z", code: "qasgasisz", description: "Wanneer Qastrol vergeet hoe hij gas moet geven", cost: 1770 },
	{ name: "Rainbow Road", code: "rainbowroad", description: "It's called a road, it's called a rainbow road", cost: 8480 },
	{ name: "Schnappi Scary Skeletons", code: "skeleton", description: "Ich bin Schnappi das Krokodil", cost: 4270 },
	{ name: "smashbrostransition", code: "smashbrostransition", description: "Beschrijving voor smashbrostransition", cost: 740 },
	{ name: "Michael Rosen: Noice", code: "noice", description: "Noice!", cost: 820 },
	{ name: "Browsers cassle", code: "browser", description: "Mario wz in a jail seel in browsers cassle and he was looked and couldn't get ouuuuuuuuuuuu!", cost: 1750 },
	{ name: "Domino Day", code: "dominoday", description: "Live vanuit het WTC-Expo in Leeuwarden, is dit, Domino Day", cost: 1750 },
	{ name: "Minecraft Movie: Kippenrijder", code: "kippenrijder", description: "Steve zegt \"kippenrijder\"", cost: 470 },
	{ name: "Ik heb helemaal geen neus", code: "geenneus", description: "Heb geen neus, ik heb helemaal geen neus", cost: 1510 },
	{ name: "Baksteene kom nou terug", code: "baksteene", description: "Baksteene 🧱 kom nou terug... ☹️ ik was fout ❌ Ik ben alleen 😭 en heb het koud... 🥶", cost: 2090 },
	{ name: "Gamerwolde", code: "gamerwolde", description: "Hier wonen alleen gamers", cost: 1250 },
	{ name: "Welkom dat je kijkt", code: "welkomdatjekijkt", description: "Welkom, welkom, welkom dat je kijkt", cost: 950 },
	{ name: "adoringfan", code: "adoringfan", description: "Beschrijving voor adoringfan", cost: 2440 },
	{ name: "humbertotantoe", code: "humbertotantoe", description: "Beschrijving voor humbertotantoe", cost: 2070 },
	{ name: "HumbertotantoeLeeg", code: "HumbertotantoeLeeg", description: "Beschrijving voor HumbertotantoeLeeg", cost: 2060 },
	{ name: "kauloboszhard", code: "kauloboszhard", description: "Beschrijving voor kauloboszhard", cost: 5740 },
	{ name: "stop", code: "stop", description: "Beschrijving voor stop", cost: 1910 },
	{ name: "vrolijkpalen", code: "vrolijkpalen", description: "Beschrijving voor vrolijkpalen", cost: 1190 },
	{ name: "xbox", code: "xbox", description: "Beschrijving voor xbox", cost: 1070 },
	{ name: "fever", code: "fever", description: "Beschrijving voor fever", cost: 6800 },
	{ name: "mariokartworld", code: "mariokartworld", description: "Beschrijving voor mariokartworld", cost: 3970 }
];