/* Auto-generated by tools/generate_soundeffect_links.py */
const soundeffectsLinks = {
  "ah": [
    "soundeffects/ah.mp3"
  ],
  "airhorn": [
    "soundeffects/airhorn.mp3"
  ],
  "alweereenwinnaar": [
    "soundeffects/alweereenwinnaar.mp3"
  ],
  "augh": [
    "soundeffects/augh.mp3"
  ],
  "biem": [
    "soundeffects/biem.mp3"
  ],
  "bonk": [
    "soundeffects/bonk.mp3"
  ],
  "boulevard": [
    "soundeffects/boulevard.mp3"
  ],
  "bruh": [
    "soundeffects/bruh.mp3"
  ],
  "cave": [
    "soundeffects/cave.mp3"
  ],
  "challenger": [
    "soundeffects/challenger.mp3"
  ],
  "creeper": [
    "soundeffects/creeper.mp3"
  ],
  "crickets": [
    "soundeffects/crickets.mp3"
  ],
  "cringe": [
    "soundeffects/cringe.mp3"
  ],
  "criticalhit": [
    "soundeffects/criticalhit.mp3"
  ],
  "crowbar": [
    "soundeffects/crowbar.mp3"
  ],
  "damage": [
    "soundeffects/damage.mp3"
  ],
  "disappointed": [
    "soundeffects/disappointed.mp3"
  ],
  "door": [
    "soundeffects/door.mp3"
  ],
  "drink": [
    "soundeffects/drink.mp3"
  ],
  "eat": [
    "soundeffects/eat.mp3"
  ],
  "eendje": [
    "soundeffects/eendje.mp3"
  ],
  "enderman": [
    "soundeffects/enderman.mp3"
  ],
  "error": [
    "soundeffects/error.mp3"
  ],
  "euroschreeuw": [
    "soundeffects/euroschreeuw.mp3"
  ],
  "failure": [
    "soundeffects/failure.mp3"
  ],
  "fallguys": [
    "soundeffects/fallguys.mp3"
  ],
  "fart": [
    "soundeffects/fart.mp3"
  ],
  "finale": [
    "soundeffects/finale.mp3"
  ],
  "fortnite": [
    "soundeffects/fortnite.mp3"
  ],
  "gameover": [
    "soundeffects/gameover.mp3"
  ],
  "gas": [
    "soundeffects/gas.mp3"
  ],
  "goeiemiddag": [
    "soundeffects/goeiemiddag.mp3"
  ],
  "hema": [
    "soundeffects/hema.mp3"
  ],
  "heybuurman": [
    "soundeffects/heybuurman.mp3"
  ],
  "hiereeneuro": [
    "soundeffects/hiereeneuro.mp3"
  ],
  "illuminati": [
    "soundeffects/illuminati.mp3"
  ],
  "internet": [
    "soundeffects/internet.mp3"
  ],
  "intro": [
    "soundeffects/intro.mp3"
  ],
  "join": [
    "soundeffects/join.mp3"
  ],
  "kloppen": [
    "soundeffects/kloppen.mp3"
  ],
  "knolpower": [
    "soundeffects/knolpower.mp3"
  ],
  "leave": [
    "soundeffects/leave.mp3"
  ],
  "meow": [
    "soundeffects/meow.mp3"
  ],
  "missed": [
    "soundeffects/missed.mp3"
  ],
  "mosterd": [
    "soundeffects/mosterd.mp3"
  ],
  "ns": [
    "soundeffects/ns.mp3"
  ],
  "oef": [
    "soundeffects/oef.mp3"
  ],
  "ohmygod": [
    "soundeffects/ohmygod.mp3"
  ],
  "opjemuil": [
    "soundeffects/opjemuil.mp3"
  ],
  "ping": [
    "soundeffects/ping.mp3"
  ],
  "pipe": [
    "soundeffects/pipe.mp3"
  ],
  "punch": [
    "soundeffects/punch.mp3"
  ],
  "rctlaugh": [
    "soundeffects/rctlaugh.mp3"
  ],
  "rctscream": [
    "soundeffects/rctscream.mp3"
  ],
  "scorn": [
    "soundeffects/scorn.mp3"
  ],
  "shock": [
    "soundeffects/shock.mp3"
  ],
  "shutdown": [
    "soundeffects/shutdown.mp3"
  ],
  "sinisterlaugh": [
    "soundeffects/sinisterlaugh.mp3"
  ],
  "slimstemens": [
    "soundeffects/slimstemens.mp3"
  ],
  "startup": [
    "soundeffects/startup.mp3"
  ],
  "sus": [
    "soundeffects/sus.mp3"
  ],
  "taxonweb": [
    "soundeffects/taxonweb.mp3"
  ],
  "tickle": [
    "soundeffects/tickle.mp3"
  ],
  "tnt": [
    "soundeffects/tnt.mp3"
  ],
  "toilet": [
    "soundeffects/toilet.mp3"
  ],
  "twohours": [
    "soundeffects/twohours.mp3"
  ],
  "usb": [
    "soundeffects/usb.mp3"
  ],
  "verdomme": [
    "soundeffects/verdomme.mp3"
  ],
  "villager": [
    "soundeffects/villager.mp3"
  ],
  "vineboom": [
    "soundeffects/vineboom.mp3"
  ],
  "violin": [
    "soundeffects/violin.mp3"
  ],
  "watgoed": [
    "soundeffects/watgoed.mp3"
  ],
  "wauw": [
    "soundeffects/wauw.mp3"
  ],
  "whip": [
    "soundeffects/whip.mp3"
  ],
  "wide": [
    "soundeffects/wide.mp3"
  ],
  "witch": [
    "soundeffects/witch.mp3"
  ],
  "woef": [
    "soundeffects/woef.mp3"
  ],
  "wow": [
    "soundeffects/wow.mp3"
  ],
  "zombie": [
    "soundeffects/zombie.mp3"
  ],
  "yup": [
    "soundeffects/yup.mp3"
  ]
};
window.soundeffectsLinks = soundeffectsLinks;
