const soundeffectsTable = [
	{ name: "(airhorn)", description: "Een typische meme-luchthoorn", category: ["Meme"] },
	{ name: "(alweereenwinnaar)", description: "Alweer een winnaar! Een kermis-sound effect", category: ["Dagelijkse leven"] },
	{ name: "(augh)", description: "HUUUUUUUAAAAAAAAAAGH", category: ["Meme"] },
	{ name: "(biem)", description: "BIEM!", category: ["Meme"] },
	{ name: "(bonk)", description: "BONK!", category: ["Meme", "TV"] },
	{ name: "(bruh)", description: "Bruh", category: ["Meme"] },
	{ name: "(cave)", description: "Minecraft grotgeluid", category: ["Gaming"] },
	{ name: "(challenger)", description: "Een nieuwe challenger in Super Smash Bros", category: ["Gaming"] },
	{ name: "(creeper)", description: "Creeper explosie geluid", category: ["Gaming"] },
	{ name: "(crickets)", description: "Krekels die fluiten 😴", category: ["Natuur", "TV"] },
	{ name: "(cringe)", description: "Cringe", category: ["Meme"] },
	{ name: "(criticalhit)", description: "Een critical hit in Super Smash Bros.", category: ["Gaming"] },
	{ name: "(crowbar)", description: "Half-Life 1 crowbar geluidseffect", category: ["Gaming"] },
	{ name: "(damage)", description: "Look at all this damage!", category: ["Meme"] },
	{ name: "(disappointed)", description: "Wanneer iets teleurstellends gebeurd in Spongebob", category: ["TV"] },
	{ name: "(door)", description: "Een Minecraft deur", category: ["Gaming"] },
	{ name: "(drink)", description: "Wanneer je drinkt in Minecraft", category: ["Gaming"] },
	{ name: "(eat)", description: "Wanneer je eet in Minecraft", category: ["Gaming"] },
	{ name: "(enderman)", description: "Wanneer een Enderman teleporteerd", category: ["Gaming"] },
	{ name: "(euroschreeuw)", description: "AAAAAAAAAAAAAAA", category: ["Meme"] },
	{ name: "(failure)", description: "\"Failure\" - Super Smash Bros Melee aankondiger", category: ["Gaming"] },
	{ name: "(fallguys)", description: "Wanneer je een ronde verliest in Fall Guys", category: ["Gaming"] },
	{ name: "(fart)", description: "Reverb Scheetgeluid", category: ["Meme"] },
	{ name: "(finale)", description: "De finale van De Slimste Mens is gespeeld!", category: ["TV"] },
	{ name: "(gameover)", description: "Game over in New Super Mario Bros.", category: ["Gaming"] },
	{ name: "(gas)", description: "Gas - Jerma985", category: ["Meme", "Internet"] },
	{ name: "(goeiemiddag)", description: "Goeiemiddag", category: ["TV"] },
	{ name: "(heybuurman)", description: "Hey buurman! Ajeto buur!", category: ["TV"] },
	{ name: "(hiereeneuro)", description: "Hier een euro, AAAAAAAAAAA", category: ["Meme"] },
	{ name: "(intro)", description: "Harde Hugo community sound effect 😳", category: ["Meme"] },
	{ name: "(join)", description: "Iemand joined de Discord call", category: ["Computer"] },
	{ name: "(kloppen)", description: "Iemand klopt op de deur", category: ["Dagelijkse leven"] },
	{ name: "(knolpower)", description: "Het is tijd voor wat Knolpower! Dikke vette peace!", category: ["TV", "Internet"] },
	{ name: "(leave)", description: "Iemand verlaat de Discord call", category: ["Computer"] },
	{ name: "(meow)", description: "Een miauwende kat in Minecraft", category: ["Gaming", "Natuur"] },
	{ name: "(mosterd)", description: "Mosterd - Reitse Spanninga", category: ["Fryslân", "TV"] },
	{ name: "(oef)", description: "Oef - Minecraft Steve", category: ["Gaming"] },
	{ name: "(opjemuil)", description: "Op je muil, gauw!", category: ["Meme"] },
	{ name: "(ping)", description: "Discord-ping geluid", category: ["Computer"] },
	{ name: "(pipe)", description: "een pijp die valt", category: ["Meme"] },
	{ name: "(rctlaugh)", description: "RCT2 lachen geluid", category: ["Gaming"] },
	{ name: "(rctscream)", description: "RCT2 schreeuw geluid", category: ["Gaming"] },
	{ name: "(scorn)", description: "SCORN - Jerma985", category: ["Meme", "Internet"] },
	{ name: "(shock)", description: "Wanneer iets schokkends in SpongeBob gebeurt", category: ["TV"] },
	{ name: "(sinisterlaugh)", description: "Sinister lachen geluid", category: ["Meme"] },
	{ name: "(slimstemens)", description: "Het bumpergeluid van De Slimste Mens (ter Wereld)", category: ["TV"] },
	{ name: "(sus)", description: "Het geluid wanneer je je rol ziet in Among Us. Sus", category: ["Gaming"] },
	{ name: "(taxonweb)", description: "Taxonweb.be", category: ["TV"] },
	{ name: "(tickle)", description: "Een tekenfilm kietel geluid", category: ["Meme", "TV"] },
	{ name: "(tnt)", description: "Een Minecraft TNT explosie", category: ["Gaming"] },
	{ name: "(toilet)", description: "Een WC die doorgespoeld wordt", category: ["Dagelijkse leven"] },
	{ name: "(twohours)", description: "2 uur later", category: ["TV"] },
	{ name: "(usb)", description: "Wanneer een USB-apparaat wordt verbonden aan de PC", category: ["Computer"] },
	{ name: "(verdomme)", description: "\"Verdomme\" - Martien Meiland", category: ["TV"] },
	{ name: "(villager)", description: "Minecraft Villager geluid", category: ["Gaming"] },
	{ name: "(vineboom)", description: "De Vineboom meme", category: ["Meme", "Internet"] },
	{ name: "(watgoed)", description: "\"Wat goed\" - Martien Meiland", category: ["TV"] },
	{ name: "(whip)", description: "ZWEEPslag", category: ["Meme"] },
	{ name: "(witch)", description: "Een enge heksenlach", category: ["Meme", "TV"] },
	{ name: "(woef)", description: "Minecraft hond", category: ["Gaming", "Natuur"] },
	{ name: "(wow)", description: "Het anime \"Wow\" geluid, veel gebruikt als meme", category: ["Meme", "Internet"] },
	{ name: "(zombie)", description: "Minecraft zombie", category: ["Gaming"] },
	{ name: "(ns)", description: "Het omroepgeluid op het NS-treinstation. Beste reizigers!", category: ["Dagelijkse leven"] },
	{ name: "(boulevard)", description: "De tune van RTL Boulevard!", category: ["TV"] },
	{ name: "(hema)", description: "Het fluitdeuntje van de HEMA!", category: ["TV"] },
	{ name: "(missed)", description: "Oh I missed! Wario heeft iets gemist in Mario Party 1", category: ["Meme", "Gaming"] },
	{ name: "(ohmygod)", description: "Wario heeft het helemaal gehad in Mario Party 1 en gooit er een vloekterm uit", category: ["Meme", "Gaming"] },
	{ name: "(ah)", description: "Het deuntje van de Albert Heijn", category: ["TV"] },
	{ name: "(shutdown)", description: "Het geluid wanneer je Windows XP afsluit", category: ["Computer"] },
	{ name: "(yup)", description: "Peter Griffin die yup zegt", category: ["Meme", "TV"] },
	{ name: "(violin)", description: "Een zeer verdrietige viool, van de meme", category: ["Meme"] },
	{ name: "(error)", description: "Een foutmelding in Windows XP", category: ["Computer"] },
	{ name: "(punch)", description: "Er wordt een klap uitgedeeld", category: ["Meme"] },
	{ name: "(wide)", description: "Iemand loopt heel wijd, de meme", category: ["Meme"] },
	{ name: "(wauw)", description: "Eddy Wally zegt \"Wow\"", category: ["TV", "Meme"] },
	{ name: "(startup)", description: "Je start je Windows XP computer op", category: ["Computer"] },
	{ name: "(internet)", description: "Het geluid van het opstarten van inbelinternet", category: ["Computer"] },
	{ name: "(eendje)", description: "kwak", category: ["Natuur"] },
	{ name: "(fortnite)", description: "Je gaat neer in Fortnite", category: ["Gaming"] },
	{ name: "(illuminati)", description: "❔", category: ["Meme"] },
	{ name: "(ehet)", description: "De Eigen Huis en Tuin jingle", category: ["TV"] },
	{ name: "(boos)", description: "Boze meme schreeuw", category: ["Meme"] },
	{ name: "(rizz)", description: "Geluidje", category: ["Meme"] },
	{ name: "(shocking)", description: "Meme geluidje voor een schokkende onthulling", category: ["Meme"] },
	{ name: "(ding)", description: "Een geluidje alsof je een punt krijgt in een quiz", category: ["Meme"] },
	{ name: "(aww)", description: "Aww, wat schattig!", category: ["Meme"] },
	{ name: "(applepay)", description: "Het geluid van een succesvolle Apple Pay betaling", category: ["Computer"] },
	{ name: "(alert)", description: "Metal Gear Solid alert geluid", category: ["Gaming"] },
	{ name: "(money)", description: "Geld geluidseffect", category: ["Meme"] },
	{ name: "(quack)", description: "Eend quack geluid", category: ["Natuur"] },
	{ name: "(helaas)", description: "Een teleurgesteld meme trompetje", category: ["Meme"] },
	{ name: "(camera)", description: "Het geluid van een camera die een foto maakt", category: ["Dagelijkse leven"] },
	{ name: "(scratch)", description: "Een lp scratch geluidseffect, bij een 'huh' moment", category: ["Meme"] },
	{ name: "(hellothere)", description: "Hello there! General Kenobi!", category: ["Meme", "TV"] },
	{ name: "(samsung)", description: "Het meldinggeluid van een Samsung telefoon", category: ["Computer"] },
	{ name: "(boing)", description: "Boing geluidseffect", category: ["Meme"] },
	{ name: "(pan)", description: "Een klap met een pan", category: ["Gaming"] },
	{ name: "(hammer)", description: "Een klap met een hamer", category: ["TV"] },
	{ name: "(confetti)", description: "Confetti geluidseffect", category: ["Meme"] },
	{ name: "(error10)", description: "Foutmelding in Windows 10", category: ["Computer"] },
	{ name: "(klik)", description: "Een klik geluidseffect", category: ["Dagelijkse leven"] },
	{ name: "(bite)", description: "Een bijt geluidseffect", category: ["TV"] },
	{ name: "(glas)", description: "Het geluid van brekend glas", category: ["Dagelijkse leven"] },
	{ name: "(moo)", description: "Een koe loeit", category: ["Natuur"] },
	{ name: "(question)", description: "Wanneer Phoenix Wright zich iets afvraagt in Ace Attorney", category: ["Gaming"] },
	{ name: "(sword)", description: "Het geluid van een zwaard dat getrokken wordt", category: ["TV"] },
	{ name: "(buzzer)", description: "Het geluid van een quiz buzzer", category: ["TV"] },
	{ name: "(charge)", description: "Het geluid van een iPhone die wordt opgeladen", category: ["Computer"] },
	{ name: "(teams)", description: "Het geluid van een Microsoft Teams berichtmelding", category: ["Computer"] },
	{ name: "(badum)", description: "Badum tss! Het geluid van een drum voor een grap", category: ["Meme"] },
	{ name: "(chomp)", description: "Een grote hap geluidseffect", category: ["Meme"] },
	{ name: "(niceshot)", description: "'Nice shot!' - Wii Sports", category: ["Gaming"] },
	{ name: "(doorbell)", description: "Het geluid van een deurbel", category: ["Dagelijkse leven"] },
	{ name: "(train)", description: "Het geluid van een voorbijrijdende trein", category: ["Dagelijkse leven"] },
	{ name: "(pop)", description: "Een ballon die kapot gaat", category: ["Meme"] },
	{ name: "(tv)", description: "Het geluid van een oude televisie zonder signaal", category: ["TV"] },
	{ name: "(whatsapp)", description: "Het geluid van een WhatsApp berichtmelding", category: ["Computer"] },
	{ name: "(kraak)", description: "Het geluid van een krakende deur", category: ["Dagelijkse leven"] },
	{ name: "(true)", description: "Als je iets correct hebt", category: ["Meme"] },
	{ name: "(evillaugh)", description: "Kwaadaardig lach geluidseffect", category: ["Meme"] },
];