/* Auto-generated by tools/generate_soundeffect_links.py */
const soundeffectsLinks = {
  "ah": [
    "soundeffects/ah.mp3"
  ],
  "airhorn": [
    "soundeffects/airhorn.mp3"
  ],
  "airhorn2": [
    "soundeffects/airhorn2.mp3"
  ],
  "alert": [
    "soundeffects/alert.mp3"
  ],
  "alweereenwinnaar": [
    "soundeffects/alweereenwinnaar.mp3"
  ],
  "anvil": [
    "soundeffects/anvil.mp3"
  ],
  "applepay": [
    "soundeffects/applepay.mp3"
  ],
  "augh": [
    "soundeffects/augh.mp3"
  ],
  "aww": [
    "soundeffects/aww.mp3"
  ],
  "badum": [
    "soundeffects/badum.mp3"
  ],
  "biem": [
    "soundeffects/biem.mp3"
  ],
  "bite": [
    "soundeffects/bite.mp3"
  ],
  "boing": [
    "soundeffects/boing.mp3"
  ],
  "boksbel": [
    "soundeffects/boksbel.mp3"
  ],
  "bonk": [
    "soundeffects/bonk.mp3"
  ],
  "boos": [
    "soundeffects/boos.mp3"
  ],
  "boulevard": [
    "soundeffects/boulevard.mp3"
  ],
  "bruh": [
    "soundeffects/bruh.mp3"
  ],
  "buzzer": [
    "soundeffects/buzzer.mp3"
  ],
  "camera": [
    "soundeffects/camera.mp3"
  ],
  "cave": [
    "soundeffects/cave.mp3"
  ],
  "challenger": [
    "soundeffects/challenger.mp3"
  ],
  "charge": [
    "soundeffects/charge.mp3"
  ],
  "chomp": [
    "soundeffects/chomp.mp3"
  ],
  "confetti": [
    "soundeffects/confetti.mp3"
  ],
  "creeper": [
    "soundeffects/creeper.mp3"
  ],
  "cricket": [
    "soundeffects/cricket.mp3"
  ],
  "crickets": [
    "soundeffects/crickets.mp3"
  ],
  "cringe": [
    "soundeffects/cringe.mp3"
  ],
  "criticalhit": [
    "soundeffects/criticalhit.mp3"
  ],
  "crowbar": [
    "soundeffects/crowbar.mp3"
  ],
  "damage": [
    "soundeffects/damage.mp3"
  ],
  "dash": [
    "soundeffects/dash.mp3"
  ],
  "dial": [
    "soundeffects/dial.mp3"
  ],
  "ding": [
    "soundeffects/ding.mp3"
  ],
  "disappear": [
    "soundeffects/disappear.mp3"
  ],
  "disappointed": [
    "soundeffects/disappointed.mp3"
  ],
  "door": [
    "soundeffects/door.mp3"
  ],
  "doorbell": [
    "soundeffects/doorbell.mp3"
  ],
  "drink": [
    "soundeffects/drink.mp3"
  ],
  "duolingo": [
    "soundeffects/duolingo.mp3"
  ],
  "eat": [
    "soundeffects/eat.mp3"
  ],
  "eendje": [
    "soundeffects/eendje.mp3"
  ],
  "ehet": [
    "soundeffects/ehet.mp3"
  ],
  "enderman": [
    "soundeffects/enderman.mp3"
  ],
  "error": [
    "soundeffects/error.mp3"
  ],
  "error10": [
    "soundeffects/error10.mp3"
  ],
  "euroschreeuw": [
    "soundeffects/euroschreeuw.mp3"
  ],
  "evillaugh": [
    "soundeffects/evillaugh.mp3"
  ],
  "failure": [
    "soundeffects/failure.mp3"
  ],
  "fallguys": [
    "soundeffects/fallguys.mp3"
  ],
  "fart": [
    "soundeffects/fart.mp3"
  ],
  "finale": [
    "soundeffects/finale.mp3"
  ],
  "fortnite": [
    "soundeffects/fortnite.mp3"
  ],
  "gameover": [
    "soundeffects/gameover.mp3"
  ],
  "gas": [
    "soundeffects/gas.mp3"
  ],
  "glas": [
    "soundeffects/glas.mp3"
  ],
  "goeiemiddag": [
    "soundeffects/goeiemiddag.mp3"
  ],
  "golfclap": [
    "soundeffects/golfclap.mp3"
  ],
  "goofy": [
    "soundeffects/goofy.mp3"
  ],
  "hammer": [
    "soundeffects/hammer.mp3"
  ],
  "helaas": [
    "soundeffects/helaas.mp3"
  ],
  "hellothere": [
    "soundeffects/hellothere.mp3"
  ],
  "hema": [
    "soundeffects/hema.mp3"
  ],
  "heybuurman": [
    "soundeffects/heybuurman.mp3"
  ],
  "heylisten": [
    "soundeffects/heylisten.mp3"
  ],
  "hiereeneuro": [
    "soundeffects/hiereeneuro.mp3"
  ],
  "illuminati": [
    "soundeffects/illuminati.mp3"
  ],
  "internet": [
    "soundeffects/internet.mp3"
  ],
  "intro": [
    "soundeffects/intro.mp3"
  ],
  "join": [
    "soundeffects/join.mp3"
  ],
  "klik": [
    "soundeffects/klik.mp3"
  ],
  "kloppen": [
    "soundeffects/kloppen.mp3"
  ],
  "knolpower": [
    "soundeffects/knolpower.mp3"
  ],
  "kraak": [
    "soundeffects/kraak.mp3"
  ],
  "kwek": [
    "soundeffects/kwek.mp3"
  ],
  "leave": [
    "soundeffects/leave.mp3"
  ],
  "lock": [
    "soundeffects/lock.mp3"
  ],
  "meow": [
    "soundeffects/meow.mp3"
  ],
  "missed": [
    "soundeffects/missed.mp3"
  ],
  "money": [
    "soundeffects/money.mp3"
  ],
  "moo": [
    "soundeffects/moo.mp3"
  ],
  "mosterd": [
    "soundeffects/mosterd.mp3"
  ],
  "mushroom": [
    "soundeffects/mushroom.mp3"
  ],
  "niceshot": [
    "soundeffects/niceshot.mp3"
  ],
  "ns": [
    "soundeffects/ns.mp3"
  ],
  "oa": [
    "soundeffects/oa.mp3"
  ],
  "odown": [
    "soundeffects/odown.mp3"
  ],
  "oef": [
    "soundeffects/oef.mp3"
  ],
  "ohmygod": [
    "soundeffects/ohmygod.mp3"
  ],
  "oleft": [
    "soundeffects/oleft.mp3"
  ],
  "opjemuil": [
    "soundeffects/opjemuil.mp3"
  ],
  "oright": [
    "soundeffects/oright.mp3"
  ],
  "oup": [
    "soundeffects/oup.mp3"
  ],
  "pan": [
    "soundeffects/pan.mp3"
  ],
  "pb": [
    "soundeffects/pb.mp3"
  ],
  "phone": [
    "soundeffects/phone.mp3"
  ],
  "ping": [
    "soundeffects/ping.mp3"
  ],
  "pipe": [
    "soundeffects/pipe.mp3"
  ],
  "pop": [
    "soundeffects/pop.mp3"
  ],
  "punch": [
    "soundeffects/punch.mp3"
  ],
  "quack": [
    "soundeffects/quack.mp3"
  ],
  "question": [
    "soundeffects/question.mp3"
  ],
  "rctlaugh": [
    "soundeffects/rctlaugh.mp3"
  ],
  "rctscream": [
    "soundeffects/rctscream.mp3"
  ],
  "ring": [
    "soundeffects/ring.mp3"
  ],
  "rizz": [
    "soundeffects/rizz.mp3"
  ],
  "runescape": [
    "soundeffects/runescape.mp3"
  ],
  "runfall": [
    "soundeffects/runfall.mp3"
  ],
  "samsung": [
    "soundeffects/samsung.mp3"
  ],
  "scorn": [
    "soundeffects/scorn.mp3"
  ],
  "scratch": [
    "soundeffects/scratch.mp3"
  ],
  "shield": [
    "soundeffects/shield.mp3"
  ],
  "shock": [
    "soundeffects/shock.mp3"
  ],
  "shocking": [
    "soundeffects/shocking.mp3"
  ],
  "shutdown": [
    "soundeffects/shutdown.mp3"
  ],
  "sinisterlaugh": [
    "soundeffects/sinisterlaugh.mp3"
  ],
  "slag": [
    "soundeffects/slag.mp3"
  ],
  "slimstemens": [
    "soundeffects/slimstemens.mp3"
  ],
  "startup": [
    "soundeffects/startup.mp3"
  ],
  "steam": [
    "soundeffects/steam.mp3"
  ],
  "sus": [
    "soundeffects/sus.mp3"
  ],
  "swoosh": [
    "soundeffects/swoosh.mp3"
  ],
  "sword": [
    "soundeffects/sword.mp3"
  ],
  "taxonweb": [
    "soundeffects/taxonweb.mp3"
  ],
  "teams": [
    "soundeffects/teams.mp3"
  ],
  "thee": [
    "soundeffects/thee.mp3"
  ],
  "tickle": [
    "soundeffects/tickle.mp3"
  ],
  "tnt": [
    "soundeffects/tnt.mp3"
  ],
  "toilet": [
    "soundeffects/toilet.mp3"
  ],
  "train": [
    "soundeffects/train.mp3"
  ],
  "true": [
    "soundeffects/true.mp3"
  ],
  "twohours": [
    "soundeffects/twohours.mp3"
  ],
  "usb": [
    "soundeffects/usb.mp3"
  ],
  "verdomme": [
    "soundeffects/verdomme.mp3"
  ],
  "villager": [
    "soundeffects/villager.mp3"
  ],
  "vineboom": [
    "soundeffects/vineboom.mp3"
  ],
  "violin": [
    "soundeffects/violin.mp3"
  ],
  "watgoed": [
    "soundeffects/watgoed.mp3"
  ],
  "wauw": [
    "soundeffects/wauw.mp3"
  ],
  "whatsapp": [
    "soundeffects/whatsapp.mp3"
  ],
  "whip": [
    "soundeffects/whip.mp3"
  ],
  "wide": [
    "soundeffects/wide.mp3"
  ],
  "witch": [
    "soundeffects/witch.mp3"
  ],
  "woah": [
    "soundeffects/woah.mp3"
  ],
  "woef": [
    "soundeffects/woef.mp3"
  ],
  "wow": [
    "soundeffects/wow.mp3"
  ],
  "yup": [
    "soundeffects/yup.mp3"
  ],
  "zml": [
    "soundeffects/zml.mp3"
  ],
  "zombie": [
    "soundeffects/zombie.mp3"
  ]
};
window.soundeffectsLinks = soundeffectsLinks;
