const soundeffectsTable = [
	{name: "(airhorn)", description: "Een typische meme-luchthoorn", category: ["Meme"], length: 4872},
	{ name: "(alweereenwinnaar)", description: "Alweer een winnaar! Een kermis-sound effect", category: ["Dagelijkse leven"], length: 1824},
	{ name: "(augh)", description: "HUUUUUUUAAAAAAAAAAGH", category: ["Meme"], length: 2232},
	{ name: "(biem)", description: "BIEM!", category: ["Meme"], length: 1541},
	{ name: "(bonk)", description: "BONK!", category: ["Meme", "TV"], length: 624},
	{ name: "(bruh)", description: "Bruh", category: ["Meme"], length: 496},
	{ name: "(cave)", description: "Minecraft grotgeluid", category: ["Gaming"], length: 3528},
	{ name: "(challenger)", description: "Een nieuwe challenger in Super Smash Bros", category: ["Gaming"], length: 3117},
	{ name: "(creeper)", description: "Creeper explosie geluid", category: ["Gaming"], length: 4728},
	{ name: "(crickets)", description: "Krekels die fluiten 😴", category: ["Natuur", "TV"], length: 4464},
	{ name: "(cringe)", description: "Cringe", category: ["Meme"], length: 1104},
	{ name: "(criticalhit)", description: "Een critical hit in Super Smash Bros.", category: ["Gaming"], length: 2448},
	{ name: "(crowbar)", description: "Half-Life 1 crowbar geluidseffect", category: ["Gaming"], length: 744},
	{ name: "(damage)", description: "Look at all this damage!", category: ["Meme"], length: 1896},
	{ name: "(disappointed)", description: "Wanneer iets teleurstellends gebeurd in Spongebob", category: ["TV"], length: 3553},
	{ name: "(door)", description: "Een Minecraft deur", category: ["Gaming"], length: 444},
	{ name: "(drink)", description: "Wanneer je drinkt in Minecraft", category: ["Gaming"], length: 1872},
	{ name: "(eat)", description: "Wanneer je eet in Minecraft", category: ["Gaming"], length: 1728},
	{ name: "(enderman)", description: "Wanneer een Enderman teleporteerd", category: ["Gaming"], length: 993},
	{ name: "(euroschreeuw)", description: "AAAAAAAAAAAAAAA", category: ["Meme"], length: 1824},
	{ name: "(failure)", description: "\"Failure\" - Super Smash Bros Melee aankondiger", category: ["Gaming"], length: 2880},
	{ name: "(fallguys)", description: "Wanneer je een ronde verliest in Fall Guys", category: ["Gaming"], length: 3936},
	{ name: "(fart)", description: "Reverb Scheetgeluid", category: ["Meme"], length: 3892},
	{ name: "(finale)", description: "De finale van De Slimste Mens is gespeeld!", category: ["TV"], length: 7285},
	{ name: "(gameover)", description: "Game over in New Super Mario Bros.", category: ["Gaming"], length: 2064},
	{ name: "(gas)", description: "Gas - Jerma985", category: ["Meme", "Internet"], length: 648},
	{ name: "(goeiemiddag)", description: "Goeiemiddag", category: ["TV"], length: 2647},
	{ name: "(heybuurman)", description: "Hey buurman! Ajeto buur!", category: ["TV"], length: 1176},
	{ name: "(hiereeneuro)", description: "Hier een euro, AAAAAAAAAAA", category: ["Meme"], length: 1944},
	{ name: "(intro)", description: "Harde Hugo community sound effect 😳", category: ["Meme"], length: 3024},
	{ name: "(join)", description: "Iemand joined de Discord call", category: ["Computer"], length: 1032},
	{ name: "(kloppen)", description: "Iemand klopt op de deur", category: ["Dagelijkse leven"], length: 720},
	{ name: "(knolpower)", description: "Het is tijd voor wat Knolpower! Dikke vette peace!", category: ["TV", "Internet"], length: 2445},
	{ name: "(leave)", description: "Iemand verlaat de Discord call", category: ["Computer"], length: 552},
	{ name: "(meow)", description: "Een miauwende kat in Minecraft", category: ["Gaming", "Natuur"], length: 705},
	{ name: "(mosterd)", description: "Mosterd - Reitse Spanninga", category: ["Fryslân", "TV"], length: 720},
	{ name: "(oef)", description: "Oef - Minecraft Steve", category: ["Gaming"], length: 1584},
	{ name: "(opjemuil)", description: "Op je muil, gauw!", category: ["Meme"], length: 1800},
	{ name: "(ping)", description: "Discord-ping geluid", category: ["Computer"], length: 504},
	{ name: "(pipe)", description: "een pijp die valt", category: ["Meme"], length: 3792},
	{ name: "(rctlaugh)", description: "RCT2 lachen geluid", category: ["Gaming"], length: 1071},
	{ name: "(rctscream)", description: "RCT2 schreeuw geluid", category: ["Gaming"], length: 3056},
	{ name: "(scorn)", description: "SCORN - Jerma985", category: ["Meme", "Internet"], length: 2304},
	{ name: "(shock)", description: "Wanneer iets schokkends in SpongeBob gebeurt", category: ["TV"], length: 3657},
	{ name: "(sinisterlaugh)", description: "Sinister lachen geluid", category: ["Meme"], length: 3239},
	{ name: "(slimstemens)", description: "Het bumpergeluid van De Slimste Mens (ter Wereld)", category: ["TV"], length: 6382},
	{ name: "(sus)", description: "Het geluid wanneer je je rol ziet in Among Us. Sus", category: ["Gaming"], length: 4519},
	{ name: "(taxonweb)", description: "Taxonweb.be", category: ["TV"], length: 2520},
	{ name: "(tickle)", description: "Een tekenfilm kietel geluid", category: ["Meme", "TV"], length: 2112},
	{ name: "(tnt)", description: "Een Minecraft TNT explosie", category: ["Gaming"], length: 2560},
	{ name: "(toilet)", description: "Een WC die doorgespoeld wordt", category: ["Dagelijkse leven"], length: 3056},
	{ name: "(twohours)", description: "2 uur later", category: ["TV"], length: 2508},
	{ name: "(usb)", description: "Wanneer een USB-apparaat wordt verbonden aan de PC", category: ["Computer"], length: 1320},
	{ name: "(verdomme)", description: "\"Verdomme\" - Martien Meiland", category: ["TV"], length: 967},
	{ name: "(villager)", description: "Minecraft Villager geluid", category: ["Gaming"], length: 1032},
	{ name: "(vineboom)", description: "De Vineboom meme", category: ["Meme", "Internet"], length: 3144},
	{ name: "(watgoed)", description: "\"Wat goed\" - Martien Meiland", category: ["TV"], length: 1959},
	{ name: "(whip)", description: "ZWEEPslag", category: ["Meme"], length: 1045},
	{ name: "(witch)", description: "Een enge heksenlach", category: ["Meme", "TV"], length: 3056},
	{ name: "(woef)", description: "Minecraft hond", category: ["Gaming", "Natuur"], length: 444},
	{ name: "(wow)", description: "Het anime \"Wow\" geluid, veel gebruikt als meme", category: ["Meme", "Internet"], length: 4232},
	{ name: "(zombie)", description: "Minecraft zombie", category: ["Gaming"], length: 2194},
	{ name: "(ns)", description: "Het omroepgeluid op het NS-treinstation. Beste reizigers!", category: ["Dagelijkse leven"], length: 3265},
	{ name: "(boulevard)", description: "De tune van RTL Boulevard!", category: ["TV"], length: 8725},
	{ name: "(hema)", description: "Het fluitdeuntje van de HEMA!", category: ["TV"], length: 5486},
	{ name: "(missed)", description: "Oh I missed! Wario heeft iets gemist in Mario Party 1", category: ["Meme", "Gaming"], length: 1704},
	{ name: "(ohmygod)", description: "Wario heeft het helemaal gehad in Mario Party 1 en gooit er een vloekterm uit", category: ["Meme", "Gaming"], length: 1968},
	{ name: "(ah)", description: "Het deuntje van de Albert Heijn", category: ["TV"], length: 4841},
	{ name: "(shutdown)", description: "Het geluid wanneer je Windows XP afsluit", category: ["Computer"], length: 1881},
	{ name: "(yup)", description: "Peter Griffin die yup zegt", category: ["Meme", "TV"], length: 579},
	{ name: "(violin)", description: "Een zeer verdrietige viool, van de meme", category: ["Meme"], length: 4598},
	{ name: "(error)", description: "Een foutmelding in Windows XP", category: ["Computer"], length: 1019},
	{ name: "(punch)", description: "Er wordt een klap uitgedeeld", category: ["Meme"], length: 1567},
	{ name: "(wide)", description: "Iemand loopt heel wijd, de meme", category: ["Meme"], length: 7393},
	{ name: "(wauw)", description: "Eddy Wally zegt \"Wow\"", category: ["TV", "Meme"], length: 1440},
	{ name: "(startup)", description: "Je start je Windows XP computer op", category: ["Computer"], length: 4911},
	{ name: "(internet)", description: "Het geluid van het opstarten van inbelinternet", category: ["Computer"], length: 2743},
	{ name: "(eendje)", description: "kwak", category: ["Natuur"], length: 960},
	{ name: "(fortnite)", description: "Je gaat neer in Fortnite", category: ["Gaming"], length: 1008},
	{ name: "(illuminati)", description: "❔", category: ["Meme"], length: 7889},
	{ name: "(ehet)", description: "De Eigen Huis en Tuin jingle", category: ["TV"], length: 7918},
	{ name: "(boos)", description: "Boze meme schreeuw", category: ["Meme"], length: 5472},
	{ name: "(rizz)", description: "Geluidje", category: ["Meme"], length: 1933},
	{ name: "(shocking)", description: "Meme geluidje voor een schokkende onthulling", category: ["Meme"], length: 5146},
	{ name: "(ding)", description: "Een geluidje alsof je een punt krijgt in een quiz", category: ["Meme"], length: 2978},
	{ name: "(aww)", description: "Aww, wat schattig!", category: ["Meme"], length: 3004},
	{ name: "(applepay)", description: "Het geluid van een succesvolle Apple Pay betaling", category: ["Computer"], length: 1032},
	{ name: "(alert)", description: "Metal Gear Solid alert geluid", category: ["Gaming"], length: 1934},
	{ name: "(money)", description: "Geld geluidseffect", category: ["Meme"], length: 3082},
	{ name: "(quack)", description: "Eend quack geluid", category: ["Natuur"], length: 1176},
	{ name: "(helaas)", description: "Een teleurgesteld meme trompetje", category: ["Meme"], length: 3709},
	{ name: "(camera)", description: "Het geluid van een camera die een foto maakt", category: ["Dagelijkse leven"], length: 2064},
	{ name: "(scratch)", description: "Een lp scratch geluidseffect, bij een 'huh' moment", category: ["Meme"], length: 810},
	{ name: "(hellothere)", description: "Hello there! General Kenobi!", category: ["Meme", "TV"], length: 862},
	{ name: "(samsung)", description: "Het meldinggeluid van een Samsung telefoon", category: ["Computer"], length: 2403},
	{ name: "(boing)", description: "Boing geluidseffect", category: ["Meme"], length: 1620},
	{ name: "(pan)", description: "Een klap met een pan", category: ["Gaming"], length: 653},
	{ name: "(hammer)", description: "Een klap met een hamer", category: ["TV"], length: 888},
	{ name: "(confetti)", description: "Confetti geluidseffect", category: ["Meme"], length: 1776},
	{ name: "(error10)", description: "Foutmelding in Windows 10", category: ["Computer"], length: 2821},
	{ name: "(klik)", description: "Een klik geluidseffect", category: ["Dagelijkse leven"], length: 1344},
	{ name: "(bite)", description: "Een bijt geluidseffect", category: ["TV"], length: 1056},
	{ name: "(glas)", description: "Het geluid van brekend glas", category: ["Dagelijkse leven"], length: 1384},
	{ name: "(moo)", description: "Een koe loeit", category: ["Natuur"], length: 1646},
	{ name: "(question)", description: "Wanneer Phoenix Wright zich iets afvraagt in Ace Attorney", category: ["Gaming"], length: 5094},
	{ name: "(sword)", description: "Het geluid van een zwaard dat getrokken wordt", category: ["TV"], length: 1202},
	{ name: "(buzzer)", description: "Het geluid van een quiz buzzer", category: ["TV"], length: 1149},
	{ name: "(charge)", description: "Het geluid van een iPhone die wordt opgeladen", category: ["Computer"], length: 1384},
	{ name: "(teams)", description: "Het geluid van een Microsoft Teams berichtmelding", category: ["Computer"], length: 985},
	{ name: "(badum)", description: "Badum tss! Het geluid van een drum voor een grap", category: ["Meme"], length: 1933},
	{ name: "(chomp)", description: "Een grote hap geluidseffect", category: ["Meme"], length: 522},
	{ name: "(niceshot)", description: "'Nice shot!' - Wii Sports", category: ["Gaming"], length: 1071},
	{ name: "(doorbell)", description: "Het geluid van een deurbel", category: ["Dagelijkse leven"], length: 8359},
	{ name: "(train)", description: "Het geluid van een voorbijrijdende trein", category: ["Dagelijkse leven"], length: 2586},
	{ name: "(pop)", description: "Een ballon die kapot gaat", category: ["Meme"], length: 496},
	{ name: "(tv)", description: "Het geluid van een oude televisie zonder signaal", category: ["TV"], length: 1080},
	{ name: "(whatsapp)", description: "Het geluid van een WhatsApp berichtmelding", category: ["Computer"], length: 1900},
	{ name: "(kraak)", description: "Het geluid van een krakende deur", category: ["Dagelijkse leven"], length: 2456},
	{ name: "(true)", description: "Als je iets correct hebt", category: ["Meme"], length: 1149},
	{ name: "(evillaugh)", description: "Kwaadaardig lach geluidseffect", category: ["Meme"], length: 1646},
];