// TTS table data. ElevenLabs voices support every language; TTSMonster only English; Google/Microsoft entries get language hints

const ttsTable = [
    // Bij elke stem wordt voortaan ook "type" vermeld: "Mannelijk" of "Vrouwelijk".
    // isAI: true voor gegenereerde AI-stemmen (waar bekend), false voor normale TTS (zoals Google/Microsoft)
    { name: "Adriaan", code: "adriaan:", description: "Adriaan van Bassie en Adriaan", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Microsoft David", code: "david:", description: "De Engelse mannelijke Microsoft-stem.", category: "Microsoft", type: "Mannelijk", isAI: false, languages: ["en"] },
    { name: "Donald Trump", code: "trump:", description: "Donald Trump als Engelse AI-stem", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Maarten van Rossem", code: "vanrossem:", description: "Maarten van Rossem, bekend van o.a. De Slimste Mens", type: "Mannelijk", category: "ElevenLabs", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "Gert Verhulst", code: "gertverhulst:", description: "Gert Verhulst van Studio 100", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "NPO1 Zenderstem", code: "npo1:", description: "De zenderstem van Nederland 1", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "SBS6 Zenderstem", code: "sbs6:", description: "De zenderstem van SBS6.", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Geert Wilders", code: "wilders:", description: "Geert Wilders, partijleider van de PVV", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Enzo Knol", code: "enzoknol:", description: "Enzo Knolpower!", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "ASMR-stem", code: "asmr:", description: "Een Engelse ASMR stem die niet in het Nederlands werkt!", category: "TTSMonster", type: "Vrouwelijk", isAI: true, languages: ["en"] },
    { name: "Baldi", code: "baldi:", description: "Baldi van Baldi's Basics!", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Joe Biden", code: "biden:", description: "Joe Biden! Joe Biden!", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Eminem", code: "eminem:", description: "Het is Slim Shady die je bericht in het Engels rapt", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "French", code: "french:", description: "Een TTS met een Frans accent die Engels spreekt", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "GLaDoS", code: "glados:", description: "GLaDoS van Portal", category: "TTSMonster", type: "Vrouwelijk", isAI: true, languages: ["en"] },
    { name: "Jazz Singer", code: "jazz:", description: "Een Engelse jazz-zanger zingt je bericht!", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "KKona", code: "kkona:", description: "Een Engelse AI-stem van iemand met een Amerikaans accent", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Klaus", code: "klaus:", description: "Een Engelse AI-stem van iemand met een Duits accent", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Morgan Freeman", code: "morganfreeman:", description: "Morgan Freeman, de bekende acteur", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Plankton", code: "plankton:", description: "Plankton (van de Engelse Spongebob)", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Ben Shapiro", code: "shapiro:", description: "Ben Shapiro", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Stanley Parable aankondiger", code: "stanleyparable:", description: "de aankondiger van The Stanley Parable", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "SpongeBob SquarePants", code: "spongebob:", description: "Spongebob van de Engelse versie van Spongebob Squarepants", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Watchmojo", code: "watchmojo:", description: "de aankondiger van Watch Mojo", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "The Weeknd", code: "weeknd:", description: "The Weekend zingt je bericht", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Eva Jinek", code: "jinek:", description: "Eva Jinek maar dan als AI", category: "ElevenLabs", type: "Vrouwelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "Jeroen Kijk in de Vegte", code: "kidv:", description: "Jeroen Kijk in de Vegte, bekend als radio-dj bij NPO Radio 2 en als de voice-over van RTL Boulevard en B&B Vol Liefde", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Dick Schoof", code: "dickschoof:", description: "De demissionaire minister-president van Nederland", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "Tell Sell stem", code: "tellsell:", description: "De Tell Sell stem", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Martien Meiland", code: "meiland:", description: "Martien Meiland, bekend van Chateau Meiland", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Ernie", code: "ernie:", description: "Ernie van Bert & Ernie", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "NS Omroepstem", code: "ns:", description: "De omroepstem op treinstations als AI-stem", category: "ElevenLabs", type: "Vrouwelijk", isAI: true, languages: ["*"] },
    { name: "Miel Monteur", code: "mielmonteur:", description: "Miel Monteur, bekend van de videogames", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "Frank Lammers", code: "franklammers:", description: "Frank Lammers van de Jumbo en Undercover", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Philip Freriks", code: "freriks:", description: "Philip Freriks van het NOS Journaal", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Arjen Lubach", code: "lubach:", description: "Arjen Lubach, bekend van Zondag met Lubach, de Avondshow en nu LUBACH op RTL4", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "Rob Trip", code: "robtrip:", description: "Rob Trip van het NOS Journaal", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Microsoft Hazel", code: "hazel:", description: "De vrouwelijke Engelse stem van Microsoft", category: "Microsoft", type: "Vrouwelijk", isAI: false, languages: ["en"] },
    { name: "Jan Smit", code: "jansmit:", description: "Jan Smit, de volkszanger uit Volendam", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "Gordon Heuckeroth", code: "gordon:", description: "Gordon Heuckeroth", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Bart Simpson", code: "bartsimpson:", description: "Bart Simpson van The Simpsons", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "Bassie", code: "bassie:", description: "Bassie van Bassie en Adriaan", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Halo aankondiger", code: "halo:", description: "Killtacular! De Halo-aankondiger (werkt beter in het Engels, maar werkt ook soort van in het Nederlands)", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Piepstem", code: "piepstem:", description: "Harry Piekema was het! De zelfde stem als 'joep:', maar dan een hogere stemtoon. Bekend van Among Us", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Gerard Joling", code: "joling:", description: "Gerard Joling als TTS-stem!", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "Frans Bauer", code: "bauer:", description: "Frans Bauer als TTS-stem!", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "Qastrol", code: "qastrol:", description: "Qastrol als AI-stem!", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "Sinterklaas", code: "sinterklaas:", description: "Sinterklaas als AI-stem! Dag hoor!", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    // Google-stemmen (toegevoegd). Voor Google stemmen: isAI: false, category: "Google", taal altijd Nederlands
    { name: "Google Emma", code: "emma:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Noah", code: "noah:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Lucas", code: "lucas:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Liam", code: "liam:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Sem", code: "sem:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Olivia", code: "olivia:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Nora", code: "nora:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Julia", code: "julia:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Mees", code: "mees:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Sofie", code: "sofie:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Noud", code: "noud:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Mila", code: "mila:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Adam", code: "adam:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Yara", code: "yara:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Daan", code: "daan:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Tessa", code: "tessa:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Eline", code: "eline:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Milou", code: "milou:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Sam", code: "sam:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Luuk", code: "luuk:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Guus", code: "guus:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Nina", code: "nina:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Bram", code: "bram:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Siem", code: "siem:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Gijs", code: "gijs:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Saar", code: "saar:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Floris", code: "floris:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Lotte", code: "lotte:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Anna", code: "anna:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Jesse", code: "jesse:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Ella", code: "ella:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Joep", code: "joep:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Google Fleur", code: "fleur:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "Google Teun", code: "teun:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "Dilan Yeşilgöz", code: "dilan:", description: "Dilan Yeşilgöz, partijleider van de VVD", category: "ElevenLabs", type: "Vrouwelijk", isAI: true, languages: ["*"] },
    { name: "Rob Jetten", code: "jetten:", description: "Rob Jetten, partijleider van D66", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "Willekeurige stem", code: "random:", description: "Kies een willekeurige Google TTS stem (standaardkeuze als er geen tts stem in het donatiebericht staat)", category: "Google", isAI: false, languages: ["nl"] }
];