// TTS table data. ElevenLabs voices support every language; TTSMonster only English; Google/Microsoft entries get language hints

const ttsTable = [
    { name: "adriaan:", description: "Adriaan van Bassie en Adriaan", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "david:", description: "De Engelse mannelijke Microsoft-stem.", category: "Microsoft", languages: ["en"] },
    { name: "trump:", description: "Donald Trump als Engelse AI-stem", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "vanrossem:", description: "Maarten van Rossem, bekend van o.a. De Slimste Mens", category: "ElevenLabs", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "gertverhulst:", description: "Gert Verhulst van Studio 100", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "npo1:", description: "De zenderstem van Nederland 1", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "sbs6:", description: "De zenderstem van SBS6.", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "wilders:", description: "Geert Wilders, partijleider van de PVV", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "enzoknol:", description: "Enzo Knolpower!", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "asmr2:", description: "Een Engelse ASMR stem die niet in het Nederlands werkt!", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "baldi:", description: "Baldi van Baldi's Basics!", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "biden:", description: "Joe Biden! Joe Biden!", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "eminem:", description: "Het is Slim Shady die je bericht in het Engels rapt", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "french:", description: "Een TTS met een Frans accent die Engels spreekt", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "glados:", description: "GLaDoS van Portal", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "jazz:", description: "Een Engelse jazz-zanger zingt je bericht!", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "kkona:", description: "Een Engelse AI-stem van iemand met een Amerikaans accent", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "klaus:", description: "Een Engelse AI-stem van iemand met een Duits accent", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "morganfreeman:", description: "Morgan Freeman, de bekende acteur", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "plankton:", description: "Plankton (van de Engelse Spongebob)", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "shapiro:", description: "Ben Shapiro", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "stanleyparable:", description: "de aankondiger van The Stanley Parable", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "spongebob:", description: "Spongebob van de Engelse versie van Spongebob Squarepants", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "watchmojo:", description: "de aankondiger van Watch Mojo", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "weeknd:", description: "The Weekend zingt je bericht", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "stefan:", description: "De tweede Vlaamse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "henk:", description: "De tweede Nederlandse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "tom:", description: "De derde Nederlandse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "anna:", description: "De eerste Nederlandse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "emma:", description: "De vierde Nederlandse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "julia:", description: "De vijfde Nederlandse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "martine:", description: "De eerste Vlaamse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "inge:", description: "De zesde Nederlandse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "niels:", description: "De zevende Nederlandse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "jan:", description: "De vierde Vlaamse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "astrid:", description: "De derde Vlaamse TTS stem van Google.", category: "Google", languages: ["nl"] },
    { name: "jinek:", description: "Eva Jinek maar dan als AI", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "kidv:", description: "Jeroen Kijk in de Vegte, bekend als de voice-over van RTL Boulevard en B&B Vol Liefde", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "dickschoof:", description: "De minister-president van Nederland", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "tellsell:", description: "De Tell Sell stem", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "meiland:", description: "Martien Meiland, bekend van Chateau Meiland", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "ernie:", description: "Ernie van Bert & Ernie", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "ns:", description: "De omroepstem op treinstations als AI-stem", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "mielmonteur:", description: "Miel Monteur, bekend van de videogames", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "franklammers:", description: "Frank Lammers van de Jumbo en Undercover", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "freriks:", description: "Philip Freriks van het NOS Journaal", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "lubach:", description: "Arjen Lubach van Zondag met Lubach en de Avondshow", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "robtrip:", description: "Rob Trip van het NOS Journaal", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "harry:", description: "De Britse mannelijke stem van Google", category: "Google", languages: ["en"] },
    { name: "news:", description: "De Britse mannelijke nieuwsstem van Google", category: "Google", languages: ["en"] },
    { name: "lucy:", description: "De Britse vrouwelijke stem van Google", category: "Google", languages: ["en"] },
    { name: "hazel:", description: "De vrouwelijke Engelse stem van Microsoft", category: "Microsoft", languages: ["en"] },
    { name: "jansmit:", description: "Jan Smit, de volkszanger uit Volendam", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "gordon:", description: "Gordon Heuckeroth", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "bartsimpson:", description: "Bart Simpson van The Simpsons", category: "TTSMonster", isAI: true, languages: ["en"] },
    { name: "bassie:", description: "Bassie van Bassie en Adriaan", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "asmr:", description: "Een Nederlandse ASMR-stem, maar deze werkt ook in het Engels", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "halo:", description: "Killtacular! De Halo-aankondiger (werkt beter in het Engels, maar werkt ook soort van in het Nederlands)", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "piepstem:", description: "Harry Piekema was het! De zelfde stem als 'henk:', maar dan een hogere stemtoon. Bekend van Among Us", category: "Google", languages: ["nl"] },
    { name: "joling:", description: "Gerard Joling als TTS-stem!", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "bauer:", description: "Frans Bauer als TTS-stem!", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "qastrol:", description: "Qastrol als AI-stem!", category: "ElevenLabs", isAI: true, languages: ["*"] },
    { name: "sinterklaas:", description: "Sinterklaas als AI-stem! Dag hoor!", category: "ElevenLabs", isAI: true, languages: ["*"] }
];