// TTS table data. ElevenLabs voices support every language; TTSMonster only English; Google/Microsoft entries get language hints

const ttsTable = [
    // Bij elke stem wordt voortaan ook "type" vermeld: "Mannelijk" of "Vrouwelijk".
    // isAI: true voor gegenereerde AI-stemmen (waar bekend), false voor normale TTS (zoals Google/Microsoft)
    { name: "adriaan:", description: "Adriaan van Bassie en Adriaan", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "david:", description: "De Engelse mannelijke Microsoft-stem.", category: "Microsoft", type: "Mannelijk", isAI: false, languages: ["en"] },
    { name: "trump:", description: "Donald Trump als Engelse AI-stem", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "vanrossem:", description: "Maarten van Rossem, bekend van o.a. De Slimste Mens", type: "Mannelijk", category: "ElevenLabs", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "gertverhulst:", description: "Gert Verhulst van Studio 100", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "npo1:", description: "De zenderstem van Nederland 1", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "sbs6:", description: "De zenderstem van SBS6.", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "wilders:", description: "Geert Wilders, partijleider van de PVV", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "enzoknol:", description: "Enzo Knolpower!", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "asmr2:", description: "Een Engelse ASMR stem die niet in het Nederlands werkt!", category: "TTSMonster", type: "Vrouwelijk", isAI: true, languages: ["en"] },
    { name: "baldi:", description: "Baldi van Baldi's Basics!", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "biden:", description: "Joe Biden! Joe Biden!", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "eminem:", description: "Het is Slim Shady die je bericht in het Engels rapt", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "french:", description: "Een TTS met een Frans accent die Engels spreekt", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "glados:", description: "GLaDoS van Portal", category: "TTSMonster", type: "Vrouwelijk", isAI: true, languages: ["en"] },
    { name: "jazz:", description: "Een Engelse jazz-zanger zingt je bericht!", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "kkona:", description: "Een Engelse AI-stem van iemand met een Amerikaans accent", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "klaus:", description: "Een Engelse AI-stem van iemand met een Duits accent", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "morganfreeman:", description: "Morgan Freeman, de bekende acteur", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "plankton:", description: "Plankton (van de Engelse Spongebob)", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "shapiro:", description: "Ben Shapiro", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "stanleyparable:", description: "de aankondiger van The Stanley Parable", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "spongebob:", description: "Spongebob van de Engelse versie van Spongebob Squarepants", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "watchmojo:", description: "de aankondiger van Watch Mojo", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "weeknd:", description: "The Weekend zingt je bericht", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "jinek:", description: "Eva Jinek maar dan als AI", category: "ElevenLabs", type: "Vrouwelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "kidv:", description: "Jeroen Kijk in de Vegte, bekend als de voice-over van RTL Boulevard en B&B Vol Liefde", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "dickschoof:", description: "De demissionaire minister-president van Nederland", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "tellsell:", description: "De Tell Sell stem", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "meiland:", description: "Martien Meiland, bekend van Chateau Meiland", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "ernie:", description: "Ernie van Bert & Ernie", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "ns:", description: "De omroepstem op treinstations als AI-stem", category: "ElevenLabs", type: "Vrouwelijk", isAI: true, languages: ["*"] },
    { name: "mielmonteur:", description: "Miel Monteur, bekend van de videogames", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "franklammers:", description: "Frank Lammers van de Jumbo en Undercover", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "freriks:", description: "Philip Freriks van het NOS Journaal", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "lubach:", description: "Arjen Lubach, bekend van Zondag met Lubach, de Avondshow en nu LUBACH op RTL4", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "robtrip:", description: "Rob Trip van het NOS Journaal", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "hazel:", description: "De vrouwelijke Engelse stem van Microsoft", category: "Microsoft", type: "Vrouwelijk", isAI: false, languages: ["en"] },
    { name: "jansmit:", description: "Jan Smit, de volkszanger uit Volendam", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "gordon:", description: "Gordon Heuckeroth", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "bartsimpson:", description: "Bart Simpson van The Simpsons", category: "TTSMonster", type: "Mannelijk", isAI: true, languages: ["en"] },
    { name: "bassie:", description: "Bassie van Bassie en Adriaan", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "halo:", description: "Killtacular! De Halo-aankondiger (werkt beter in het Engels, maar werkt ook soort van in het Nederlands)", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] },
    { name: "piepstem:", description: "Harry Piekema was het! De zelfde stem als 'henk:', maar dan een hogere stemtoon. Bekend van Among Us", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "joling:", description: "Gerard Joling als TTS-stem!", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "bauer:", description: "Frans Bauer als TTS-stem!", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "qastrol:", description: "Qastrol als AI-stem!", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    { name: "sinterklaas:", description: "Sinterklaas als AI-stem! Dag hoor!", category: "ElevenLabs", type: "Mannelijk", isAI: true, supportsAudioTags: true, languages: ["*"] },
    // Google-stemmen (toegevoegd). Voor Google stemmen: isAI: false, category: "Google", taal altijd Nederlands
    { name: "emma:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "noah:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "lucas:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "liam:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "sem:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "olivia:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "nora:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "julia:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "mees:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "sofie:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "noud:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "mila:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "adam:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "yara:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "daan:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "tessa:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "eline:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "milou:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "sam:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "luuk:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "guus:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "nina:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "bram:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "siem:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "gijs:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "saar:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "floris:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "lotte:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "anna:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "jesse:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "ella:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "joep:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "fleur:", description: "Google TTS (Nederlands)", category: "Google", type: "Vrouwelijk", isAI: false, languages: ["nl"] },
    { name: "teun:", description: "Google TTS (Nederlands)", category: "Google", type: "Mannelijk", isAI: false, languages: ["nl"] },
    { name: "dilan:", description: "Dilan Yeşilgöz, partijleider van de VVD", category: "ElevenLabs", type: "Vrouwelijk", isAI: true, languages: ["*"] },
    { name: "jetten:", description: "Rob Jetten, partijleider van D66", category: "ElevenLabs", type: "Mannelijk", isAI: true, languages: ["*"] }
];