#!/usr/bin/env python3
"""
generate_soundeffect_links.py

Scan the local `soundeffects/` directory and generate a JS file
`js/table/soundeffectslinks.js` that exports a mapping of normalized names
to available file paths. This lets client-side JS quickly know which
sound effects have preview audio without probing or downloading files.

Usage:
  python tools/generate_soundeffect_links.py

Options:
  --sounds-dir PATH   Directory to scan (default: soundeffects)
  --out PATH          Output JS file (default: js/table/soundeffectslinks.js)
  --exts LIST         Comma-separated list of extensions to include (default: .mp3)
  --dry-run           Print the mapping to stdout instead of writing
"""
import argparse
import json
import re
from pathlib import Path


def normalize(name: str) -> str:
    # same normalization as the alerts JS/py: remove non-alphanum and lowercase
    return re.sub(r'[^a-z0-9]', '', name, flags=re.IGNORECASE).lower()


def main():
    parser = argparse.ArgumentParser(description='Generate soundeffectslinks JS from soundeffects/ folder')
    parser.add_argument('--sounds-dir', default='soundeffects', help='Folder containing soundeffect audio files')
    parser.add_argument('--out', default='js/table/soundeffectslinks.js', help='Output JS file')
    parser.add_argument('--exts', default='.mp3', help='Comma-separated extensions to include (e.g. .mp3,.ogg,.wav)')
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()

    sounds_dir = Path(args.sounds_dir)
    if not sounds_dir.exists() or not sounds_dir.is_dir():
        print(f"Soundeffects directory not found: {sounds_dir}")
        return

    exts = {e.strip().lower() for e in args.exts.split(',') if e.strip()}

    mapping = {}
    for p in sorted(sounds_dir.rglob('*')):
        if not p.is_file():
            continue
        ext = p.suffix.lower()
        if ext not in exts:
            continue
        name = p.stem
        key = normalize(name)
        rel = str(p.as_posix())  # use forward slashes for JS
        mapping.setdefault(key, []).append(rel)

    # sort file lists for determinism
    for k in mapping:
        mapping[k].sort()

    js_out = f"/* Auto-generated by tools/generate_soundeffect_links.py */\n"
    js_out += "const soundeffectsLinks = " + json.dumps(mapping, ensure_ascii=False, indent=2) + ";\n"
    js_out += "window.soundeffectsLinks = soundeffectsLinks;\n"

    out_path = Path(args.out)
    if args.dry_run:
        print(js_out)
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(js_out, encoding='utf-8')
    print(f"Wrote {out_path} with {len(mapping)} entries")


if __name__ == '__main__':
    main()
