#!/usr/bin/env python3
"""
generate_alerts_links.py

Scan the local `alerts/` directory and generate a JS file
`js/table/alertslinks.js` that exports a mapping of normalized names
to available file paths. This lets client-side JS quickly know which
alerts have preview files without probing the server.

Usage:
  python tools/generate_alerts_links.py

Options:
  --alerts-dir PATH   Directory to scan (default: alerts)
  --out PATH          Output JS file (default: js/table/alertslinks.js)
  --dry-run           Print the mapping to stdout instead of writing

"""
import argparse
import json
import re
from pathlib import Path


def normalize(name: str) -> str:
    # same normalization as the JS: remove non-alphanum and lowercase
    return re.sub(r'[^a-z0-9]', '', name, flags=re.IGNORECASE).lower()


def main():
    parser = argparse.ArgumentParser(description='Generate alertslinks JS from alerts/ folder')
    parser.add_argument('--alerts-dir', default='alerts', help='Folder containing alert media')
    parser.add_argument('--out', default='js/table/alertslinks.js', help='Output JS file')
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()

    alerts_dir = Path(args.alerts_dir)
    if not alerts_dir.exists() or not alerts_dir.is_dir():
        print(f"Alerts directory not found: {alerts_dir}")
        return

    allowed_exts = {'.png', '.jpg', '.jpeg', '.gif', '.webp', '.mp3', '.ogg', '.wav', '.mp4', '.webm'}

    mapping = {}
    for p in sorted(alerts_dir.rglob('*')):
        if not p.is_file():
            continue
        ext = p.suffix.lower()
        if ext not in allowed_exts:
            continue
        name = p.stem
        key = normalize(name)
        rel = str(p.as_posix())  # forward slashes
        mapping.setdefault(key, []).append(rel)

    # sort file lists for determinism
    for k in mapping:
        mapping[k].sort()

    js_out = f"/* Auto-generated by tools/generate_alerts_links.py */\n"
    js_out += "const alertsLinks = " + json.dumps(mapping, ensure_ascii=False, indent=2) + ";\n"
    js_out += "window.alertsLinks = alertsLinks;\n"

    out_path = Path(args.out)
    if args.dry_run:
        print(js_out)
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(js_out, encoding='utf-8')
    print(f"Wrote {out_path} with {len(mapping)} entries")


if __name__ == '__main__':
    main()
